<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<body class="gray-bg">
    <div class="wrapper wrapper-content" >
        <div class="row" style="text-align: center;margin-top: 100px;">
            <img src="/Public/hplus/img/black_logo1.png">
            <div style="color: #1ab394;font-size: 20px;margin-top: 50px">在这里共享商企平台 - 后台管理系统</div>       
        </div>
    </div>
</body>
<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>