<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<?php require_once MODULE_PATH.'/View/Common/menu.phtml'; ?>
<section class="Hui-article-box">
<nav class="breadcrumb"><i class="Hui-iconfont">&#xe67f;</i> 首页
    <span class="c-gray en">&gt;</span>
    用户管理
    <span class="c-gray en">&gt;</span>
    用户列表 <span class="c-gray en">&gt;</span>
    <?php echo $res['nick_name']; ?> <a class="btn btn-success radius r" style="line-height:1.6em;margin-top:3px" href="javascript:location.replace(location.href);" title="刷新" ><i class="Hui-iconfont">&#xe68f;</i></a>
</nav>
<form action="/Videoadmin/member/edit" method="post" enctype="multipart/form-data" style="margin-right: 60px;left: -80px;position: relative;" class="form form-horizontal">
    <input type="hidden" name="member_id" value="<?php echo $res['member_id']; ?>">
    <div class="row cl">
        <label class="form-label col-xs-4 col-sm-3">手机号：</label>
        <div class="formControls col-xs-8 col-sm-9">
            <input type="text" class="input-text" autocomplete="off" disabled="true" name="phone_num" value="<?php echo $res['phone_num']; ?>">
        </div>
    </div>
    <div class="row cl">
        <label class="form-label col-xs-4 col-sm-3">昵称：</label>
        <div class="formControls col-xs-8 col-sm-9">
            <input type="text" class="input-text" autocomplete="off" name="nick_name" value="<?php echo $res['nick_name']; ?>">
        </div>
    </div>
    <div class="row cl">
        <label class="form-label col-xs-4 col-sm-3">密码：</label>
        <div class="formControls col-xs-8 col-sm-9">
            <input type="text" class="input-text" autocomplete="off" name="password" placeholder="当前密码密文：<?php echo $res['password']; ?>，【不填则不修改】">
        </div>
    </div>
    <div class="row cl">
        <div class="col-xs-8 col-sm-9 col-xs-offset-4 col-sm-offset-3">
            <input class="btn btn-primary radius" type="submit" value="提交">
            <input class="btn btn-primary radius" type="reset" value="重置">
        </div>
    </div>
</form>
</section>
<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>