<link href="/Public/hplus/css/font-awesome.min93e3.css?v=4.4.0" rel="stylesheet">
<h3 style='text-align: center;color: #1ab394;margin-top: 250px;line-height: 35px;'><i class="fa fa-check-circle" style="margin-right: 10px;font-size: 35px;"></i>恭喜您支付成功！您的业务已经处理完成</h3>
<br/>
<p style='text-align: center;'>
如果您发现支付宝被扣费，但并没有成功充值共享币或激活账户，请及时联系我们！<a href="http://<?php echo $_SERVER['HTTP_HOST']; ?>/business" style='color:#1ab394;margin-left: 5px; '> 返回商户平台>></a>
</p>