<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
	<body>
		<div class="free-regist-all">
			<form action="/Hospital/My/do_edit_patients" method="post" id="addsuf-form">
			    <div class="fr-re-it">
			        <a href="/Hospital/My/patients" class="fa fa-angle-left"></a>
			        <span class="fr-login-l">修改就诊人信息</span>
			    </div>
			    <div class="addSuf-mar"></div>
			    <div class="addSuf-main">
				    <div class="addSuf-name">
				    		<label class="as-name-sp">真实姓名</label>
				    		<div class="as-ma-right">
				    			<input type="text" class="as-name-in" id="as-name-in" name="patients_name" value="<?php echo $result['patients_name'] ?>">
				    		</div>
				    </div>
				    <!-- <div class="addSuf-sex">
				    		<span class="as-name-sp">性别</span>
				    		<div class="as-ma-right">
				    			<div class="in-fir-r">
				                    <input type="radio" class="sex" name="sex" value="1" checked>
				                    <label class="s-sex boy" >男</label>
				                    <input type="radio" class="sex sex-r" id="fr-sex" name="sex" value="2" >
				                    <label class="s-sex girl">女</label>
				                </div>
				    		</div>
				    </div> -->
				    <div class="addSuf-id">
				    		<label class="as-name-sp">身份证号</label>
				    		<div class="as-ma-right">
				    			<input type="number" class="as-id-in" placeholder="请输入就诊人的身份证号" id="as-id-in" name="id_card" value="<?php echo $result['id_card'] ?>">
				    		</div>
				    </div>
				    <div class="addSuf-age">
				    		<label class="as-name-sp">年龄</label>
				    		<div class="as-ma-right">
				    			<input type="number" class="as-age-in" id="as-age-in" name="patients_age" value="<?php echo $result['patients_age'] ?>">
				    		</div>
				    </div>
				    <div class="addSuf-tel">
				    		<lable class="as-name-sp">手机号码</lable>
				    		<div class="as-ma-right">
				    			<input type="number" class="as-tel-in" id="as-tel-in" name="patients_phone" value="<?php echo $result['patients_phone'] ?>">
				    		</div>
				    </div>
			    </div>
				<!-- <div class="resetsuf">
				    <input type="checkbox" id="resetsuf-in">
				    <label for="resetsuf-in">设为默认就诊人</label>
				</div> -->
				<input type="hidden" name="patients_id" value="<?php echo $_GET['patients_id'] ?>">
		</form>
		</div>
		<div class="addsuf-bottom">
		    <div class="addsuf-bot-but">确定</div>
		</div>
    </body>
<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>