<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
    <body>
		<div class="person" >
			<div class="per-top">
				<div class="pre-t-t">
    				<a href="/Hospital" class="fa fa-angle-left"></a>
                	<a href="javascript:;" onclick="javascript:logIn();" class="per-ri-pa">登录</a>
    			</div>
    			<div class="per-head">
    				<img src="/Public/Hospital/index/images/person.png" alt="" class="per-head-i"> 
    				<p class="per-head-t">未登录</p>
    			</div>
			</div>
			<div class="per-cen">
				<ul>
					<li>
						<a href="javascript:;" class="per-cen-a"  style="opacity: 0.3">
							<img src="/Public/Hospital/index/images/yisheng.png" alt="" class="per-sen-t">
							<span class="per-sen-t">我的医生</span>
						</a>
					</li>
					<li>
						<a href="javascript:;"  style="opacity: 0.3">
							<img src="/Public/Hospital/index/images/zixun.png" alt="" class="per-sen-t">
							<span class="per-sen-t">我的咨询</span>
						</a>
					</li>
					<li>
						<a href="javascript:;"  style="opacity: 0.3">
							<img src="/Public/Hospital/index/images/guahao.png" alt="" class="per-sen-t">
							<span class="per-sen-t">我的挂号</span>
						</a>
					</li>
					<li class="per-cen-li" >
						<a href="javascript:;"   style="opacity: 0.3">
							<img src="/Public/Hospital/index/images/jiuzhenren.png" alt="" class="per-sen-t">
							<span class="per-sen-t">常用就诊人</span>
						</a>
					</li>
					</ul>
			</div>
      <div class="introduce-footer clearfix">
		 <div class="tab-bar">
        <ul class="clearfix">
            <li class="tab-group  f_l  "><a href="/Hospital/Advice/lists">
                <span>会诊室</span></a></li>
            <li class="tab-home f_l "><a href="/Hospital/Index/index">
                <span>首页</span></a></li>
            <li class="tab-personal f_l personal-currunt"><a href="#">
                <span>我</span></a></li>
        </ul>
    </div>
	</div>
		</div>	
    </body>
    <script>
    function logIn(){
        window.location.href = "http://www.zzlhi.com/log/action/in?refererUrl=http://"+"<?php echo $_SERVER['HTTP_HOST'];?>"+"<?php echo $_SERVER['REQUEST_URI']; ?>"+"?holder=true";
    }
</script>
<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>