<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>

<style type="text/css">
    .pay_message{
        width: 100%;
        height: 1rem;
        z-index: 1;
        position: absolute;
        background-color: rgba(177, 171, 171, 0.37);
        top: 0.3rem;
        color: #FF9500;
        text-align: center;
        font-size: 0.37rem;
        line-height: 1rem;
    }
</style>

<!-- 播放页面 文件名称需要修改 -->
<div class="detal-all">
    <div class="detal-top">
        <div class="detal-v-b">
            <?php if($res['pay_num'] > 0 && !$buyEd): ?>
            <div class="pay_message" id="pay_message" onclick="javascript:buyThisVideo(<?php echo $res['video_id']; ?>);">立即购买</div>
            <?php endif; ?>
            <video class="detal-v-b" poster="<?php echo ($res['pay_num'] > 0 && !$buyEd) ? '/Public/Video/index/image/pay_message.jpg' : $res['pic_path']; ?>"  controls="controls" autoplay="autoplay">
                <?php if($res['pay_num'] > 0 && $buyEd): ?>
                <source src="<?php echo $res['play_url'][$_GET['num'] ? $_GET['num'] : 1]; ?>" type="video/mp4" />
                <?php elseif($res['pay_num'] > 0 && !$buyEd): ?>
                <source src="" type="video/mp4" />
                <?php else: ?>
                <source src="<?php echo $res['play_url'][$_GET['num'] ? $_GET['num'] : 1]; ?>" type="video/mp4" />
                <?php endif; ?>
            </video>
        </div>
        <div class="container">
            <div class="head">
                <span><?php echo $res['name']; ?></span>
            </div>
            <div class="contain-collect">
                <span><?php echo $res['class_name']; ?></span>
                <button <?php echo $isFavorited ? "disabled style='background-color:#ddd;" : ''; ?> style="background-color: #FF9500;color: #fff" id="favoritedButton" onclick="javascript:Interaction(<?php echo $res['video_id']; ?>,'favorite');" class="con-col-cang"><?php echo $isFavorited ? '已收藏' : '收藏'; ?></button>
                <button <?php echo $isZaned ? "disabled style='background-color:#ddd;'" : ''; ?> style="background-color: #FF9500;color: #fff" id="zanButton" onclick="javascript:Interaction(<?php echo $res['video_id']; ?>,'zan');" class="con-col-zan ">赞<b><?php echo $res['zan_num']; ?></b></button>
            </div>
            <div class="head-text">
                <p class="head-t" id="head-t"><?php echo $res['synopsis']; ?></p>
            </div>
            <div class="head-foot" style="min-height: 8rem">
                <span>播放剧集</span>
                <?php foreach($res['play_url'] as $k => $v): ?>
                <a href="/video/video/play?video_id=<?php echo $res['video_id']; ?>&num=<?php echo $k; ?>" <?php if((isset($_GET['num'])) && ($k == $_GET['num'])){echo 'style="background-color: #C34E0D;"';}elseif((!$_GET['num']) && $k == 1){echo 'style="background-color: #C34E0D;"';} ?> class="head-fir"><?php echo $k; ?></a>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
    <!-- 相关视频 -->
    <div class="correlation">
        <div class="cor-top">
        <span>
            相关视频
        </span>
        </div>
        <div class="cor-bot">
            <ul class="cor-bot-u" style="clear: both;content: '';overflow: hidden;">
                <?php foreach($tuijian as $v): ?>
                <li>
                	<a href="/video/video/play?video_id=<?php echo $v['video_id']; ?>">
	                    <div class="cor-bot-i cor-bot-l">
	                        <img src="<?php echo $v['pic_path']; ?>" alt="">
	                        <span class="cor-bot-t"><?php echo $v['name']; ?></span>
	                    </div>
                    </a>
                </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
</div>
<script>
    //必须参数
    var member_id = "<?php echo $member_id; ?>";

    //监听离开
    var domain = window.location.host;
    if(member_id && (domain != 'www.zzlhi.com')){ //只针对内网用户目的是为了关闭MEC
        var second = 0;
        var url = "/video/video/listenLeave";
        var video_id = "<?php echo $_GET['video_id']; ?>";
        $.post(url,{member_id:member_id,video_id:video_id,second:second},function(d){
            d = eval('('+ d +')');
            if(d.success){
                setInterval(function(){
                    second += 1;
                    if(second == 1*60*10){
                        $.post(url,{listen_id:d.listen_id,second:second},function(r){},'json');
                        second = 0;
                    }
                },1000);
            }
        },'text');
    }

    //立即购买
    function buyThisVideo(video_id){
        if(!member_id){
            if(confirm('提示：登录后方可购买，是否进行登录？')){
                window.location.href = 'http://www.zzlhi.com/log/action/in?refererUrl=http://<?php echo $_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI']; ?>';
            }
            return false;
        }
        var url = '/video/order/buyThisVideo';
        $.post(url,{video_id:video_id},function(d){
            d = eval('('+ d +')');
            if(d.error){
                alert(d.msg);
                window.location.reload();
            }else{
                window.location.href = d.url;
            }
        },'text');
    }

    //收藏、赞
    function Interaction(video_id,type){
        var url = '/video/video/'+type;
        $.post(url,{video_id:video_id},function(d){
            d = eval('('+ d +')');
            if(d.error){
                if(confirm(d.msg)){
                    window.location.href = 'http://www.zzlhi.com/log/action/in?refererUrl=http://<?php echo $_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI']; ?>';
                }
                return false;
            }else{
                if(type == 'zan'){
                    $('#zanButton').attr('disabled','true').css({'background-color':'#ddd','color':'#000'}).children().text(d.newZanNum);
                }else if(type == 'favorite'){
                    $('#favoritedButton').attr('disabled','true').css({'background-color':'#ddd','color':'#000'}).text('已收藏');
                }
                return false;
            }
        },'text');
    }
</script>
<!-- 防止重复js监听本页面单独使用底部 -->
<div style="font-size: 0.3rem;text-align: center;margin: 0px;background-color: #7B7B7B;width: 100%;padding: 5px;color: #fff;"><?php echo $webConfig['bottom_con']; ?></div>
</body>
</html>