<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>在这里 - 聊天</title>
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta content="yes" name="apple-mobile-web-app-capable">
    <meta content="black" name="apple-mobile-web-app-status-bar-style">
    <meta content="telephone=no" name="format-detection">
    <link rel="stylesheet" href="/Public/Chat/index/css/base.css">
    <link rel="stylesheet" href="/Public/Chat/index/css/font-awesome.min.css">
    <link rel="stylesheet" href="/Public/Chat/index/css/chat.css">
    <link rel="stylesheet" href="/Public/Chat/index/css/emoji.css">
    <script src="/Public/Chat/index/js/main.js"></script>
    <script src="/Public/Chat/index/js/autosize.min.js"></script>
    <script src="/Public/Chat/index/js/zepto.min.js"></script>
    <script src="/Public/Chat/index/js/ZeptoEmoji.js"></script>
    <script src="/Public/Chat/index/js/Emoji.contrast.js"></script>
    <script src="/Public/Chat/index/js/jquery-3.2.0.min.js"></script>
    <script src="/Public/Chat/index/js/loadmore.js"></script>
</head>