<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<style>
.wy-header-title {
    margin: 0 50px;
    text-align: center;
    height: 44px;
    line-height: 44px;
    font-size: 16px;
    color: #fff;
    font-weight: 700;
}
</style>
<body ontouchstart>
<!--顶部搜索-->
<header class='weui-header fixed-top' style="background: #e21323;">
  <div class="wy-header-title"></div>
  <div class="pro-sort">
    <div class="weui-flex">
      <div class="weui-flex__item">
      <div class="placeholder  SortAscCss" style="color: #e21323;">
          <select class="weui-select" id='chouse_type' name="type" style="background: transparent;  color: #e21323;height: 40px;line-height: 40px;position: relative;font-size: 14px;">
            <option disabled="">自营区</option>
            <option <?php echo empty($_GET['type'])?'selected="selected"':''; ?> value = "">全部自营</option>
            <option <?php echo $_GET['type']=='1_2000'?'selected="selected"':''; ?> value = "1_2000">1~2000</option>
            <option <?php echo $_GET['type']=='2001_5000'?'selected="selected"':''; ?> value = "2001_5000">2001~5000</option>
            <option <?php echo $_GET['type']=='5000up'?'selected="selected"':''; ?> value = "5000up">5000以上</option>
            <option disabled="">代理区</option>
            <option <?php echo $_GET['type']=='myagent'?'selected="selected"':''; ?> value = "myagent">全部代理</option>
          </select>
          </div>
      </div>
      <div class="weui-flex__item"><div class="placeholder sales SortAscCss" style="color: #e21323;">按销量</div></div>
      <div class="weui-flex__item"><div class="placeholder prices " style="color: #e21323;">按价格</i></div></div>
    </div>
  </div>
</header>
<!--主体-->
<div class="weui-content" style="padding-top:85px;">
  <div id="list" class='demos-content-padded proListWrap'>
    <?php foreach($goods as $v): ?>
    <div class="pro-items">
      <a href="/Exchange/Goods/detail?goods_id=<?php echo $v['goods_id']; ?>" class="weui-media-box weui-media-box_appmsg">
        <div class="weui-media-box__hd"><img class="weui-media-box__thumb" src="<?php echo explode(';',$v['pics'])[0]; ?>" alt=""></div>
        <div class="weui-media-box__bd">
          <h1 class="weui-media-box__desc"><?php echo $v['goods_name']; ?></h1>
          <div class="wy-pro-pri"><em class="num font-15"><?php echo $v['piao']; ?></em>共享币</div>
          <ul class="weui-media-box__info prolist-ul">
            <li class="weui-media-box__info__meta">销量<em class="num"><?php echo $v['sales_volume']; ?></em></li>
            <!-- <li class="weui-media-box__info__meta"><em class="num">0</em>条评价</li> -->
          </ul>
        </div>
      </a>
    </div>
    <?php endforeach; ?>
  </div>
  <?php if (count($goods) < 10): ?>
  <div class="weui-loadmore weui-loadmore_line">
    <span class="weui-loadmore__tips">没有更多了</span>
  </div>
  <?php else: ?>
  <div class="weui-loadmore">
    <i class="weui-loading"></i>
    <span class="weui-loadmore__tips">正在加载...</span>
  </div>
  <?php endif ?>
  
 
  
</div>
<div class="foot-black"></div>
<div class="weui-tabbar wy-foot-menu">
  <a href="/Exchange" class="weui-tabbar__item ">
    <div class="weui-tabbar__icon foot-menu-home"></div>
    <p class="weui-tabbar__label">首页</p>
  </a>
  <a href="/Exchange/Goods/lists" class="weui-tabbar__item weui-bar__item--on">
    <div class="weui-tabbar__icon foot-menu-list"></div>
    <p class="weui-tabbar__label">商品</p>
  </a>
  <a href="/Exchange/Member/index" class="weui-tabbar__item">
    <div class="weui-tabbar__icon foot-menu-member"></div>
    <p class="weui-tabbar__label">我的</p>
  </a>
</div>
</body>
<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>
<script>
  $(function() {
    FastClick.attach(document.body);
  });
</script> 
<script>
    window.onload=function(){
      var title = $('#chouse_type option:selected').text()+'的商品';
      $('.wy-header-title').html(title);
    }
      //设置默认
      if($('.prices').hasClass('SortDescCss')){
        $('.prices').removeClass('SortDescCss')
      }else if($('.prices').hasClass('SortAscCss')){
        $('.prices').removeClass('SortAscCss');
      }
      if($('.sales').hasClass('SortDescCss')){
        $('.sales').removeClass('SortDescCss')
      }else if($('.sales').hasClass('SortAscCss')){
        $('.sales').removeClass('SortAscCss');
      }
      var order = <?php echo $_GET['order']?'"'.$_GET['order'].'"':'"sa"'; ?>;
      if (order=='sa') {
        $('.sales').addClass('SortAscCss');
      }else if(order=='sd'){
        $('.sales').addClass('SortDescCss');
      }else if(order=='pa'){
        $('.prices').addClass('SortAscCss');
      }else if(order=='pd'){
        $('.prices').addClass('SortDescCss');
      }else{
        $('.sales').addClass('SortAscCss');
      }

     $('.sales').click(function() {
      if($('.prices').hasClass('SortDescCss')){
        $('.prices').removeClass('SortDescCss')
      }else if($('.prices').hasClass('SortAscCss')){
        $('.prices').removeClass('SortAscCss');
      }
      if($(this).hasClass('SortDescCss')){
        $(this).removeClass('SortDescCss')
        $(this).addClass('SortAscCss');
        window.location.href="/Exchange/Goods/lists?type="+"<?php echo $_GET['type']; ?>"+"&order=sa";
      }else if($(this).hasClass('SortAscCss')){
        $(this).removeClass('SortAscCss')
        $(this).addClass('SortDescCss');
        window.location.href="/Exchange/Goods/lists?type="+"<?php echo $_GET['type']; ?>"+"&order=sd";
      }else{
       $(this).addClass('SortAscCss');
        window.location.href="/Exchange/Goods/lists?type="+"<?php echo $_GET['type']; ?>"+"&order=sa";
     }
     
     })
      $('.prices').click(function() {
        if($('.sales').hasClass('SortDescCss')){
          $('.sales').removeClass('SortDescCss')
        }else if($('.sales').hasClass('SortAscCss')){
          $('.sales').removeClass('SortAscCss');
        }
       if($(this).hasClass('SortDescCss')){
        $(this).removeClass('SortDescCss')
        $(this).addClass('SortAscCss');
        window.location.href="/Exchange/Goods/lists?type="+"<?php echo $_GET['type']; ?>"+"&order=pa";
      }else if($(this).hasClass('SortAscCss')){
        $(this).removeClass('SortAscCss')
        $(this).addClass('SortDescCss');
        window.location.href="/Exchange/Goods/lists?type="+"<?php echo $_GET['type']; ?>"+"&order=pd";
      }else{
       $(this).addClass('SortAscCss');
        window.location.href="/Exchange/Goods/lists?type="+"<?php echo $_GET['type']; ?>"+"&order=pa";
     }
    
     })
    $('#chouse_type').change(function(){
      window.location.href="/Exchange/Goods/lists?type="+$('#chouse_type option:selected').val();
    });
      
      // infinite
      var page = 2;
      var loading = false;
      $(document.body).infinite().on("infinite", function() {
        if(loading) return;
        loading = true;
        var get_url = window.location.pathname+window.location.search;
        $.ajax({
            cache: true,
            type: "GET",
            url:get_url,
            data:{'page':page},// 你的formid
            dataType: 'json',
            async: false,
            error: function(data) {
              setTimeout(function(){
                $('.weui-loadmore').addClass('weui-loadmore_line');
                $('.weui-loadmore').html('<span class="weui-loadmore__tips">网络错误</span>')
                loading = false;
              },3000);

            },
            success: function(data) {      
              if (data.error == 0) {
                var goods = data.data;
                for (var i = 0; i < goods.length; i++) {
                  var only_goods = goods[i];
                  $("#list").append('<div class="pro-items"><a href="/Exchange/Goods/detail?goods_id='+only_goods["goods_id"]+'" class="weui-media-box weui-media-box_appmsg"><div class="weui-media-box__hd"><img class="weui-media-box__thumb" src="'+only_goods['pics'].split(";",1)+'" alt=""></div><div class="weui-media-box__bd"><h1 class="weui-media-box__desc">'+only_goods['goods_name']+'</h1><div class="wy-pro-pri">¥<em class="num font-15">'+only_goods['piao']+'</em>共享币</div><ul class="weui-media-box__info prolist-ul"><li class="weui-media-box__info__meta">销量<em class="num">'+only_goods['sales_volume']+'</em></li></ul></div></a></div>');
                }
                page++;
                loading = false;
              }else{
                setTimeout(function(){
                  $('.weui-loadmore').addClass('weui-loadmore_line');
                  $('.weui-loadmore').html('<i class=""></i> <span class="weui-loadmore__tips">'+data.msg+'</span>');
                  loading = false;
                },1000);
              }
            }
        });
          
        
      });
</script>