<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<style>
.wy-header {
    height: 44px;
    border-bottom: 0px;
    position: fixed;
    left: 0;
    top: 0;
    width: 100%;
    background: #e21323;
    z-index: 100;
}
.wy-header-title {
    margin: 0 50px;
    text-align: center;
    height: 44px;
    line-height: 44px;
    font-size: 16px;
    color: #fff;
    overflow: hidden;
}
  .div_c{
    background-color:#fff;
    height: 80px;
    padding: 23px 35px;
    box-sizing: border-box;
    width:100%;
    text-align: center;
    position:absolute;
    top: 30%;
  }
  .f_div{
    height: 30%;
    width: 80%;
    margin:0 auto;
    background: #fff;
    z-index: 99;
    margin-top: 25%;
    border-radius: 8px;
    position:relative;
  }
  .coverPass{
    display: none;
    position: fixed;
    width:100%;
    height:100%;
    background-color: rgba(125,125,125,0.8);
    z-index: 50;
  }
  #pass{
    height: 1px;
    width: 1px;
  }
  .c_li{
    position: relative;
    float:left;
    width: 15.5%;
    height: 35px;
    line-height: 35px;
    border-left: 1px dashed #111;
    border-bottom:1px solid #111;
    border-top:1px solid #111;
   }
  .first{
    border-left:1px solid #111;
    border-radius: 5px 0 0 5px;
  }
  .last{
     border-right:1px solid #111;
     border-radius: 0 5px 5px 0;
  }
  li {
    list-style:none;
  }
  .passTitle{
    height: 60px;
    line-height: 60px;
    text-align: center;
    font-size: 20px;
  }
  .cancel,.sure{
    height: 32px;
    width: 32px;
    width: 30%;
    text-align: center;
    font-size: 20px;
    background: none;
    outline: none;
    color: #fff;
    border-radius: 5px;
  }
  .cancel{
    float: left;
    background-color: #b1b1b1;
  }
  .sure{
    float: right;
    background-color: #e21323;
  }
  .passBut{
    height: 40px;
    width: 70%;
    position: absolute;
    bottom: 10px;
    left: 13%;
  }
  .pointD{
    height: 8px;
    width: 8px;
    position: absolute;
    top: 50%;
    left: 50%;
    background: #111;
   border-radius: 50%;
   margin-left: -4px;
   margin-top: -4px; 
  }
</style>
<body ontouchstart>
<!--主体-->
<div class="coverPass">
  <div class="f_div">
    <form>
      <p class="passTitle">支付密码</p>
      <input id="pass"  type="password" autocomplete="off" name="pass" value="" maxlength="6" onkeypress="return event.keyCode>=48&&event.keyCode<=57" ng-pattern="/[^a-zA-Z]/">
      <div class="div_c">
        <li class="c_li first point">
          <div class=""></div>
        </li>
        <li class="c_li point">
          <div class=""></div>
        </li>
        <li class="c_li point">
          <div class=""></div>
        </li>
        <li class="c_li point">
          <div class=""></div>
        </li>
        <li class="c_li point">
          <div class=""></div>
        </li>
        <li class="c_li last point">
          <div class=""></div>
        </li>
      </div>
      <div class="passBut">
        <p class="cancel">取消</p>
        <p class="sure" >确定</p>
      </div>
    </form>
  </div>
</div>
<header class="wy-header">
  <a href="javascript:history.back(-1);" title="返回上一页" style="width: 50px;position: absolute;left: 0;top: 0;z-index: 10; height: 45px;"><div class="wy-header-icon-back"><span></span></div></a>
  <div class="wy-header-title"  style="color: #fff">确认订单</div>
</header>
<div class="weui-content" style="margin-top: 44px;">
  <div class="wy-media-box weui-media-box_text address-select">
    <div class="weui-media-box_appmsg">
      <div class="weui-media-box__hd proinfo-txt-l" style="width:20px;"><span class="promotion-label-tit"><img src="/Public/mobile/images/icon_nav_city.png" /></span></div>
      <div class="weui-media-box__bd">
        <a href="/Exchange/Member/address_edit" class="weui-cell_access">
            <?php if($user['province_id'] && $user['city_id'] && $user['area_id']): ?>
            <h4 class="address-name"><span><?php echo $user['name']; ?></span><span><?php echo $user['phone_num']; ?></span></h4>
            <div class="address-txt" id="address"><?php echo $user['province_name'].' '.$user['city_name'].' '.$user['area_name'].' '.$user['address']; ?></div>
            <?php else: ?>
            <div class="address-txt">请补全收货地址</div>
            <?php endif ;?>
        </a>
      </div>
      <div class="weui-media-box__hd proinfo-txt-l" style="width:16px;"><div class="weui-cell_access"><span class="weui-cell__ft"></span></div></div>
    </div>
  </div>
  <div class="wy-media-box weui-media-box_text">
    <div class="weui-media-box__bd">
     <div class="weui-media-box_appmsg ord-pro-list">
        <div class="weui-media-box__hd"><a href="/Exchange/Goods/detail?goods_id=<?php echo $goods['goods_id']; ?>"><img class="weui-media-box__thumb" src="<?php echo explode(';',$goods['pics'])[0]; ?>" alt=""></a></div>
        <div class="weui-media-box__bd">
          <h1 class="weui-media-box__desc"><a href="/Exchange/Goods/detail?goods_id=<?php echo $goods['goods_id']; ?>" class="ord-pro-link"><?php echo $goods['goods_name']; ?></a></h1>
          <!-- <p class="weui-media-box__desc">规格：<span>红色</span>，<span>23</span></p> -->
          <div class="clear mg-t-10">
            <div class="wy-pro-pri fl"><em class="num font-15"><?php echo $goods['piao']; ?></em>共享币</div>
            <div class="pro-amount fr"><span class="font-13">数量：<em class="name">1</em></span></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="weui-panel">
    <div class="weui-panel__bd">
      <div class="weui-media-box weui-media-box_small-appmsg">
        <div class="weui-cells">
            <div class="weui-cell weui-cell_access">
                <div class="weui-cell__bd weui-cell_primary">
                  <p class="font-14">
                    <span class="fl mg-r-10">配送方式</span>
                    <span class="fl" style="width: 75%">
                        <select name="is_ziti" id="is_ziti" style="padding:1px 0px 1px 75%; width: 100% ;text-align:right;  appearance:none;-moz-appearance:none; -webkit-appearance:none;  ">
                          <option value="1" style="text-align: right;">自提</option>
                          <option value="2"  style="text-align:right;">快递</option>
                        </select>
                        <span style=" position: absolute;right: 20px;top: 10px;">
                          ▼
                        </span>
                    </span>
                  </p>
                </div>
            </div>
            <div class="weui-cell weui-cell_access" href="javascript:;">
                <div class="weui-cell__bd weui-cell_primary">
                  <p class="font-14"><span class="mg-r-10">商家地址</span></p>
                  <p class="font-14"><span class="fr txt-color-red" style="float: left;font-size: 10px;margin: 5px 0px;line-height: 25px;"><?php echo $business['province_name'].' '.$business['city_name'].' '.$business['area_name'].'<br/>'.$business['business_address']; ?></span></p>
                </div>
            </div>
            <div class="weui-cell weui-cell_access" href="javascript:;">
                <div class="weui-cell__bd weui-cell_primary">
                    <p class="font-14"><span class="mg-r-10">所需运费</span><span class="fr txt-color-red">包邮</span></p>
                </div>
            </div>
            <a class="weui-cell weui-cell_access" >
                <div class="weui-cell__bd weui-cell_primary">
                    <p class="font-14"><span class="mg-r-10">我的共享币</span><span class="sitem-tip"><em class="num"><?php echo $user['piao']; ?></em>个</span></p>
                </div>
            </a>
            <a class="weui-cell weui-cell_access">
                <div class="weui-cell__bd weui-cell_primary">
                    <p class="font-14"><span class="mg-r-10">备注：</span>
                        <input type="text" name="message" id="message" placeholder="填写型号和颜色" style="display: inline-block;width: 75%;height: 100%; padding: 9px 10px;">
                    </p>
                </div>
            </a>
        </div>
      </div>
    </div>
  </div>
  <div class="wy-media-box weui-media-box_text">
    <div class="mg10-0 t-c">共需支付共享币：<span class="wy-pro-pri mg-tb-5"><em class="num font-20"><?php echo $goods['piao']; ?></em>个</span></div>
    <div class="mg10-0"><span href="" class="weui-btn weui-btn_warn ords-btn-buy ">确认兑换</span></div>
  </div>
</div>
</body>
<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>
<script>
    $(function() {
        FastClick.attach(document.body);
    });
</script>
<script type="text/javascript">
    $(function(){
      $(".Spinner").Spinner({value:1, len:3, max:999});
    });

    $(document).on("click", ".ords-btn-buy", function() {
        $(".coverPass").fadeIn();
        $('.coverPass').click(function(){
          document.getElementById('pass').focus();
        });
        if ($("#pass")) {
          $("#pass").focus();
        }
        $('#pass').bind('input propertychange', function() {
          var num = $('#pass').val().length;
          $(".point").find("div").removeClass("pointD")
          for (var i = 0; i < num; i++) {
            $(".div_c").find("li").eq(i).find("div").addClass("pointD");
          }
        });
        $(".cancel").on("click",function(){
          $(".point").find("div").removeClass("pointD")
          $(".coverPass").fadeOut();
          $("#pass").val("");
        });
        $(".sure").on("click",function(){
          var passWordCon = $("#pass").val();
          if (passWordCon.length != 6) {
            $("#pass").focus();
            return false;
          }
          $(".point").find("div").removeClass("pointD")
          $(".coverPass").fadeOut();
          $("#pass").val("");
          var myPiao = <?php echo $user['piao']; ?>;
          var payPiao = <?php echo $goods['piao']; ?>;
          if(myPiao < payPiao){
              $.toast("您的共享币不足",'cancel');
              return false;
          }else{
              $.post('/Exchange/Goods/order',{'passWordCon':passWordCon,address:$('#address').text(),is_ziti:$('#is_ziti').val(),message:$('#message').val(),goods_id:<?php echo $goods['goods_id']; ?>},function(d){
                  if(d.error){
                      $.toast(d.msg,'cancel');
                      return false;
                  }else{
                      $.toast(d.msg);
                      setTimeout("window.location.href = '/Exchange/Member/myorders'",1000);
                  }
              },'json');
          }
        })
    });
</script>