<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<style type="text/css">
    ul li{
        border-top: 0.125rem solid #F4F4F4;
    }
    .nav-foot{
        background-color: #ffffff;
        position: relative;
    }
    .per-cen li{
        width: 2.465rem;
    }
    .per-container{
        min-height: 16rem;
    }
</style>
<body>
<div class="per-container">
    <div class="person-bg" style="margin-bottom: 2rem;">
        <a href="/index.php/index/index/memberInfo?member_id=<?php echo $member['member_id']; ?>" class="fa fa-angle-left"></a>
        <div class="headimg">
            <img src="<?php echo $member['base64_con']; ?>" alt="">
        </div>
    </div>
    <div class="per-cen">
        <ul>
            <li class="">
        <a href="/index.php/index/user/editInfo" class="per-cen-a">
        <img src="/Public/Index/index/images/ziliao.png" alt="" class="per-sen-t">
        <span class="per-sen-t">修改资料</span>
        </a>
    </li>
    <li>
        <a href="/index.php/index/user/rePassword">
        <img src="/Public/Index/index/images/mima.png" alt="" class="per-sen-t">
        <span class="per-sen-t">修改密码</span>
        </a>
    </li>
    <li>
        <a href="javascript:;" style="opacity: 0.3;">
        <img src="/Public/Index/index/images/jifen.png" alt="" class="per-sen-t">
        <span class="per-sen-t">我的积分</span>
        </a>
    </li>
    <li>
        <a href="javascript:;" style="opacity: 0.3;">
        <img src="/Public/Index/index/images/zhaohuan.png" alt="" class="per-sen-t">
        <span class="per-sen-t">召唤小编</span>
        </a>
    </li>
    </ul>
    <div class="per-cut-off"></div>
    </div>
</div>
</body>
<div class="nav-foot">
    <div class="line-left f_l"></div>
    <div class="moddle-logo">
        <img src="/Public/Index/index/images/bot.png" alt="">
        <p class="big f_l">在这里</p>
        <p class="small f_l">zzlhi.com</p>
        <br>
    </div>
    <div class="line-right f_r"></div>
</div>
</body>
</html>