<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<link href="/Public/Video/index/css/mui.css" rel="stylesheet"/>
<link href="/Public/Video/index/css/main.css" rel="stylesheet" type="text/css"/>
<style type="text/css">
    .mona-ipb input{
        font-size: 0.4rem;
    }
    .regist-all .re-it .re-t a{
        height: 1.45rem;
    }
    body{
        background-color: #FFFFFF;
    }
</style>
<body>
<div class="per-container">
    <div class="person-bg" style="margin-bottom: 2rem;">
        <a href="/index.php/index/user/index" class="fa fa-angle-left"></a>
        <div class="headimg">
            <img src="<?php echo $member['base64_con']; ?>" alt="">
        </div>
    </div>
    <div class="regist-all">
        <div class="mi-re-body">
        <form>
            <input type="password" class="re-in-tel" name="password" id="password" placeholder="新密码">
            <div class="re-ipb">
                <input type="password" class="re-in-pas" id="repassword" placeholder="重复新密码">
            </div>
        </form>
        </div>
        <div class="re-ck-but mi-ck-but" style="margin-top: 2rem;">
            <input type="button" onclick="javascript:rePassword();" class="re-in-but" style="background-color: #2196F3" value="提交修改">
        </div>
    </div>
</div>
<script>
    function rePassword(){
        if($('#password').val() != $('#repassword').val()){
            alert('两次密码不相同');
            return false;
        }
        $.post('/index.php/index/user/rePassword',{data:$('form').serialize()},function(d){
            d = eval('('+ d +')');
            if(d.error){
                alert(d.msg);
                return false;
            }else{
                alert(d.msg);
                window.location.href = "/index.php/index/user/index";
            }
        },'text');
    }
</script>