
<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<body class="gray-bg">
    <div class="wrapper wrapper-content animated fadeInRight">

        <div class="row">
         
            <div class="col-sm-12">
                <div class="ibox float-e-margins business-info">
                    <div class="ibox-title">
                        <h5>商户资料</h5>
                        <span class="label label-primary pull-right label-primary-cust">
                            <?php if($_GET['back'] == 'true'): ?>
                            <a href="javascript:history.back(-1);" class="fa-lg-cust-a" title="返回上一页">
                                <i class="fa fa-arrow-left fa-lg-cust"  aria-hidden="true"></i>
                            </a>
                            <?php endif; ?>
                        </span>
                    </div>
                    <div class="ibox-content">
                        <?php echo $res['alert']; ?>
                        <form class="form-horizontal m-t" id="signupForm">
                         <div class="form-group">
                                <label class="col-sm-3 control-label">商户号：</label>
                                <div class="col-sm-8">
                                    <input id="firstname" name="firstname" class="form-control" type="text" disabled="disabled" value="<?php echo $info['business_id'] ?>">
                                    <?php echo $res['tishi']; ?>
                                </div>
                            </div>
                             <div class="form-group">
                                <label class="col-sm-3 control-label">法人姓名：</label>
                                <div class="col-sm-8">
                                    <input id="username" name="username" class="form-control" type="text"  <?php echo $res['lock']; ?> value="<?php echo $info['legal_name'] ?>">
                                    <?php echo $res['tishi']; ?>

                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">法人身份证号：</label>
                                <div class="col-sm-8">
                                    <input id="cardId" name="cardId" class="form-control" type="text" <?php echo $res['lock']; ?> value="<?php echo $info['card_num'] ?>">
                                    <?php echo $res['tishi']; ?>
                                    
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">手机号：</label>
                                <div class="col-sm-8">
                                    <input id="phone" name="phone" class="form-control" type="text" <?php echo $res['lock']; ?> value="<?php echo $info['phone_num'] ?>">
                                     <?php echo $res['tishi']; ?>
                                    
                                </div>
                            </div>
                             
                            <div class="form-group">
                                <label class="col-sm-3 control-label">公司名称：</label>
                                <div class="col-sm-8">
                                    <input id="" name="company_name" class="form-control" type="text" <?php echo $res['lock']; ?> value="<?php echo $info['company_name'] ?>">
                                    <?php echo $res['tishi']; ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">行业类型：</label>
                                <div class="col-sm-8">
                                    <select <?php echo $res['lock']; ?> class="input-sm form-control input-s-sm inline" name="profession_id" style="height: 33px;">
                                        <option value="0">行业类别</option>
                                        <?php foreach ($professions as $key => $value): ?>
                                        <?php $pro_dis = ($value['profession_id']==$info['profession_id'])?'selected="selected"':''; ?>
                                        <option value="<?php echo $value['profession_id'] ?>" <?php echo $pro_dis; ?> ><?php echo $value['profession_name'] ?></option>
                                        <?php endforeach ?>
                                    </select>
                                    
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">积分商城名称：</label>
                                <div class="col-sm-8">
                                    <input id="" name="" class="form-control" type="text" disabled title="请在左上角头像下拉处修改商城名称" value="<?php echo $info['exchange_name'] ?>">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">公司所在地：</label>
                                <div class="col-sm-8">
                                   <select <?php echo $res['lock']; ?> class="input-sm form-control input-s-sm inline" name="province_id" style="width: 97px;height: 33px;">
                                        <option value="0">省份</option>
                                        <?php foreach ($provinces as $key => $value): ?>
                                        <?php $prov_dis = ($value['province_id']==$info['province_id'])?'selected="selected"':''; ?>
                                        <option value="<?php echo $value['province_id'] ?>" <?php echo $prov_dis; ?> ><?php echo $value['province_name'] ?></option>
                                        <?php endforeach ?>
                                    </select>

                                    <select <?php echo $res['lock']; ?> class="input-sm form-control input-s-sm inline" name="city_id" style="width: 97px;height: 33px;">
                                        <option value="0">城市</option>
                                        <?php foreach ($citys as $key => $value): ?>
                                        <?php $city_dis = ($value['city_id']==$info['city_id'])?'selected="selected"':''; ?>
                                        <option value="<?php echo $value['city_id'] ?>" <?php echo $city_dis; ?> ><?php echo $value['city_name'] ?></option>
                                        <?php endforeach ?>
                                    </select>

                                    <select <?php echo $res['lock']; ?> class="input-sm form-control input-s-sm inline" name="area_id" style="width: 97px;height: 33px;">
                                        <option value="0">区(县)</option>
                                        <?php foreach ($areas as $key => $value): ?>
                                        <?php $area_dis = ($value['area_id']==$info['area_id'])?'selected="selected"':''; ?>
                                        <option value="<?php echo $value['area_id'] ?>" <?php echo $area_dis; ?> ><?php echo $value['area_name'] ?></option>
                                        <?php endforeach ?>
                                    </select>
                                                    
                                </div>
                            </div>
                             <div class="form-group">
                                <label class="col-sm-3 control-label">街道地址：</label>
                                <div class="col-sm-8">
                                    <input id="" <?php echo $res['lock']; ?> name="business_address" class="form-control" type="text" value="<?php echo $info['business_address'] ?>">
                                    
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">注册时间：</label>
                                <div class="col-sm-8">
                                    <input id="" name="" class="form-control" type="text" <?php echo $res['lock']; ?> value="<?php echo $info['add_time'] ?>">
                                     <?php echo $res['tishi']; ?>
                                </div>
                            </div>
                            <div class="form-group form-group-bottom">

                                <div class="col-sm-2 col-sm-offset-3" style='float: left;'>
                                    <?php echo $res['button']; ?>
                                </div>
                                <div class="col-sm-2  " style='float: left;'>
                                    <p onClick="window.location.reload();" class="btn btn-default">刷新</p>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>
    <script type="text/javascript">
        //获取城市
        $('select[name=province_id]').change(function(){
            $.ajax({
                cache: true,
                type: "POST",
                url:"/Business/Log/get_citys",
                data:{province_id:$('select[name=province_id]').val()},
                dataType: 'json',
                async: false,
                error: function(data) {
                swal('网络错误，请重试！', "", "warning");
                },
                success: function(data) {      
                    $('select[name=city_id]').html('');
                    data = data.data;
                    $('select[name=city_id]').append('<option value="0">城市</option>');
                    $('select[name=area_id]').html('');
                    $('select[name=area_id]').append('<option value="0">区(县)</option>');
                    for (var i = 0; i < data.length; i++) {
                        $('select[name=city_id]').append('<option value="'+data[i].city_id+'">'+data[i].city_name+'</option>');
                    }
                }
            });
        });

        //获取区(县)
        $('select[name=city_id]').change(function(){
            $.ajax({
                cache: true,
                type: "POST",
                url:"/Business/Log/get_areas",
                data:{city_id:$('select[name=city_id]').val()},
                dataType: 'json',
                async: false,
                error: function(data) {
                 swal('网络错误，请重试！', "", "warning");
                },
                success: function(data) {      
                    $('select[name=area_id]').html('');
                    data = data.data;
                    $('select[name=area_id]').append('<option value="0">区(县)</option>');
                    for (var i = 0; i < data.length; i++) {
                        $('select[name=area_id]').append('<option value="'+data[i].area_id+'">'+data[i].area_name+'</option>');
                    }
                }
            });
        });

        $('#signupForm_submit').click(function(){
    swal({
                title: "确定要提交审核吗？",
                text: "我们审核通过后您的资料将不可再更改，请务必填写真实情况",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "是的，我要提交",
                cancelButtonText: "让我再考虑一下",
                closeOnConfirm: false,
                closeOnCancel: true
            },
            function(isConfirm) {
                if (isConfirm) { 
                   $.ajax({
                            cache: true,
                            type: "POST",
                            url:"/Business/Center/info",
                            data:$('#signupForm').serialize(),// 你的formid
                            dataType: 'json',
                            async: false,
                             error: function(data) {
                                    swal('网络错误，请重试！', "", "warning");
                             },
                            success: function(data) {      
                                if (data.error == 0) {
                                    swal("提交成功", "", "success");
                                    setTimeout("window.location.reload();",1000);
                                }else{
                                    swal(data.msg, "", "error");
                                }
                            }
                    });
                }
            })
         

        });
    </script>
</body>

