<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<style>
   
    .table-responsive .cap-center th,.table-responsive table tbody td{
        text-align: center !important;
    }
    
</style>
<body class="gray-bg">
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-sm-12">
                <div class="ibox">
                    <div class="ibox-title">
                        <h5>推荐奖励</h5>
                        <span class="label label-warning notices_num" style="float:right;height: 25px;line-height: 20px;">您现在已经累计获得共享币：<?php echo $sumRewardPiao?$sumRewardPiao:0; ?> 个</span>
                    </div>
                    <div class="ibox-content">
                        <div class="alert alert-warning">
                            <span class="alert-link">奖励规则：</span><br/><br/>新商户注册时推荐人栏填写您的商户ID ：<abbr class="alert-link" data-container="body" data-toggle="popover" data-placement="bottom" data-content="您的商户ID"><?php echo $business_id; ?></abbr>，当对方激活账户后，您就会得到 <span class="alert-link"><?php echo $reward_piao; ?></span> 个共享币的奖励！
                        </div>
                        <div class="tab-content">
                            <div id="tab-1" class="tab-pane active">
                                <div class="full-height-scroll">
                                    <div class="table-responsive">
                                        <table class="table table-striped table-hover">
                                            <tbody>
                                                <tr class="cap-center">
                                                    <th>序号</th>
                                                    <th>商户ID</th>
                                                    <th>激活状态</th>
                                                    <th>商户姓名</th>
                                                    <th>电话</th>
                                                    <th>公司名称</th>
                                                    <th>奖励共享币</th>
                                                    <th>注册时间</th>
                                                    <th>激活时间</th>
                                                </tr>
                                                <?php foreach($result as $k => $v): ?>
                                                <tr>
                                                    <td><?php echo $k + 1; ?></td>
                                                    <td><?php echo $v['business_id']; ?></td>
                                                    <td><?php echo $v['status'] == 1 ? '已激活' : '未激活'; ?></td>
                                                    <td><?php echo $v['legal_name']; ?></td>
                                                    <td><?php echo $v['phone_num']; ?></td>
                                                    <td><?php echo $v['company_name']; ?></td>
                                                    <td >
                                                        <span>+<?php echo $v['reward_piao']; ?></span>
                                                    </td>
                                                    <td><?php echo $v['add_time']; ?></td>
                                                    <td><?php echo $v['activate_time']; ?></td>
                                                </tr>
                                                <?php endforeach; ?>
                                            </tbody>
                                            <tfoot>
                                                <tr>
                                                    <td colspan="12">
                                                        <div class="b-page">
                                                            <?php echo $page['page']; ?>
                                                        </div>
                                                    </td>
                                                </tr>
                                            </tfoot>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>
