<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<body>
<div class="container">
    <div class="chatheader clearfix">
        <a href="<?php echo $_SERVER['HTTP_REFERER']; ?>" class="fa fa-angle-left"></a><span><?php echo $theListRes['title']; ?></span> <a href="#" class="server "><img
            src="/Public/Chat/index/images/server.png" alt=""></a>
    </div>
    <div class="chat-content">
        <div class="chatbigbox">
            <?php $so = $member_id == $theListRes['member_id'] ? 'self' : 'other'; ?>
            <div class="<?php echo $so; ?>box clearfix">
                <div class="<?php echo $so; ?>">
                    <a href="/index.php/index/index/memberInfo?member_id=<?php echo $theListRes['member_id']; ?>"><img src="<?php echo $theListRes['base64_con']; ?>" alt=""></a>
                    <div class="<?php echo $so; ?>chatbox">
                        <p class='chatname'><?php echo $theListRes['nick_name']; ?></p>
                        <div class="chat-details">
                            <p>
                                <?php echo $theListRes['content']; ?>
                            </p>

                            <div class="bugle"></div>
                        </div>
                        <div class="chattime">
                            <span><?php echo $theListRes['start_time']; ?></span>
                        </div>
                    </div>
                </div>
            </div>
            <?php foreach($detailRes as $v): ?>
            <?php $so = $member_id == $v['member_id'] ? 'self' : 'other'; ?>
            <div class="<?php echo $so; ?>box clearfix">
                <div class="<?php echo $so; ?>">
                    <a href="/index.php/index/index/memberInfo?member_id=<?php echo $v['member_id']; ?>"><img src="<?php echo $v['base64_con']; ?>" alt=""></a>
                    <div class="<?php echo $so; ?>chatbox">
                        <p class='chatname'><?php echo $v['nick_name']; ?></p>
                        <div class="chat-details">
                            <p>
                                <?php echo $v['content']; ?>
                            </p>
                            <div class="bugle"></div>
                        </div>
                        <div class="chattime">
                            <span><?php echo $v['send_time']; ?></span>
                        </div>
                    </div>
                </div>
            </div>
            <?php endforeach; ?>
        </div>
        <div class="task-status">
            <img src="/Public/Chat/index/images/<?php echo $theListRes['status'] == 1 ? 'ok' : 'off'; ?>.png" alt="">
        </div>
    </div>
</div>
</body>
<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>
