<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<style>
.wy-header {
    height: 44px;
    border-bottom: 0px;
    position: fixed;
    left: 0;
    top: 0;
    width: 100%;
    background: #e21323;
    z-index: 100;
}
.wy-header-title {
    margin: 0 50px;
    text-align: center;
    height: 44px;
    line-height: 44px;
    font-size: 16px;
    color: #fff;
    overflow: hidden;
}
.weui-btn+.weui-btn {
    margin-top: 0px;
}
</style>
<body ontouchstart>
<!--主体-->
<header class="wy-header">
  <a href="javascript:history.back(-1);" title="返回上一页" style="width: 50px;position: absolute;left: 0;top: 0;z-index: 10; height: 45px;"><div class="wy-header-icon-back"><span></span></div></a>
  <div class="wy-header-title"  style="">订单详情</div>
</header>
<div class="weui-content" style="margin-top: 44px;">
  <div class="wy-media-box weui-media-box_text address-select">
    <div class="weui-media-box_appmsg">
      <div class="weui-media-box__hd proinfo-txt-l" style="width:20px;"><span class="promotion-label-tit"><img src="/Public/mobile/images/icon_nav_city.png" /></span></div>
      <div class="weui-media-box__bd">
        <a href="javascript:;" class="weui-cell_access">
          <h4 class="address-name"><span><?php echo $_SESSION['exchange']['member_name']; ?></span><span><?php echo $_SESSION['exchange']['phone_num']; ?></span></h4>
          <div class="address-txt"><?php echo $order_info['address']; ?></div>
        </a>
      </div>
      <div class="weui-media-box__hd proinfo-txt-l" style="width:16px;"><div class="weui-cell_access"></div></div>
    </div>
  </div>
  <div class="wy-media-box weui-media-box_text">
    <div class="weui-media-box__bd">
     <div class="weui-media-box_appmsg ord-pro-list">
        <div class="weui-media-box__hd"><a href="/Exchange/Goods/detail?goods_id=<?php echo $order_info['goods_id']; ?>"><img class="weui-media-box__thumb" src="<?php echo $order_info['pic']; ?>" alt=""></a></div>
        <div class="weui-media-box__bd">
          <h1 class="weui-media-box__desc"><a href="/Exchange/Goods/detail?goods_id=<?php echo $order_info['goods_id']; ?>" class="ord-pro-link"><?php echo $order_info['goods_name']; ?></a></h1>
          <p class="weui-media-box__desc">备注：<?php echo $order_info['message'] ?></p>
          <div class="clear mg-t-10">
            <div class="wy-pro-pri fl"><em class="num font-15"><?php echo $order_info['piao']/$order_info['num'] ?></em>共享币</div>
            <div class="pro-amount fr"><span class="font-13">数量×<em class="name">1</em></span></div>
          </div>
        </div>
      </div>

    </div>
  </div>
  <div class="weui-panel">
    <div class="weui-panel__bd">
      <div class="weui-media-box weui-media-box_small-appmsg">
        <div class="weui-cells">
          <a class="weui-cell weui-cell_access" >
            <div class="weui-cell__bd weui-cell_primary">
              <p class="font-14"><span class="mg-r-10">订单号</span><span ><em class="num"><?php echo $order_info['order_sn']; ?></em></span></p>
            </div>
          </a>
          <div class="weui-cell weui-cell_access" href="javascript:;">
            <div class="weui-cell__bd weui-cell_primary">
              <?php $str_status = array('1'=>'待提货','2'=>'待发货','3'=>'待收货','4'=>'已完成','5'=>'已取消','6'=>'退换中','7'=>'已退货') ?>
              <p class="font-14"><span class="mg-r-10">订单状态</span><span class="fr txt-color-red"><?php echo $str_status[$order_info['status']]; ?></span></p>
            </div>
          </div>
          <?php if ($order_info['status'] == 6): ?>
            <?php $str_return_status = array('0'=>'商家未受理','1'=>'商家已受理','2'=>'商家已拒绝') ?>
            <?php if ($order_info['return_status']==0): ?>
            <div class="weui-cell weui-cell_access" href="javascript:;">
              <div class="weui-cell__bd weui-cell_primary">
                <p class="font-14"><span class="mg-r-10">退换状态</span><span class="fr txt-color-red"><?php echo $str_return_status[$order_info['return_status']]; ?></span></p>
              </div>
            </div>
            <?php elseif ($order_info['return_status']==1): ?>
            <div class="weui-cell weui-cell_access" href="javascript:;">
              <div class="weui-cell__bd weui-cell_primary">
                <p class="font-14"><span class="mg-r-10">退换状态</span></p>
                <div class="font-14" style="margin-top: 10px;background-color: #f5f5f5;border: 1px solid #e3e3e3;border-radius: 4px;-webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.05);box-shadow: inset 0 1px 1px rgba(0,0,0,.05);    line-height: 22px;    padding-bottom: 10px;">
                <p style="padding: 2px 10px">
                <span class="txt-color-red"><?php echo $str_return_status[$order_info['return_status']]; ?></span>
                </p>
                <p style="padding: 2px 10px">
                  <?php echo $str_return_status[$order_info['return_status']]; ?>您的申请，请您与负责人： <span class="txt-color-red"><?php echo $b_name ?></span>  进行沟通 ，联系方式： <span class="txt-color-red"><?php echo $b_phone_num ?></span>，如协商完毕，请按后方按钮确认沟通结果！ 
                  <?php if ($order_info['return_result'] == 2 || $order_info['return_result'] == 3): ?>
                      <a href="javascript:;" class="ords-btn-com receipt" style="background: #fff;padding: 0 10px;border: 1px solid red;color: red;font-size: 12px;">协商完成</a>
                  <?php else: ?>
                      <a id="result" href="javascript:;" class="ords-btn-com receipt" style="background: red;padding: 0 10px;border: 1px solid red;color: #fff;font-size: 12px;">已和商家协商</a>
                  <?php endif ?>
                </p>
                <p>
                 
                </p>
                </div>
              </div>
            </div>
          <?php elseif ($order_info['return_status']==2): ?>
            <div class="weui-cell weui-cell_access" href="javascript:;">
              <div class="weui-cell__bd weui-cell_primary">
                <p class="font-14"><span class="mg-r-10">退换状态</span></p>
                <div class="font-14" style="margin-top: 10px;background-color: #f5f5f5;border: 1px solid #e3e3e3;border-radius: 4px;-webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.05);box-shadow: inset 0 1px 1px rgba(0,0,0,.05);    line-height: 22px;    padding-bottom: 10px;">
                <p style="padding: 2px 10px">
                <span class="txt-color-red"><?php echo $str_return_status[$order_info['return_status']]; ?></span>
                </p>
                <p style="padding: 2px 10px">
                  <?php echo $str_return_status[$order_info['return_status']]; ?>您的申请，请您与负责人： <span class="txt-color-red"><?php echo $b_name ?></span>  进行沟通 ，联系方式： <span class="txt-color-red"><?php echo $b_phone_num ?></span>，如协商失败，请申诉！ 
                  <?php if ($order_info['return_result'] == 2 || $order_info['return_result'] == 3): ?>
                        <a href="javascript:;" class="ords-btn-com receipt" style="background: #fff;padding: 0 10px;border: 1px solid red;color: red;font-size: 12px;">客服已介入</a>
                  <?php else: ?>
                      <a id="appeal" href="javascript:;" class="ords-btn-com receipt" style="background: red;padding: 0 10px;border: 1px solid red;color: #fff;font-size: 12px;">客服介入</a>
                      <a id="cancel_return" href="javascript:;" class="ords-btn-com receipt" style="background: red;padding: 0 10px;border: 1px solid red;color: #fff;font-size: 12px;">取消退换</a>
                  <?php endif ?>
                </p>
                </div>
              </div>
            </div>
          <?php endif ?>
          <?php endif ?>
          <div class="weui-cell weui-cell_access">
            <div class="weui-cell__bd weui-cell_primary">
              <p class="font-14"><span class="mg-r-10">配送方式</span><span class="fr"><?php echo $order_info['is_ziti']==1?'自提':'快递'; ?></span></p>
            </div>
          </div>
          <div class="weui-cell weui-cell_access" href="javascript:;">
            <div class="weui-cell__bd weui-cell_primary">
              <p class="font-14"><span class="mg-r-10">运费</span><span class="fr txt-color-red">包邮</span></p>
            </div>
          </div>
          <div class="weui-cell weui-cell_access" href="javascript:;">
            <div class="weui-cell__bd weui-cell_primary">
              <p class="font-14"><span class="mg-r-10">快递公司</span><span class="fr"><?php echo $transport?$transport:'无'; ?></span></p>
            </div>
          </div>
           <div class="weui-cell weui-cell_access" href="javascript:;">
            <div class="weui-cell__bd weui-cell_primary">
              <p class="font-14"><span class="mg-r-10">快递单号</span><span class="fr"><?php if($order_info['waybill']=='#'){echo '无';}elseif($order_info['waybill']){echo $order_info['waybill'];}else{ echo '无';} ?></span>
              </p>
            </div>
          </div>
          <div class="weui-cell weui-cell_access" href="javascript:;">
            <div class="weui-cell__bd weui-cell_primary">
              <p class="font-14"><span class="mg-r-10">商家店铺地址</span></p>
              <p class="font-14" style="margin-top:10px">
              <span class="txt-color-red"><?php echo $business_address; ?></span>
              </p>
            </div>
          </div>
           <a class="weui-cell weui-cell_access " style="margin-bottom: 10px;">
            <div class="weui-cell__bd weui-cell_primary">
              <p class="font-14"><span class="mg-r-10">生成订单时间:</span><span ><em class="num"><?php echo $order_info['add_time']; ?></em></span></p>
            </div>
          </a>
        
            <div class="weui-cell__bd clear" style="margin-bottom: 10px;">
            <?php if ($order_info['status'] == 1): ?>
            <a href="javascript:;" onClick="tihuo(<?php echo $order_info['order_id']; ?>)" class="weui-btn weui-btn_mini weui-btn_warn fr mg-r-10">确认提货</a>
            <?php elseif($order_info['status'] == 2): ?>
            <a href="javascript:;" onClick="cancel_order(<?php echo $order_info['order_id']; ?>)" class="weui-btn weui-btn_mini weui-btn_warn fr mg-r-10">取消订单</a>
            <?php elseif($order_info['status'] == 3): ?>
            <a href="javascript:;" onClick="shouhuo(<?php echo $order_info['order_id']; ?>)" class="weui-btn weui-btn_mini weui-btn_warn fr mg-r-10">确认收货</a>
            <a href="/exchange/member/return_goods?order_id=<?php echo $order_info['order_id']; ?>" class="weui-btn weui-btn_mini weui-btn_warn fr mg-r-10">申请退换</a>
            <?php elseif($order_info['status'] == 4): ?>

              <?php if ($order_info['is_eval'] == 0): ?>
              <a href="/Exchange/Member/add_evaluate?order_id=<?php echo $order_info['order_id']; ?>" class="weui-btn weui-btn_mini weui-btn_warn fr mg-r-10">评价订单</a>
              <?php endif ?>

              <?php if ($order_info['success_time']  >= date('Y-m-d H:i:s',(time()-3600*48)) && false): ?>
              <a href="/exchange/member/return_goods?order_id=<?php echo $order_info['order_id']; ?>" class="weui-btn weui-btn_mini weui-btn_warn fr mg-r-10">申请退换</a>
              <?php endif ?>

            <?php endif ?>
            </div>

        </div>
      </div>
    </div>
  </div> 
</div>
</body>
<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>
<script>
  $(function() {
    FastClick.attach(document.body);
  });
</script>
<script type="text/javascript">
    function tihuo(order_id){
        $.confirm("如果您没有拿到商品请取消操作","您确定已拿到此商品了吗?", function() {
            $.ajax({
                cache: true,
                type: "POST",
                url:"/exchange/member/order_success",
                data:{'order_id':order_id},
                dataType: 'json',
                async: false,
                error: function(data) {
                    $.toast("网络错误", "cancel");
                },
                success: function(data) {
                    if (data.error == 0) {
                        $.toast("订单已完成");
                        setTimeout('window.location.reload();',1000);
                    }else{
                        $.toast(data.msg, "cancel");
                    }
                    
                }
            });
            
        }, function() {
          //取消操作
        });
    }
    
    function shouhuo(order_id){
        $.confirm("如果您没有收到商品请取消操作","您确定已收到此商品了吗?", function() {
            $.ajax({
                cache: true,
                type: "POST",
                url:"/exchange/member/order_success",
                data:{'order_id':order_id},
                dataType: 'json',
                async: false,
                error: function(data) {
                    $.toast("网络错误", "cancel");
                },
                success: function(data) {
                    if (data.error == 0) {
                        $.toast("已确认收货");
                        setTimeout('window.location.reload();',1000);
                    }else{
                        $.toast(data.msg, "cancel");
                    }
                    
                }
            });
            
        }, function() {
          //取消操作
        });
    }

    function cancel_order(order_id){
        $.confirm("如果您不想取消这笔订单请取消操作","您确定要取消这笔订单吗?", function() {
            $.ajax({
                cache: true,
                type: "POST",
                url:"/exchange/member/cancel_order",
                data:{'order_id':order_id},
                dataType: 'json',
                async: false,
                error: function(data) {
                    $.toast("网络错误", "cancel");
                },
                success: function(data) {
                    if (data.error == 0) {
                        $.toast("订单已取消");
                        setTimeout('window.location.reload();',1000);
                    }else{
                        $.toast(data.msg, "cancel");
                    }
                    
                }
            });
            
        }, function() {
          //取消操作
        });
    }

    $('#result').click(function(){
        var order_id = <?php echo $_GET['order_id']; ?>;
        if (!order_id) {
            $.toast("参数错误", "cancel");
            return false;
        }
        $.confirm("确认后商家可向客服申请结算","确定您和商家沟通清楚了吗?", function() {
            $.ajax({
                cache: true,
                type: "POST",
                url:"/exchange/member/return_result",
                data:{'order_id':order_id},
                dataType: 'json',
                async: false,
                error: function(data) {
                    $.toast("网络错误", "cancel");
                },
                success: function(data) {
                    if (data.error == 0) {
                        $.toast(data.msg);
                        setTimeout('window.location.reload();',1000);
                    }else{
                        $.toast(data.msg, "cancel");
                    }
                    
                }
            });
            
        }, function() {
          //取消操作
        });
    });

    $('#cancel_return').click(function(){
        var order_id = <?php echo $_GET['order_id']; ?>;
        if (!order_id) {
            $.toast("参数错误", "cancel");
            return false;
        }
        $.confirm("如果您取消退换商品，我们将视为您已收到货并且结束此订单，如果未收到货请取消操作","您确定取消退换商品吗?", function() {
            $.ajax({
                cache: true,
                type: "POST",
                url:"/exchange/member/order_success",
                data:{'order_id':order_id},
                dataType: 'json',
                async: false,
                error: function(data) {
                    $.toast("网络错误", "cancel");
                },
                success: function(data) {
                    if (data.error == 0) {
                        $.toast("已取消退换");
                        setTimeout('window.location.reload();',1000);
                    }else{
                        $.toast(data.msg, "cancel");
                    }
                    
                }
            });
            
        }, function() {
          //取消操作
        });
    });

    $('#appeal').click(function(){
        var order_id = <?php echo $_GET['order_id']; ?>;
        if (!order_id) {
            $.toast("参数错误", "cancel");
            return false;
        }
        $.confirm("确认后客服会在2个工作日内联系您，请耐心等待","您确定需要客服介入吗?", function() {
            $.ajax({
                cache: true,
                type: "POST",
                url:"/exchange/member/appeal",
                data:{'order_id':order_id},
                dataType: 'json',
                async: false,
                error: function(data) {
                    $.toast("网络错误", "cancel");
                },
                success: function(data) {
                    if (data.error == 0) {
                        $.toast("已申请客服介入");
                        setTimeout('window.location.reload();',1000);
                    }else{
                        $.toast(data.msg, "cancel");
                    }
                    
                }
            });
            
        }, function() {
          //取消操作
        });
    });
</script>