<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?php echo $webConfig['title']; ?></title>
    <meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no"/>
    <meta content="yes" name="apple-mobile-web-app-capable">
    <meta content="black" name="apple-mobile-web-app-status-bar-style">
    <meta content="telephone=no" name="format-detection">
    <link rel="stylesheet" href="/Public/Index/index/css/font-awesome.min.css">
    <link rel="stylesheet" href="/Public/Index/index/css/navpage.css">
    <script src="/Public/Index/index/js/main.js"></script>
    <script src="/Public/Index/index/js/zepto.min.js"></script>
    <script src="/Public/Index/index/js/jquery-3.1.1.js"></script>
    <script src="/Public/Index/index/js/amazeui.min.js"></script>
</head>
<body>