<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>


<body class="gray-bg">
    <div class="wrapper wrapper-content animated fadeInRight">
       
        <div class="row">
            <div class="col-sm-12">
                <div class="ibox float-e-margins">
                   <div class="ibox-title">
                            <h5>会员添加</h5>
                    </div>
                    <div class="ibox-content">
                        <div class="alert alert-warning">
                            提示：您可以通过本页面添加会员到您的会员列表，如果首次录入数据量大的话，推荐您使用右侧按钮进行本地导入。
                            <a href="/Business/Member/addByExcel"><p class="btn btn-success btn-sm pull-right" style="margin-top: -7px;"><i class="fa fa-table"></i>&nbsp;Excel&nbsp;表格批量导入会员</p></a>
                        </div>
                        <form class="form-horizontal m-t" id="">
                            <input name="is_formal" type="hidden" value="1">
                            <div class="form-group">
                                <label class="col-sm-3 control-label">姓名：</label>
                                <div class="col-sm-8">
                                    <input id="cname" name="name" type="text" class="form-control" required="" aria-required="true">
                                </div>
                            </div>
                          	 <div class="form-group">
                                <label class="col-sm-3 control-label">电话：</label>
                                <div class="col-sm-8">
                                    <input id="tel-num" name="phone_num" type="number" class="form-control" required="" aria-required="true">
                                </div>
                            </div>
							<div class="form-group">
                                <label class="col-sm-3 control-label">性别：</label>
                                <div class="col-sm-8">
                                    <div class="radio i-checks">
                                        <label><input type="radio" checked="" value="1" name="sex"> <i></i> 男</label>
                                    </div>
                                    <div class="radio i-checks">
                                        <label><input type="radio" value="0" name="sex"> <i></i> 女</label>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">生日：</label>
                                <div class="col-sm-8">
                                    <input value="" name="birth_time" type="text" class="form-control layer-date" onclick="laydate({istime: true, format: 'YYYY-MM-DD'})" required="" aria-required="true">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">入会时间：</label>
                                <div class="col-sm-8">
                                    <input value="" name="join_time" type="text" class="form-control layer-date" onclick="laydate({istime: true, format: 'YYYY-MM-DD'})" required="" aria-required="true">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">会员级别：</label>
                                <div class="col-sm-8">
                                    <div class="radio i-checks">
                                        <label><input type="radio" value="A" name="level"> <i></i> A</label>
                                    </div>
                                    <div class="radio i-checks">
                                        <label><input type="radio" value="B" name="level"> <i></i> B</label>
                                    </div>
                                    <div class="radio i-checks">
                                        <label><input type="radio" value="C" name="level"> <i></i> C</label>
                                    </div>
                                    <div class="radio i-checks">
                                        <label><input type="radio" checked="" value="D" name="level"> <i></i> D</label>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">备注：</label>
                                <div class="col-sm-8">
                                    <textarea class="form-control" rows="3" style="resize:none;" placeholder="最多输入255个字符" name="notice"></textarea>
                                </div>
                            </div>
                            <div class="form-group form-group-bottom">
                                <div class="col-sm-2 col-sm-offset-3">
                                    <p class="btn btn-primary" onclick="submitAdd();">确定添加</p>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            
            </div>
           
        </div>
    </div>
</body>
<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>
<script>
    //按钮样式
    $(document).ready(function(){$(".i-checks").iCheck({checkboxClass:"icheckbox_square-green",radioClass:"iradio_square-green",})});
    //添加会员
    function submitAdd(){
        var url = '/Business/Member/add';
        $.post(url,$('form').serialize(),function(d){
            if(d.error){
                swal(d.msg, "", "error");
                return false;
            }else{
                swal(d.msg, "", "success");
                setTimeout('window.location.reload()',1200);
            }
        },'json');
    }
</script>
