<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>


<body class="gray-bg">
    <div class="wrapper wrapper-content animated fadeInRight">
            <div class="row">
                <div class="col-sm-12">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h5>发放明细</h5>
							<span class="label label-primary pull-right label-primary-cust">
	                            <a href="javascript:history.back(-1);" class="fa-lg-cust-a" title="返回上一页">
	                                <i class="fa fa-arrow-left fa-lg-cust" aria-hidden="true"></i>
	                            </a>
	                        </span>
                        </div>
                        <div class="ibox-content">
                            <div class=" alert alert-warning" style="margin: 0 auto;">
                                <div class="row">
                                    <div class="col-sm-2">
                                        姓名: <b><?php echo $_GET['name']; ?></b>
                                    </div>
                                    <div class="col-sm-2">
                                        性别: <b><?php echo $_GET['sex']; ?></b>
                                    </div>
                                    <div class="col-sm-2">
                                        手机号: <b><?php echo $_GET['phone_num']; ?></b>
                                    </div>
                                </div>
                            </div>
                            <br>
                            <table class="footable table table-stripped toggle-arrow-tiny" >
                                <thead>
                                  <tr>
                                        <th>发生时间</th>
                                        <th>消费金额</th>
                                        <th>增加共享币数</th>
                                        <th>类型</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach($result as $v): ?>
                                    <tr>
                                        <td><?php echo $v['add_time']; ?></td>
                                        <td><?php echo $v['pay_num']; ?></td>
                                        <td><?php echo $v['add_piao']; ?></td>
                                        <td><?php echo $v['type']; ?></td>
                                    </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</body>
<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>
