<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<style>
.laydate_body .laydate_table {
    display: none;
    width: 240px!important;
    margin: 0!important;
    border: 1px solid #ccc;
    border-top: none;
    border-bottom: none;
}
#laydate_MM{
	 display: none!important;
}
.laydate_body .laydate_ym {
    border: 1px solid #009F95;
    background-color: #009F95;
    width: 228px !important;
}
.laydate_body .laydate_y input {
    width: 171px !important;
    margin-right: 15px;
}
.laydate_body .laydate_y .laydate_yms {
    width: 229px !important;
    text-align: center;
}
</style>
<body class="gray-bg">
    <div class="wrapper wrapper-content animated fadeInRight">
    	<div class="alert alert-info">
	    	<div class="row">
	            <div class="col-sm-8">
		            <input id="year" value="<?php echo $_GET['year'] ? $_GET['year'] : date('Y'); ?>" class="laydate-icon form-control layer-date datepicker" style='width: 40%;margin-top: -8px; margin-right: 5px'>
		            <button type="button" class="btn btn-primary" data-container="body" onclick="javascript:enterYear();" data-toggle="popover" data-placement="left" style='padding: 5px 10px;margin-top:-3px;margin-right: 5px'>
		                查看
		            </button>
		            <button type="button" class="btn btn-success" data-container="body" onclick="javascript:enterYear('theYear');" data-toggle="popover" data-placement="left" style='padding: 5px 10px;margin-top: -3px; margin-right: 5px'>
		                今年
		            </button>
	            </div>
	        </div>
            
        </div>
        <div class="row">
            <div class="col-sm-6">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5><?php echo $_GET['year'] ? $_GET['year'] : date('Y'); ?>年会员入会时间增长变化（月/人）</small></h5>
                    </div>
                    <div class="ibox-content">

                        <div class="echarts" id="echarts-bar-chart"></div>
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5><?php echo $_GET['year'] ? $_GET['year'] : date('Y'); ?>年入会的会员性别比例</h5>
                    </div>
                    <div class="ibox-content">
                        <div class="echarts" id="echarts-pie-chart"></div>
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5><?php echo $_GET['year'] ? $_GET['year'] : date('Y'); ?>年入会的会员级别比例</h5>
                    </div>
                    <div class="ibox-content">
                        <div class="echarts" id="echarts-pie-chart-2"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>

<script src="/Public/hplus/js/plugins/echarts/echarts-all.js"></script>

<script>
 $(".datepicker").datepicker({
            language: "zh-CN",
            startView: 2,  
            maxViewMode: 2,
            minViewMode:2,
            forceParse: false, 
            weekStart: 1, 
            autoclose: true,//选中之后自动隐藏日期选择框
            clearBtn: true,//清除按钮
            format: "yyyy"//日期格式
        });
       
</script>

<script>
	function enterYear(year){
		if(year == 'theYear'){
			window.location.href = '/Business/Member/member_count?year=<?php echo date('Y'); ?>'
		}else{
			window.location.href = '/Business/Member/member_count?year=' + $('#year').val();
		}
	}
</script>

<script>
    $(function () {
        var t = echarts.init(document.getElementById("echarts-bar-chart")),
            n = {
                title: {
                    text: ""
                },
                tooltip: {
                    trigger: "axis"
                },
                legend: {
                    data: ["会员人数"],
                    x: "right"
                },
                grid: {
                    x: 30,
                    x2: 40,
                    y2: 24
                },
                calculable: !0,
                xAxis: [{
                    type: "category",
                    data: ["1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月", "11月", "12月"]
                }],
                yAxis: [{
                    type: "value"
                }],
                series: [{
                    name: "会员人数",
                    type: "bar",
                    data: [<?php echo $monthCount[1]; ?>, <?php echo $monthCount[2]; ?>, <?php echo $monthCount[3]; ?>, <?php echo $monthCount[4]; ?>, <?php echo $monthCount[5]; ?>, <?php echo $monthCount[6]; ?>, <?php echo $monthCount[7]; ?>, <?php echo $monthCount[8]; ?>, <?php echo $monthCount[9]; ?>, <?php echo $monthCount[10]; ?>, <?php echo $monthCount[11]; ?>, <?php echo $monthCount[12]; ?>],
                    markPoint: {
                        data: [{
                            type: "max",
                            name: "最大值"
                        }, {
                            type: "min",
                            name: "最小值"
                        }]
                    },
                    markLine: {
                        data: [{
                            type: "average",
                            name: "平均值"
                        }]
                    }
                }]
                  
                
            };
        t.setOption(n), window.onresize = t.resize;
        var l = echarts.init(document.getElementById("echarts-pie-chart")),
            u = {
                title: {
                    text: "会员性别比例",
                    subtext: "",
                    x: "center"
                },
                tooltip: {
                    trigger: "item",
                    formatter: "{a} <br/>{b} : {c} ({d}%)"
                },
                legend: {
                    orient: "vertical",
                    x: "left",
                    data: ["男", "女"]
                },
                calculable: !0,
                series: [{
                    name: "性别比例",
                    type: "pie",
                    radius: "55%",
                    center: ["50%", "60%"],
                    data: [{
                        value: <?php echo $sex[1]; ?>,
                        name: "男"
                    }, {
                        value: <?php echo $sex[0]; ?>,
                        name: "女"
                    }]
                }]
            };
        l.setOption(u), $(window).resize(l.resize);
        var v = echarts.init(document.getElementById("echarts-pie-chart-2")),
            u = {
                title: {
                    text: "会员级别比例",
                    subtext: "",
                    x: "center"
                },
                tooltip: {
                    trigger: "item",
                    formatter: "{a} <br/>{b} : {c} ({d}%)"
                },
                legend: {
                    orient: "vertical",
                    x: "left",
                    data: ["A", "B", "C", "D"]
                },
                calculable: !0,
                series: [{
                    name: "级别比例",
                    type: "pie",
                    radius: "55%",
                    center: ["50%", "60%"],
                    data: [{
                        value: <?php echo $level['A']; ?>,
                        name: "A"
                    }, {
                        value: <?php echo $level['B']; ?>,
                        name: "B"
                    }, {
                        value: <?php echo $level['C']; ?>,
                        name: "C"
                    }, {
                        value: <?php echo $level['D']; ?>,
                        name: "D"
                    }]
                }]
            };
        v.setOption(u), $(window).resize(v.resize);
    });
</script>