<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<style>

</style>
  <style type="text/css">
  .exchange-img {
    /* display: inline-block; */
    height: 40vh!important;
     width: 50vw !important; 
    margin: 0 auto;
}
    </style>
<body class="gray-bg">
    <div class="wrapper wrapper-content animated fadeInRight">

        <div class="row" style="background: #fff; margin-right: 0px; margin-left: 0px;">
            <div class="col-sm-12">
                <div class="ibox float-e-margins business-info" style="margin-bottom: 0px;">
                    <div class="ibox-title">
                        <h5>商品详情</h5>  
                        <span class="label label-primary pull-right label-primary-cust">
                            <a href="javascript:history.back(-1);" class="fa-lg-cust-a" title="返回上一页">
                                <i class="fa fa-arrow-left fa-lg-cust" aria-hidden="true"></i>
                            </a>
                        </span> 
                    </div>
                </div>
            </div> 
            <div class="col-sm-5" style="padding-right: 0px;">
                    <div class="ibox float-e-margins">
                        <div class="ibox-content" style="">
                            <div class="carousel slide" id="carousel1">
                                <div class="carousel-inner">
                                    <?php foreach ($goods_info['pics'] as $key => $value): ?>
                                    <div class="item <?php echo $key == 0?'active':''; ?>">
                                        <img alt="image" class="img-responsive exchange-img" src="<?php echo $value; ?>">
                                    </div>
                                    <?php endforeach ?>
                                    
                                </div>
                                <a data-slide="prev" href="carousel.html#carousel1" class="left carousel-control">
                                    <span class="icon-prev"></span>
                                </a>
                                <a data-slide="next" href="carousel.html#carousel1" class="right carousel-control">
                                     <span class="icon-next"></span>
                                </a>
                            </div>
                            <div class="user-button" style="margin-top: 30px;">
                                            <div class="row" >
                                                <div class="col-sm-12" style="text-align: center;">
                                                    <?php if ($goods_info['business_id']==$this_business_id): ?>
                                                    <a href="javascript:;" type="button" class="btn btn-default btn-sm " style="font-size: 15px;">我的商品</a>
                                                    <?php else: ?>
                                                        <?php if ($goods_info['is_agent'] == 1): ?>
                                                        <a href="javascript:;" type="button" class="btn btn-default btn-sm " style="font-size: 15px;">已经代理</a>
                                                        <?php else: ?>
                                                            <?php if($goods_info['nums'] > 0): ?>
                                                            <a href="javascript:doAgent(<?php echo $goods_info['goods_id']; ?>);" type="button" id="doAgentButton" class="btn btn-warning btn-sm " style="font-size: 15px;">我要代理</a>
                                                            <?php else: ?>
                                                            <a href="javascript:;" type="button" class="btn btn-default btn-sm " style="font-size: 15px;">没有库存</a>
                                                            <?php endif ?>
                                                        <?php endif ?>
                                                    <?php endif ?>
                                                </div>
                                               
                                            </div>
                                        </div>
                        </div>
                    </div>
              </div>
               <div class="col-sm-7" style="padding-left: 0px;">
                 <div class="ibox float-e-margins">
                                     <div class="ibox-content " style='line-height: 40px;font-size:15px;'>
                                        <h2><strong><?php echo $goods_info['goods_name']; ?></strong></h2>
                                        <strong> 商家ID：</strong><span><?php echo $goods_info['business_id']; ?></span>  <br>
                                        <strong> 商城名称：</strong><span><?php echo $goods_info['exchange_name']; ?></span>&nbsp;&nbsp;&nbsp;<a href="/business/goods/exchange?business_id=<?php echo $goods_info['business_id']; ?>" style="color:#0717ea;">【全部商品】</a> <br>
                                        <strong> 商家公司：</strong><span><?php echo $goods_info['company_name']; ?></span>  <br>
                                        <strong> 商家电话：</strong><span><?php echo $goods_info['phone_num']; ?></span><br>
                                        <strong> 商家所在地：</strong><span><?php echo $province.' '.$city.' '.$area; ?></span>  
                                        <hr style="margin: 5px;" />
                                        <strong> 兑换价格：</strong><span><?php echo $goods_info['piao']; ?></span> 共享币 <br>
                                        <strong> 商品类型：</strong><span><?php echo $goods_info['goods_type_name']; ?></span> <br>
                                        <strong> 商品库存：</strong><span><?php echo $goods_info['nums']; ?></span> 件 <br>
                                        <strong> 销售返利：</strong><span><?php echo $goods_info['rebate'] * 100; ?></span>% <br>
                                        <strong> 商品描述：</strong><span><?php echo $goods_info['description']; ?></span><br>

                                        
                                    </div>
                                    </div>
                </div>                 
               
                
            
        </div>
    </div>
    <?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>

</body>
<script type="text/javascript">
    //我要代理
    function doAgent(goods_id){
        var url = '/Business/Goods/exchange';
        $.post(url,{goods_id:goods_id},function(d){
            if(d.error){
                  swal(d.msg, "", "error");
                return false;
            }else{
                swal(d.msg, "", "success");
                $('#doAgentButton').attr('class','btn btn-default btn-sm').text('已经代理');
                return false;
            }
        },'json');
    }
</script>