<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>

<style>
.good-img{
	width: 50px;
	height: 50px;
	display: block;
}
table{
    font-size: 13px;
}
.footable-row-detail-name {
    display: table-cell;
    font-weight: bold;
    padding-right: 0.5em;
    line-height: 30px;
    min-width: 80px;
}
.modal-backdrop{
    display: none;
}
</style>

<body class="gray-bg">
    <div class="wrapper wrapper-content animated fadeInRight" >
        <div class="row">
            <div class="col-sm-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>我的商品</h5>
                    </div>
                    <div class="ibox-content">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="input-group col-sm-12">
                                    <form method="get" action="/business/goods/lists" class="clearfix pull-left" >
                                        <select name="goods_type_id" class="input-sm form-control input-s-sm inline sex-select " style="width: 20%;margin-right: 10px;">
                                            <option value="0">商品类型</option>
                                            <option disabled="true">--------------------</option>
                                            <?php foreach($goods_type as $v): ?>
                                            <option <?php echo $_GET['goods_type_id'] == $v['goods_type_id'] ? 'selected' : ''; ?> value="<?php echo $v['goods_type_id']; ?>"><?php echo $v['goods_type_name']; ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                        <select name="is_gx" class="input-sm form-control input-s-sm inline sex-select " style="width: 20%;margin-right: 10px;">
                                            <option value="0">共享状态</option>
                                            <option disabled="true">--------------------</option>
                                            <option <?php echo $_GET['is_gx'] == 1 ? 'selected' : ''; ?> value="1">是</option>
                                            <option <?php echo $_GET['is_gx'] == 2 ? 'selected' : ''; ?> value="2">否</option>
                                        </select>
                                        <select name="status" class="input-sm form-control input-s-sm inline sex-select " style="width: 20%;margin-right: 10px;">
                                            <option value="0">上架状态</option>
                                            <option disabled="true">--------------------</option>
                                            <option <?php echo $_GET['status'] == 1 ? 'selected' : ''; ?> value="1">上架</option>
                                            <option <?php echo $_GET['status'] == 2 ? 'selected' : ''; ?> value="2">下架</option>
                                        </select>
                                        <input type="text" name="keywords" value="<?php echo $_GET['keywords'] ? $_GET['keywords'] : ''; ?>" placeholder="商品名称关键字" class="input-sm form-control pull-left col-sm-4" style="width:30%;" >
                                        <span class="input-group-btn pull-left " >
                                            <button type="submit" class="btn btn-sm btn-primary search-btn"> 搜索</button>
                                        </span>
                                    </form>
                                    <button type="button" onclick="javascript:window.location.href = '/business/goods/lists';" class="btn btn-danger btn-sm  reset-btn pull-left" style="margin-left: 34px;">刷新</button>
                                     <button type="button" onclick="javascript:window.location.href = '/business/goods/add';" class="btn btn-success btn-sm  reset-btn pull-left" style="margin-left: 30px;">添加新商品</button>
                                </div>
                            </div>
                        </div>
                        <div class="member-warn">
                            <div class="alert alert-warning">
                                您现在共有商品： <span class="alert-link"><?php echo $count; ?></span> 种
                                <?php if($_GET['goods_type_id'] > 0 || $_GET['is_gx'] > 0 || $_GET['status'] > 0 || !empty($_GET['keywords'])): ?>
                                ，以下为搜索&nbsp;&nbsp;
                                <?php if($_GET['goods_type_id'] > 0): ?>
                                商品类型是 “<span class="alert-link"><?php echo $goods_type[$_GET['goods_type_id'] - 1]['goods_type_name']; ?></span>”&nbsp;&nbsp;
                                <?php endif; ?>
                                <?php if($_GET['is_gx'] > 0): ?>
                                共享状态是 “<span class="alert-link"><?php echo $_GET['is_gx'] == 1 ? '是' : '否'; ?></span>”&nbsp;&nbsp;
                                <?php endif; ?>
                                <?php if($_GET['status'] > 0): ?>
                                上架状态是 “<span class="alert-link"><?php echo $_GET['status'] == 1 ? '上架' : '下架'; ?></span>”&nbsp;&nbsp;
                                <?php endif; ?>
                                <?php if(!empty($_GET['keywords'])): ?>
                                商品名称包含 “<span class="alert-link"><?php echo $_GET['keywords']; ?></span>”&nbsp;&nbsp;
                                <?php endif; ?>
                                的商品，共 <span class="alert-link"><?php echo $where_count; ?></span> 种
                                <?php endif; ?>
                            </div>
                        </div>
                        <table class=" table table-stripped toggle-arrow-tiny" data-sorting="false">
                            <thead>
                                <tr>
                                    <th >序号</th>
                                    <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;商品名</th>
                                    <th>商品图</th>
                                    <th>商品类型</th>
                                    <th>兑换价格（共享币）</th>
                                    <th data-hide="all">库存</th>
                                    <th >上架状态</th>
                                    <th>是否共享</th>
                                    <th data-hide="all">销售返利</th>
                                    <th data-hide="all">商品描述</th>
                                    <th>操作</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach($goods as $k => $v): ?>
                                <tr>
                                    <td><?php echo $k + 1 + $page['firstRow']; ?></td>
                                    <td class="show_jian" data-container="body" data-toggle="popover" data-placement="bottom" data-content="<?php echo $v['goods_name']; ?>"><?php echo $v['is_jian'] == 1 ? '<img data-container="body" data-toggle="popover" data-placement="bottom" data-content="推荐商品" src="/Public/hplus/img/orange_jian.png">' : '&nbsp;&nbsp;&nbsp;&nbsp;'; ?>&nbsp;<?php echo mb_substr($v['goods_name'],0,15); if(strlen($v['goods_name']) > 15) echo ' ....'; ?></td>
                                    <td><img src="<?php echo explode(';',$v['pics'])[0]; ?>" alt="" class="good-img"></td>
                                    <td><?php echo $goods_type[$v['goods_type_id'] - 1]['goods_type_name']; ?></td>
                                    <td><?php echo $v['piao']; ?> 个</td>
                                    <td><?php echo $v['nums']; ?></td>
                                    <td class="show_status"><?php echo $v['status'] == 1 ? '<span class="text-success">上架</span>' : '<span class="text-muted">下架</span>'; ?></td>
                                    <td class="show_gx"><?php echo $v['is_gx'] == 1 ? '是' : '否'; ?></td>
                                    <td><?php echo $v['rebate'] * 100; ?> %</td>
                                    <td><?php echo $v['description'];?></td>
                                    <td>
                                        <a href="#" class="myModal"   data-toggle="modal" data-target="#myModal_<?php echo $v['goods_id'] ?>">
                                            <span class="label label-info ">分组</span>
                                        </a>
                                        <div class="modal inmodal" id="myModal_<?php echo $v['goods_id'] ?>" tabindex="-1" role="dialog" aria-hidden="true">
                                            <div class="modal-dialog">
                                                <div class="modal-content animated bounceInRight">
                                                    <div class="modal-header">
                                                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">关闭</span>
                                                        </button>
                                                        <h4 class="modal-title">分配商品到分组</h4>
                                                    </div>
                                                    <div class="modal-body">  
                                                        <div class="form-group"><label>选择分组</label>
                                                            <select style="color:#000;" id="groups_<?php echo $v['goods_id'] ?>" class="form-control" name="groups_id">
                                                                <?php foreach ($groups as $kk => $vv): ?>

                                                                <?php $disabled = "";
                                                                     if (in_array($vv['group_id'], $existing_groups[$v['goods_id']])) {
                                                                        $disabled = 'disabled="disabled" style="color:#DDD;"';
                                                                    } 
                                                                ?>
                                                                <option <?php echo $disabled; ?> value="<?php echo $vv['group_id']; ?>"><?php echo $vv['group_name']; ?></option>
                                                                <?php endforeach ?>
                                                            </select>
                                                        </div>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button id="close_<?php echo $v['goods_id']; ?>" type="button" class="btn btn-white" data-dismiss="modal">关闭操作</button>

                                                        <button type="button" onClick="add_group(<?php echo $v['goods_id']; ?>)" class="btn btn-primary" style=" margin-bottom: 6px;">确认</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <a href="/Business/Goods/edit?goods_id=<?php echo $v['goods_id']; ?>">
                                            <span class="label label-warning ">编辑</span>
                                        </a>
                                        <a href="javascript:;">
                                            <span class="label label-success updateStatus" status="<?php echo $v['status']; ?>" goods_id="<?php echo $v['goods_id']; ?>"><?php echo $v['status'] == 1?'下架':'上架' ?></span>
                                        </a>
                                         <a href="/Business/Goods/extend?goods_id=<?php echo $v['goods_id']; ?>&goods_name=<?php echo $v['goods_name']; ?>&goods_type_name=<?php echo $goods_type[$v['goods_type_id'] - 1]['goods_type_name']; ?>&piao=<?php echo $v['piao'] ?>&nums=<?php echo $v['nums'] ?>&rebate=<?php echo $v['rebate'] ?>">
                                            <span class="label label-primary ">推广</span>
                                        </a>
                                         <a href="javascript:;">
                                            <span class="label label-danger del_goods" goods_id="<?php echo $v['goods_id']; ?>">删除</span>
                                        </a>
                                    </td>
                                </tr>
                                <?php endforeach; ?>
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td colspan="12">
                                        <div class="b-page">
                                            <?php echo $page['page']; ?>
                                        </div>
                                    </td>
                                </tr>
                            </tfoot>
                        </table>
                    </div>

                    
                </div>
            </div>
        </div>
    </div>
</body>

<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>

<script>
function returnF() {
    return
}
    $(document).ready(function(){$(".table").footable();});
    $(".myModal").click(function(){
        $('.modal-dialog').css('top',$(document).scrollTop())
    })

    $('.myModal').modal({
        keyboard: false,
        backdrop:false,
        show:false
    });


    function add_group(goods_id){
        var group_id = $('#groups_'+goods_id).val();
        if (!group_id) {
            swal('请选择分组', "", "warning");
            return false;
        }else{
            $.ajax({
                cache: true,
                type: "POST",
                url:"/Business/Goods/set_group",
                data:{'group_id':group_id,'good_id':goods_id},
                dataType: 'json',
                async: false,
                error: function(data) {
                   swal('网络错误，请重试！', "", "warning");
                },
                success: function(data) {
                    if (data.error == 0) {
                        swal("成功加入到分组", "", "success");
                        $('#groups_'+goods_id).find('option[value='+group_id+']').attr('disabled',true);
                        $('#groups_'+goods_id).find('option[value='+group_id+']').css('color','#DDD');
                        //IE
                        if(document.all) {
                        document.getElementById("close_"+goods_id).click();
                        }
                        // 其它浏览器
                        else {
                        var e = document.createEvent("MouseEvents");
                        e.initEvent("click", true, true);
                        document.getElementById("close_"+goods_id).dispatchEvent(e);
                        }
                    }else{
                        swal(data.msg, "", "error");
                    }
                }
            });
        }
    }

    $('.updateStatus').click(function(){
        var _this = $(this);
        var goods_id = _this.attr('goods_id');
        if (_this.attr('status') == 1) {
            var status = 2;
            var span_class = 'text-muted';
        }else{
            var status = 1;
            var span_class = 'text-success';
        }
        var s_text = '';
        if (_this.html() == '下架') {
            s_text = '下架商品后会“取消分享”和“取消推荐”！';
        }
        swal({
            title: "您确定要"+_this.html()+"该商品吗？",
            text: s_text,
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "是的，我要"+_this.html()+"！",
            cancelButtonText: "让我再考虑一下…",
            closeOnConfirm: false,
            closeOnCancel: true
        },
        function(isConfirm) {
            if (isConfirm) {
                $.ajax({
                    cache: true,
                    type: "POST",
                    url:"/Business/Goods/updateStatus",
                    data:{'goods_id':goods_id,'status':status},
                    dataType: 'json',
                    async: false,
                    error: function(data) {
                       swal('网络错误，请重试！', "", "warning");
                    },
                    success: function(data) {
                        if (data.error == 0) {
                            var new_status = _this.html();
                            var old_status = _this.parents('td').prevAll('.show_status').children('span').html()
                            _this.html(old_status);
                            _this.parents('td').prevAll('.show_status').children('span').html(new_status);
                            _this.attr('status',status);
                            _this.parents('td').prevAll('.show_status').children('span').attr('class',span_class);
                            if (new_status == '下架') {
                                _this.parents('td').prevAll('.show_jian').children('img').remove();
                                _this.parents('td').prevAll('.show_gx').html('否');
                            }
                            swal("商品已"+new_status+"！", "", "success");
                        }else{
                            swal(data.msg, "", "error");
                        }
                    }
                });
                
            }
        })
    })

    $('.del_goods').click(function(){
        var _this = $(this);
        var goods_id = _this.attr('goods_id');
        swal({
            title: "您确定要删除该商品吗？",
            text: "",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "是的，我要删除！",
            cancelButtonText: "让我再考虑一下…",
            closeOnConfirm: false,
            closeOnCancel: true
        },
        function(isConfirm) {
            if (isConfirm) {
                $.ajax({
                    cache: true,
                    type: "POST",
                    url:"/Business/Goods/delete",
                    data:{'goods_id':goods_id},
                    dataType: 'json',
                    async: false,
                    error: function(data) {
                       swal('网络错误，请重试！', "", "warning");
                    },
                    success: function(data) {
                        if (data.error == 0) {
                            _this.parents('tr').remove();
                            swal("商品已删除！", "", "success");
                        }else{
                            swal(data.msg, "", "error");
                        }
                    }
                });
                
            }
        })
    })
</script>