<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<body>
<div class="container">
    <div class="chatheader clearfix">
        <a href="/chat/task/index" class="fa fa-angle-left"></a><span>我发布的求助</span> <a href="#" class="server "><img
            src="/Public/Chat/index/images/server.png" alt=""></a>
    </div>
    <div class="t-content">
        <div class="suspending">
            <h2>我发布的求助</h2>
        </div>
        <ul class="t-bigbox">
        </ul>
        <div class="load-more">点击加载更多...</div>
        <div class='t-tab'>
            <ul>
                <li><a href="/chat/task/index">
                    <img src="/Public/Chat/index/images/4.jpg" alt=""><span>这里帮</span>
                </a></li>
                <li><a href="#">
                    <img src="/Public/Chat/index/images/1.png" alt=""><span style="color:#BB4B48;">我发布的</span>
                </a></li>
                <li><a href="/chat/task/mypart">
                    <img src="/Public/Chat/index/images/2.png" alt=""><span>我参与的</span>
                </a></li>
                <li><a href="/chat/task/release_task">
                    <img src="/Public/Chat/index/images/3.png" alt=""><span>发布任务</span>
                </a></li>
            </ul>
        </div>
    </div>
</div>
</body>
<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>
<script>
    $.loadmore.get(getData, {
        scroll: true, //默认是false,是否支持滚动加载
        size:3, //默认是10
        flag: 1, //自定义参数，可选，示例里没有用到
    });
    function getData(config, offset, size) {
        config.isAjax = true;
        $.ajax({
            type: 'POST',
            url: '/chat/task/myrelease',
            dataType: 'json',
            success: function (reponse) {
                config.isAjax = false;
                var data = reponse;
                var sum = reponse.length;
                var result = '';
                /************业务逻辑块：实现拼接html内容并append到页面*****************/
                if (sum - offset < size) {
                    size = sum - offset;
                }
                /*使用for循环*/
                for (var i = offset; i < (offset + size); i++) {
                    result += '<li class="task-box">' +
                        ' <a href="/chat/task/receive_task?task_id='+ data[i].task_id +'" >' +
                        ' <div class="t-title">' +
                        ' <h2>' + data[i].title + '</h2> ' +
                        '</div>' +
                        ' <div class="task-details"> ' +
                        '<p> ' + data[i].content + '</p>' +
                        ' </div> ' +
                        '<div class="t-line"></div>' +
                        "<div class='t-person clearfix'> " +
                        '<span class="f_l">发布者：</span> ' +
                        '<span class="f_l name">' + data[i].nick_name + '</span>' +
                        ' <span class="f_r">' + data[i].start_time + '</span>' +
                        '</div>' +
                        '</a>' +
                        '</li>';
                }
                $('.t-bigbox').append(result);
                /*******************************************/
                /*隐藏more*/
                if ((offset + size) >= sum) {
                    //$(".load-more").hide();
                    config.isEnd = true;
                    /*停止滚动加载请求*/
                    //提示没有了
                    $(".load-more").html("没有更多啦");
                } else {
                    $(".load-more").show();
                }
            },
            error: function (xhr, type) {
                alert('Ajax 异常!');
            }
        });
    }
</script>