 	<script src="/Public/hplus/js/jquery.min.js?v=2.1.4"></script>
    <script src="/Public/hplus/js/bootstrap.min.js?v=3.3.6"></script>
    <script src="/Public/hplus/js/plugins/metisMenu/jquery.metisMenu.js"></script>
    <script src="/Public/hplus/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>
    <script src="/Public/hplus/js/plugins/layer/laydate/laydate.js"></script>
    <script src="/Public/hplus/js/plugins/layer/layer.min.js"></script>
    <script src="/Public/hplus/js/hplus.min.js?v=4.1.0"></script>
    <script type="text/javascript" src="/Public/hplus/js/contabs.min.js"></script>
    <script src="/Public/hplus/js/plugins/pace/pace.min.js"></script>
    <script src="/Public/hplus/js/plugins/jquery-ui/jquery-ui.min.js"></script>
    <script src="/Public/hplus/js/plugins/validate/jquery.validate.min.js"></script>
    <script src="/Public/hplus/js/demo/form-validate-demo.min.js"></script>
    <script src="/Public/hplus/js/plugins/peity/jquery.peity.min.js"></script>
    <script src="/Public/hplus/js/content.min.js?v=1.0.0"></script>
    <script src="/Public/hplus/js/demo/peity-demo.min.js"></script>
    <script src="/Public/hplus/js/plugins/iCheck/icheck.min.js"></script>
    <script src="/Public/hplus/js/plugins/sweetalert/sweetalert.min.js"></script>
    <script src="/Public/hplus/js/plugins/footable/footable.all.min.js"></script> 
    <script src="/Public/hplus/js/plugins/suggest/bootstrap-suggest.min.js"></script>
    <script src="/Public/hplus/js/plugins/datapicker/bootstrap-datepicker.js"></script>
    <script src="/Public/hplus/js/plugins/blueimp/jquery.blueimp-gallery.min.js"></script>
    <script src="/Public/hplus/js/plugins/sparkline/jquery.sparkline.min.js"></script>
    <script>
        //===== title样式代码开始 =====
        //data-container="body" data-toggle="popover" data-placement="bottom" data-content="内容"
        $(function (){
            // $("[data-toggle='popover']").popover();
            $("[data-toggle='popover']").popover({ trigger: "manual" , html: true, animation:false})
            .on("mouseenter", function () {
                var _this = this;   // 这里的this触发的dom,需要存起来 否则在下面 .popover的逻辑中this会变为弹出的dom
                $(this).popover("show");
                $(".popover").on("mouseleave", function () {
                    $(_this).popover('hide'); 
                });
            }).on("mouseleave", function () {
                var _this = this;
                setTimeout(function () {
                    if (!$(".popover:hover").length) {
                        $(_this).popover("hide");
                    }
                }, 1);
            });
        });
        //===== title样式代码结束 =====
    </script>
</body>
</html>