<!-- 找回密码 -->
<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<style>
.wy-header {
    height: 44px;
    border-bottom: 0px;
    position: fixed;
    left: 0;
    top: 0;
    width: 100%;
    background: #e21323;
    z-index: 100;
}
.wy-header-title {
    margin: 0 50px;
    text-align: center;
    height: 44px;
    line-height: 44px;
    font-size: 16px;
    color: #fff;
    overflow: hidden;
}
.weui-label.wy-lab{
    width: 80px;
}
</style>
<body ontouchstart>
<!--主体-->
<header class="wy-header">
 <a href="javascript:history.back(-1);" title="返回上一页" style="width: 50px;position: absolute;left: 0;top: 0;z-index: 10; height: 45px;"><div class="wy-header-icon-back"><span></span></div></a>
  <div class="wy-header-title" style="color: #fff">支付密码修改</div>
</header>
<form id="find_pass" >
    <div class="weui-content" style="margin-top: 44px;">
        <div class="weui-cells weui-cells_form wy-address-edit">
            <div class="weui-cell weui-cell_vcode">
                <div class="weui-cell__hd"><label class="weui-label wy-lab">手机号</label></div>
                <div class="weui-cell__bd"><input class="weui-input" name="phone_num" type="tel" readonly="readonly" value="<?php echo substr_replace($_SESSION['exchange']['phone_num'],'****',3,4) ?>"></div>
                <div class="weui-cell__ft"><p id="get_code" class="weui-vcode-btn">获取验证码</p></div>
            </div>
            <div class="weui-cell ">
                <div class="weui-cell__hd"><label class="weui-label wy-lab">验证码</label></div>
                <div class="weui-cell__bd"><input class="weui-input" name="phone_code" type="number" placeholder="验证码"></div>

            </div>
            <div class="weui-cell">
                <div class="weui-cell__hd"><label class="weui-label wy-lab">新支付密码</label></div>
                <div class="weui-cell__bd"><input class="weui-input" name="pay_pass" type="password" pattern="[0-9]*" placeholder="输入6位新支付密码" maxlength="6"></div>
            </div>
            <div class="weui-cell">
                <div class="weui-cell__hd"><label class="weui-label wy-lab">重复新密码</label></div>
                <div class="weui-cell__bd"><input class="weui-input" name="repay_pass" type="password" pattern="[0-9]*" placeholder="重复新密码"></div>
            </div>
        </div>
        <div id="submit_pass" class="weui-btn-area"><a href="javascript:;" class="weui-btn weui-btn_warn">确认修改</a></div>
    </div>
</form>

</body>
<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>

<script>
    $(function() {
        FastClick.attach(document.body);
    });
    var wait=60;
    function time(o) {
        if (wait == 0) {
            //o.removeAttribute("disabled");   
            o.innerHTML="重新发送";
            o.style.backgroundColor='transparent !important';
            wait = 60;
        } else { 
            o.style.backgroundColor='transparent !important';
            //o.setAttribute("disabled", true);
            o.innerHTML="重新发送(" + wait + "s)";
            wait--;
            setTimeout(function() {
                time(o)
            },1000)
        }
     }
    //获取手机验证码
    var flag = false; //防止二次提交
    $('#get_code').click(function(){
        var _this = this;
        var phone_num="<?php echo $_SESSION['exchange']['phone_num']; ?>";
        if(!phone_num){
            $.toast('请填写手机号', "cancel");return false;
        }

        if (flag) {
            return false;
        }
        flag = true;
        $.ajax({
            cache: true,
            type: "POST",
            url:"/exchange/log/send_code",
            data:{'phone_num':phone_num,'pay_pass':'pay_pass'},
            dataType: 'json',
            async: false,
            error: function(data) {
                $.toast('网络错误', "cancel");
                flag = false;
            },
            success: function(data) {      
                if (data.error == 0) {
                    time(_this);
                }else{
                    $.toast(data.msg, "cancel");
                    flag = false;
                }
            }
        });
    });

    $('#submit_pass').click(function(){
        if (!$('input[name=phone_code]').val()) {
            $.toast('请填写手机验证码', "cancel");
            return;
        }
        if (!$('input[name=pay_pass]').val() || $('input[name=pay_pass]').val().length != 6) {
            $.toast('请填写6位支付密码', "cancel");
            return;
        }
        if ($('input[name=pay_pass]').val() != $('input[name=repay_pass]').val()) {
            $.toast('两次密码不致', "cancel");
            return;
        }
        $.ajax({
            cache: true,
            type: "POST",
            url:"/exchange/member/edit_pay",
            data:$('#find_pass').serialize(),// 你的formid
            dataType: 'json',
            async: false,
            error: function(data) {
                $.toast('网络错误', "cancel");
            },
            success: function(data) {      
                if (data.error == 0) {
                    $.toast(data.msg);
                    setTimeout('window.location.href="/exchange/member"',1000);
                }else{
                    $.toast(data.msg, "cancel");
                }
            }
        });
    });
</script>