<!-- 我的共享币记录 -->
<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<style>
.wy-header {
    height: 44px;
    border-bottom: 0px;
    position: fixed;
    left: 0;
    top: 0;
    width: 100%;
    background: #e21323;
    z-index: 100;
}
.wy-header-title {
    margin: 0 50px;
    text-align: center;
    height: 44px;
    line-height: 44px;
    font-size: 16px;
    color: #fff;
    overflow: hidden;
}
</style>
<body ontouchstart>
<!--主体-->
<header class="wy-header">
   <a href="javascript:history.back(-1);" title="返回上一页" style="width: 50px;position: absolute;left: 0;top: 0;z-index: 10; height: 45px;"><div class="wy-header-icon-back"><span></span></div></a>
  <div class="wy-header-title" style="">共享币记录</div>
</header>
<div class="weui-content" style="margin-top: 44px;">
    <?php foreach($result as $v): ?>
    <div class="weui-panel">
        <div class="weui-panel__hd"><?php echo isset($v['num']) ? '<span style="color:red">共享币支出</span>' : '<span style="color:green">共享币收入</span>'; ?></div>
        <div class="weui-panel__bd">
          <div class="weui-media-box weui-media-box_text">
            <h4 class="weui-media-box__title"><em class="num"><?php echo isset($v['num']) ? $v['piao'] : $v['add_piao']; ?></em>共享币</h4>
            <p class="weui-media-box__desc">
                <?php
                    if(isset($v['num'])){ //以支出订单的数量
                        echo '在“'.$v['exchange_name'].'”兑换了'.$v['num'].'件“'.$v['goods_name'].'”。';
                    }elseif(isset($v['pay_num']) && $v['pay_num'] > 0 && $v['type'] == 1){ //以线下消费类型是1
                        echo '在“'.$v['exchange_name'].'”线下消费了'.$v['pay_num'].'元，商家赠送了您'.$v['add_piao'].'个共享币。';
                    }elseif(isset($v['pay_num']) && $v['pay_num'] == 0 && $v['type'] == 1){ //以线下消费0作为
                        echo '“'.$v['exchange_name'].'”店铺的商家无偿赠送了您'.$v['add_piao'].'个共享币。';
                    }elseif($v['type'] == 2){ //以线下消费类型是2
                        echo '在“'.$v['exchange_name'].'”活动中您获得了'.$v['add_piao'].'个共享币。';
                    }elseif($v['type'] == 3){ //以线下消费类型是3
                        echo '在“'.$v['exchange_name'].'”店铺退换货时买卖双方协商完成，商家补偿了您'.$v['add_piao'].'个共享币。';
                    }elseif($v['type'] == 4){ //以线下消费类型是4
                        echo '在“'.$v['exchange_name'].'”店铺商家响应您退换货超时，作为对商家处罚，系统返还了您'.$v['add_piao'].'个共享币。';
                    }
                ?>
            </p>
            <ul class="weui-media-box__info">
                <li class="weui-media-box__info__meta">时间：<em class="num"><?php echo $v['add_time']; ?></em></li>
                <!-- <li class="weui-media-box__info__meta weui-media-box__info__meta_extra">返现金额：￥<em class="num">500.0</em></li> -->
            </ul>
          </div>
        </div>
    </div>
    <?php endforeach; ?>
</div>
</body>

<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>
<script>
  $(function() {
    FastClick.attach(document.body);
  });
</script>