<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>在这里 - 挂号问诊</title>
    <meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no"/>
    <meta content="yes" name="apple-mobile-web-app-capable">
    <meta content="black" name="apple-mobile-web-app-status-bar-style">
    <meta content="telephone=no" name="format-detection">

    <link rel="stylesheet" href="/Public/Hospital/index/css/mui.min.css"/>
    <link rel="stylesheet" href="/Public/Hospital/index/css/swiper.min.css">
    <link rel="stylesheet" href="/Public/Hospital/index/css/font-awesome.min.css">
    <link rel="stylesheet" href="/Public/Hospital/index/css/ask.css">
    <link rel="stylesheet" href="/Public/Hospital/index/css/main.css">

    <script src="/Public/Hospital/index/js/zepto.js"></script>
    <script src="/Public/Hospital/index/js/swiper.min.js"></script>
    <script src="/Public/Hospital/index/js/main.js"></script>
    <script src="/Public/Hospital/index/js/index.js"></script>
</head>