<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<body class="re-bo-all">
<div class="regist-all">
	<div class="re-it">
		<div class="re-t">
			<a href="http://www.zzlhi.com/log/action/in?refererUrl=<?php echo $refererUrl; ?>">
                <div class="return"></div>
            </a>
			<span class="login-l">统一完善信息</span>
		</div>
		<div class="re-i">
	        <a href="" class="re-i-a">
	            <img src="/Public/Video/index/image/person.png" alt="">
	        </a>
		</div>
	</div>
    <!-- <div class="re-cen-infor">
        <p>完善信息</p>
    </div> -->
	<div class="re-body">
		<form>
			<input type="hidden" name="phone_num" value="<?php echo $_GET['phone_num']; ?>">
			<input type="text" class="re-in-tel" name="nick_name" placeholder="输入昵称">
    		<div class="re-ipb">
    			<input type="password" class="re-in-pas" name="password" placeholder="设置密码（必填）">
            	<input type="password" class="re-in-pas" name="repassword" placeholder="确认密码（必填）">
    		</div>
		</form>	
    </div>
	<div class="re-ck-but">
		<button class="re-in-but" onclick="javascript:completeReg();return false;">完成</button>
	</div>
	<div class="nav-foot">
		<div class="line-left f_l"></div>
		<div class="moddle-logo">
		    <img src="/Public/Video/index/image/bot.png" alt="">
		    <p class="big f_l">在这里</p >
		    <p class="small f_l">zzlhi.com</p >
		</div>
		<div class="line-right f_r"></div>
	</div>
</div>
<script>
	function completeReg(){
		//准备
		var data = $('form').serialize();
		var url = "/log/action/perfect";
		//发送
		$.post(url,{data:data},function(d){
			d = eval('('+ d +')');
			if(d.error){
				alert(d.msg);
				return false;
			}else{
				alert(d.msg);
				window.location.href = "/log/action/in?refererUrl=<?php echo $refererUrl; ?>";
				return false;
			}
		},'text');
	}
</script>
<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>