<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<body class="gray-bg">
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-sm-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>&nbsp;Excel&nbsp;表格批量导入会员</h5>
                        <span class="label label-primary pull-right label-primary-cust">
                            <a href="javascript:history.back(-1);" class="fa-lg-cust-a" title="返回上一页">
                                <i class="fa fa-arrow-left fa-lg-cust" aria-hidden="true"></i>
                            </a>
                        </span>
                    </div>
                    <div class="ibox-content">
                        <div class="alert alert-warning"">
                            警告：使用本功能您必须下载&nbsp;<a href="/Public/plugin/common/MembersTemplate.xls"><p class="btn btn-danger btn-xs"><i class="fa fa-download"></i>&nbsp;Excel&nbsp;模板</p></a>&nbsp;按照指定格式填写完整后通过本页面上传，否则将会出现错误，对于重复录入的数据系统导入时将会跳过。
                        </div>
                        <form class="form-horizontal m-t" action="/Business/Member/addByExcel" enctype="multipart/form-data" method="post" target="iframeUpFile">
                            <div class="form-group">
                                <label class="col-sm-3 control-label">填好的模板文件：</label>
                                <div class="col-sm-8">
                                    <input id="cname" name="file" type="file" class="form-control" required="" aria-required="true">
                                </div>
                            </div>
                            <div class="form-group form-group-bottom">
                                <div class="col-sm-2 col-sm-offset-3">
                                    <button class="btn btn-primary" type="submit">执行导入</button>
                                </div>
                            </div>
                        </form>
                        <iframe name="iframeUpFile" style="width: 0.1px;height: 0.1px;border: 1px;"></iframe>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>
<script>
    //按钮样式
    $(document).ready(function(){$(".i-checks").iCheck({checkboxClass:"icheckbox_square-green",radioClass:"iradio_square-green",})});
</script>