<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>

<style>


.footable > thead > tr > th.footable-sorted-desc > span.footable-sort-indicator:before {
     content: "\e012";
}
.footable > thead > tr > th > span.footable-sort-indicator:before {
     content: "\e022";
}
.footable > thead > tr > th.footable-sorted > span.footable-sort-indicator:before {
    content: "\e013";
}
</style>
<body class="gray-bg">
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-sm-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5><?php echo $_GET['level']?$_GET['level']:'undefined'; ?>级会员列表</h5>
                        <span class="label label-primary pull-right label-primary-cust">
                            <a href="javascript:history.back(-1);" class="fa-lg-cust-a" title="返回上一页">
                                <i class="fa fa-arrow-left fa-lg-cust"  aria-hidden="true"></i>
                            </a>
                        </span>
                    </div>
                    <div class="ibox-content">
                        <div class="row">
                            <div class="">
                                
                            </div>
                          
                        </div>
                        <div class="member-warn">
                            <div class="alert alert-warning">
                                以下为 <b><?php echo $_GET['year']?$_GET['year']:date('Y-m'); ?></b> 产生 “<b>已完成</b>” 订单的 <b><?php echo $_GET['level']?$_GET['level']:'undefined'; ?></b> 级别会员：
                            </div>
                        </div>
                        <table class="footable table table-stripped toggle-arrow-tiny" data-page-size="10" data-limit-navigation='10'>
                            <thead>
                                <tr>
                                  
                                    <th >序号</th>
                                    <th>姓名</th>
                                    <th>性别</th>
                                    <th>手机号</th>
                                    <th>级别</th>
                                    <th>生日</th>
                                    <th>入会时间</th>
                                    <th>共享币发放(本店)</th>
                                    <th>共享币发放(所有店)</th>
                                    <th>操作</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach($members as $k => $v): ?>
                                <tr> 
                                    <td><?php echo $k + 1 + $page['firstRow']; ?></td>
                                    <td><?php echo $v['name']; ?></td>
                                    <td><?php echo $v['sex']; ?></td>
                                    <td><?php echo $v['phone_num']; ?></td>
                                    <td><?php echo $v['level']; ?></td>
                                    <?php $theYearBirth = date('Y').substr($v['birth_time'],4);?>
                                    <?php if(($theYearBirth > date('Y-m-d')) && ($theYearBirth <= date('Y-m-d',time()+60*60*24*30)) && (date('Y-m-d') >= $v['birth_send_time'])): ?>
                                    <td style="color:red;"><abbr title="将在未来30天内生日，今年还未发过共享币生日福利"><i class="fa fa-info-circle"></i> <?php echo $v['birth_time']; ?></abbr></td>
                                    <?php elseif(($theYearBirth > date('Y-m-d')) && ($theYearBirth <= date('Y-m-d',time()+60*60*24*30))): ?>
                                    <td style="color:blue;cursor:help;" title="将在未来30天内生日，今年已经发过共享币生日福利"><i class="fa fa-info-circle"></i> <?php echo $v['birth_time']; ?></td>
                                    <?php else: ?>
                                    <td style="cursor:help;" title="生日不在未来30天内，明年生日前30天内可再次发放共享币福利"><i class="fa fa-info-circle"></i> <?php echo $v['birth_time']; ?></td>
                                    <?php endif; ?>
                                    <td><?php echo $v['join_time']; ?></td>
                                    <td><?php echo $v['the_piao']; ?></td>
                                    <td><?php echo $v['all_piao']; ?></td>
                                    <td>
                                        <a href="/Business/Finance/order_count_level_member_order?year=<?php echo $_GET['year']?$_GET['year']:date('Y-m'); ?>&phone_num=<?php echo $v['phone_num']; ?>">
                                            <span class="label label-primary ">兑换明细</span>
                                        </a>
                                    </td>
                                </tr>
                                <?php endforeach; ?>
                            </tbody>
                            <!-- <tfoot>
                                <tr>
                                    <td colspan="12">
                                        <div class="b-page">
                                            <?php echo $page['page']; ?>
                                        </div>
                                    </td>
                                </tr>
                            </tfoot> -->
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>

<script>
    $(document).ready(function(){
        $(".footable").footable();
        
    });
   
   
    
 
</script>