<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<body class="gray-bg">
    <div class="wrapper wrapper-content animated fadeInRight">
     <div class="ibox float-e-margins">
          <div class="ibox-title">
               <h5>销售统计（级别）</h5>
                <span class="label label-primary pull-right label-primary-cust">
                    <?php if($_GET['back'] == 'true'): ?>
                    <a href="javascript:history.back(-1);" class="fa-lg-cust-a" title="返回上一页">
                        <i class="fa fa-arrow-left fa-lg-cust"  aria-hidden="true"></i>
                    </a>
                    <?php endif; ?>
                </span> 
          </div>
          <div class="ibox-content">
            <div class="alert alert-info">
            <div class="row">
                <div class="col-sm-8">
                    <input id="year" value="<?php echo $_GET['year'] ? $_GET['year'] : date('Y-m'); ?>" class="laydate-icon form-control layer-date datepicker" style='width: 40%;margin-top: -8px; margin-right: 5px'>
                    <button type="button" class="btn btn-primary" data-container="body" onclick="javascript:enterYear();" data-toggle="popover" data-placement="left" style='padding: 5px 10px;margin-top:-3px;margin-right: 5px'>
                        查看
                    </button>
                    <button type="button" class="btn btn-success" data-container="body" onclick="javascript:enterYear('theYear');" data-toggle="popover" data-placement="left" style='padding: 5px 10px;margin-top: -3px; margin-right: 5px'>
                        当月
                    </button>
                </div>
            </div>
        </div>
        </div>
    </div>
        <div class="row">
            <a href="/Business/Finance/order_count_level_member?year=<?php echo $_GET['year'] ? $_GET['year'] : date('Y-m'); ?>&level=A">
                <div class="col-sm-3">
                    <div class="ibox">
                        <div class="ibox-content">
                            <h4>级别：A </h4>
                            <h1 class="no-margins">
                                <span><?php echo $level_A_orders; ?> 订单<br></span>
                                <span style="font-size: 14px">参与会员：<?php echo $level_A_count; ?> 人</span>
                            </h1>
                        </div>
                    </div>
                </div>
            </a>
            <a href="/Business/Finance/order_count_level_member?year=<?php echo $_GET['year'] ? $_GET['year'] : date('Y-m'); ?>&level=B">
                <div class="col-sm-3">
                    <div class="ibox">
                        <div class="ibox-content">
                            <h4>级别：B </h4>
                            <h1 class="no-margins">
                                <span><?php echo $level_B_orders; ?> 订单<br></span>
                                <span style="font-size: 14px">参与会员：<?php echo $level_B_count; ?> 人</span>
                            </h1>
                        </div>
                    </div>
                </div>
            </a>
            <a href="/Business/Finance/order_count_level_member?year=<?php echo $_GET['year'] ? $_GET['year'] : date('Y-m'); ?>&level=C">
                <div class="col-sm-3">
                    <div class="ibox">
                        <div class="ibox-content">
                            <h4>级别：C </h4>
                            <h1 class="no-margins">
                                <span><?php echo $level_C_orders; ?> 订单<br></span>
                                <span style="font-size: 14px">参与会员：<?php echo $level_C_count; ?> 人</span>
                            </h1>
                        </div>
                    </div>
                </div>
            </a>
            <a href="/Business/Finance/order_count_level_member?year=<?php echo $_GET['year'] ? $_GET['year'] : date('Y-m'); ?>&level=D">
                <div class="col-sm-3">
                    <div class="ibox">
                        <div class="ibox-content">
                            <h4>级别：D </h4>
                            <h1 class="no-margins">
                                <span><?php echo $level_D_orders; ?> 订单<br></span>
                                <span style="font-size: 14px">参与会员：<?php echo $level_D_count; ?> 人</span>
                            </h1>
                        </div>
                    </div>
                </div>
            </a>
        </div>
    </div>
</body>
<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>

<script src="/Public/hplus/js/plugins/echarts/echarts-all.js"></script>

<script>
    $('.datepicker').datepicker({  
        language: "zh-CN",
        todayHighlight: true,
        format: 'yyyy-mm',
        autoclose: true,
        startView: 'months',
        maxViewMode:'months',
        minViewMode:'months'
    });      

    function enterYear(year){
        if(year == 'theYear'){
            window.location.href = '/Business/Finance/order_count_level?year=<?php echo date('Y-m'); ?>'
        }else{
            window.location.href = '/Business/Finance/order_count_level?year=' + $('#year').val();
        }
    }
</script>