<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<style>
.modal-backdrop{
    display: none;
}
</style>

<body class="gray-bg">
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
          <div class="col-sm-12">
             <div class="ibox">
                      <div class="ibox-title">
                          <h5>退换进度</h5>
                           <span class="label label-primary pull-right label-primary-cust">
                              <a href="javascript:history.back(-1);" class="fa-lg-cust-a" title="返回上一页">
                                  <i class="fa fa-arrow-left fa-lg-cust" aria-hidden="true"></i>
                              </a>
                          </span> 
                      </div>
                      <div class="ibox-content">
                            <div class="alert alert-warning">
                                <span class="alert-link"> </span>
                                <br/>
                                <?php $xieshang_str = '申请客服结算'; ?>
                                <?php if ($order_info['return_status'] == 0): ?>
                                    <?php $jujue = 'class="btn btn-danger btn-sm  reset-btn  myModal"'; $shouli = 'class="btn btn-primary btn-sm  "'; $xieshang = 'disabled="disabled" class="btn btn-default btn-sm  "';?>
                                    买家（<?php echo $order_info['c_name']; ?>，<?php echo $order_info['phone_num']; ?>，<?php echo $order_info['address']; ?>）申请退换，理由为：“<?php echo $order_info['reason_content']; ?>”。若您48小时未受理或拒绝，系统将会全额返还共享币给买家。 
                                <?php elseif ($order_info['return_status'] == 1): ?>
                                    <?php $jujue = 'disabled="disabled" class="btn btn-default btn-sm  reset-btn  myModal"'; $shouli = 'disabled="disabled" class="btn btn-default btn-sm  "'; $xieshang = 'class="btn btn-success btn-sm  "';?>
                                    <?php if ($order_info['return_result'] == 3) {
                                         $xieshang = 'disabled="disabled" class="btn btn-success btn-sm  "';
                                         $xieshang_str = '等待客服结算';
                                    } ?>
                                    买家（<?php echo $order_info['c_name']; ?>，<?php echo $order_info['phone_num']; ?>，<?php echo $order_info['address']; ?>）申请退换，您已受理，请联系买家协商解决。当买家点击“协商完成”后您可点击下方的“申请客服结算”完成订单以获取您应得的共享币。
                                <?php elseif ($order_info['return_status'] == 2): ?>
                                    <?php $jujue = 'disabled="disabled" class="btn btn-default btn-sm  reset-btn  myModal"'; $shouli = 'disabled="disabled" class="btn btn-default btn-sm  "'; $xieshang = 'disabled="disabled" class="btn btn-default btn-sm  "';?>
                                    买家（<?php echo $order_info['c_name']; ?>，<?php echo $order_info['phone_num']; ?>，<?php echo $order_info['address']; ?>）申请退换，您已拒绝退换，理由是：“<?php echo $order_info['refuse_reason'] ?>”。当前买家可以申请客服介入或取消退换，买家取消退换将会当作“已收货”处理。
                                <?php endif ?>
                                
                                <br/>
                                <br/>
                            </div>
                            <div class="input-group col-sm-12">
                            <p>
                            您现在可以进行如下操作： 
                                    <button type="button" <?php echo $jujue; ?> style="margin-left: 30px;" data-toggle="modal" data-target="#myModal_">拒绝退换</button>
                                    <button onClick="submit_btn(1)" type="button" <?php echo $shouli; ?> style="margin-left: 30px;">受理退换</button>
                                    <button onClick="submit_btn(3)" type="button" <?php echo $xieshang; ?> style="margin-left: 30px;"><?php echo $xieshang_str; ?></button>   
                                     <div class="modal inmodal" id="myModal_" tabindex="-1" role="dialog" aria-hidden="true">
                                            <div class="modal-dialog">
                                                <div class="modal-content animated bounceInRight">
                                                    <div class="modal-header">
                                                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">关闭</span>
                                                        </button>
                                                        <h4 class="modal-title">添加拒绝理由</h4>
                                                        </div>
                                                        <div class="modal-body">  
                                                            <div class="form-group"> <input id="new_group_name" type="text" name="reason_content" placeholder="请输入拒绝理由" class="form-control"></div>
                                                        </div>
                                                        <div class="modal-footer">
                                                            <button id="close_0" type="button" class="btn btn-white" data-dismiss="modal">关闭操作</button>

                                                            <button type="button" onClick="submit_btn(2)"  class="btn btn-primary" style=" margin-bottom: 6px;">确认</button>
                                                        </div>
                                                    </div>
                                                </div>
                                      </div>
                                    
                            </p>    
                                </div>

                      </div>
                      <div class="row" style="margin-top: 20px;">
                                <div class="col-sm-6">
                                   <div class="ibox">
                                            <div class="ibox-title">
                                                <h5>商品信息</h5>
                                            </div>
                                            <div class="ibox-content">
                                               <p>商品ID：<?php echo $order_info['goods_id']; ?></p> 
                                               <p>商品名称：<?php echo $order_info['goods_name']; ?></p> 
                                               <p>商品价格：<?php echo $order_info['piao'] / $order_info['num']; ?> 共享币</p>
                                     <p>返利百分比：<?php echo $order_info['rebate'] * 100; ?>%</p>
                                               <p><?php echo $order_info['sell_business_id'] != 0 ? '代理卖家ID：'.$order_info['sell_business_id'] : '&nbsp;'; ?></p>
                                            </div>
                                   </div>
                                </div>
                                 <div class="col-sm-6">
                                   <div class="ibox">
                                            <div class="ibox-title">
                                                <h5>订单信息</h5>
                                            </div>
                                            <div class="ibox-content">
                                                <p>下单时间：<?php echo $order_info['add_time']; ?></p> 
                                                <p>订单号码：
                                                  <?php
                                                  echo $order_info['order_sn'];
                                                  if ($order_info['business_id'] == $_SESSION['business']['business_id']) {
                                                          if ($order_info['sell_business_id'] != 0) {
                                                              echo '&nbsp;<img style="cursor:pointer" src="/Public/hplus/img/blue_dai.png" title="其他商家代理的我的商品订单"> ';
                                                          }
                                                      }else{
                                                          $imgs = '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;';
                                                          if ($order_info['sell_business_id'] == $_SESSION['business']['business_id']) {
                                                              echo '&nbsp;<img style="cursor:pointer" src="/Public/hplus/img/red_dai.png" title="我代理的其他商家的商品订单"> ';
                                                          }
                                                      }
                                                  ?>
                                                </p>
                                                <?php $str_status = array('1'=>'待提货','2'=>'待发货','3'=>'待收货','4'=>'已完成','5'=>'已取消','6'=>'退换中','7'=>'已退货'); $str_return_status = array('0'=>'未受理','1'=>'已受理','2'=>'已拒绝');?>
                                                <p>兑换数量：<?php echo $order_info['num']; ?></p>
                                                <p>支付共享币：<?php echo $order_info['piao']; ?> 个</p>
                                                <p>订单状态：<?php echo $str_status[$order_info['status']]; ?><sapn class="text-danger"><?php if ($order_info['status'] == 6){echo '（'.$str_return_status[$order_info['return_status']].'）';}; ?></sapn></p>
                                            </div>
                                   </div>
                                </div>
                                </div>
                      
                      
         
             </div>
          </div>
        </div>
        
    </div>
</body>

<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>

<script>
    $(".myModal").click(function(){
        $('.modal-dialog').css('top',$(document).scrollTop())
    })
    $('.myModal').modal({
        keyboard: false,
        backdrop:false,
        show:false
    });

    function submit_btn(status){
        var reason_content = $('input[name=reason_content]').val();
        var order_id = <?php echo $_GET['order_id']; ?>;
        if (!order_id) {
            swal('参数错误','','warning');
            return false;
        }
        if (status == 2 && !reason_content) {
            swal('请输入拒绝理由','','warning');
            return false;
        }
        $.ajax({
            cache: true,
            type: "POST",
            url:"/Business/Finance/return_status",
            data:{'order_id':order_id,'status':status,'reason_content':reason_content},
            dataType: 'json',
            async: false,
            error: function(data) {
               swal('网络错误，请重试！', "", "warning");
            },
            success: function(data) {
                if (data.error == 0) {
                    swal(data.msg, "", "success");
                    setTimeout("window.location.reload();",1000);
                }else{
                    swal(data.msg, "", "warning");
                }
            }
        });
    };


</script>