<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>

<!-- 主界面 头部 具体展示内容 -->
<div class="main-all">
    <div class="home-slide">
        <div id="mui-slider" class="mui-slider" >
            <div class="mui-slider-group mui-slider-loop">
                <!--支持循环-->
                <div class="mui-slider-item mui-slider-item-duplicate"><a href="<?php echo end($carousel)['url'];?>"><img src="<?php echo end($carousel)['pic_path'];?>" /></a></div>
                <?php foreach($carousel as $v): ?>
                <div class="mui-slider-item"><a href="<?php echo $v['url'];?>"><img src="<?php echo $v['pic_path'];?>" /></a></div>
                <?php endforeach; ?>
                <!--支持循环-->
                <div class="mui-slider-item mui-slider-item-duplicate"><a href="<?php echo reset($carousel)['url'];?>"><img src="<?php echo reset($carousel)['pic_path'];?>" /></a>
                </div>
            </div>
            <div class="mui-slider-indicator">
                <div class="mui-indicator mui-active"></div>
                <?php for($i=1;$i<count($carousel);$i++): ?>
                <div class="mui-indicator"></div>
                <?php endfor; ?>
            </div>
        </div>
    </div>
</div>
<!-- 搜索框 -->
<div class="main-search">
    <form method="get" action="/video/video/search">
        <input type="search" name="keywords" class="main-s" placeholder="搜索">
    </form>
</div>
<!-- 电影院 -->
<div class="main-vid main-v-mar">
    <div class="main-vid-title">
        <span class="vid-ti-o"></span>
        <span class="vid-ti-t">电影院</span>
    </div>
    
    <div class="main-igte">
        <a href="/video/video/play?video_id=<?php echo reset($dy)['video_id']; ?>" class="main-igte-a">
            <div class="igte-contain">
        <div class="igte-contain-top">
                <img src="<?php echo reset($dy)['pic_path']; ?>" alt="" class="igte-contain-i">
          </div>
                <div class="igte-contain-box">
                <p class="igte-t-t"><?php echo mb_substr(reset($dy)['name'],0,20); ?>
                </p> 
                <p class="igte-t-cen"><?php echo mb_substr(reset($dy)['synopsis'],0,45); ?> ....</p>
                <p class="igte-t-bot"><?php echo reset($dy)['class_name']; ?>&nbsp;&nbsp;&nbsp;赞<?php echo reset($dy)['zan_num']; ?></p>
                </div>
            </div>
        </a>
    </div>
    <!-- 分割线 -->
    <div class="cut-off"></div>
    <div class="main-vid-slide">
        <div class="mui-slider">
            <div class="mui-slider-group">
                <?php for($i=1;$i<count($dy);$i++): ?>
                <div class="mui-slider-item">
                    <a href="/video/video/play?video_id=<?php echo $dy[$i]['video_id']; ?>" class="main-vid-slide-a">
                        <img src="<?php echo $dy[$i]['pic_path']; ?>" />
                        <div class="mui-st-text">
                            <p class="mui-st-top"><?php echo mb_substr($dy[$i]['name'],0,15); ?></p>
                            <p class="mui-st-cen"><?php echo mb_substr($dy[$i]['synopsis'],0,30); ?> ....</p>
                            <p class="mui-st-bot"><?php echo $dy[$i]['class_name']; ?>&nbsp;&nbsp;&nbsp;赞<?php echo $dy[$i]['zan_num']; ?></p>
                        </div>
                    </a>
                </div>
                <?php endfor; ?>
             </div>
        </div>
    </div>
    <div class="cut-off"></div>
</div>
<!-- 以下尺寸未量 -->
<!-- tab 分类 -->
<div class="main-tab">
    <div class="main-t-top">
        <a href="javascript:;" class="main-t-top-active">推荐</a>
        <?php foreach($type as $v): ?>
        <a href="/video/video/list?type_id=<?php echo $v['type_id']; ?>"><?php echo $v['type_name']; ?></a>
        <?php endforeach; ?>
    </div>
    <div class="main-vid">
    <div class="cut-off"></div>
        <div class="main-igte">
            <a href="/video/video/play?video_id=<?php echo reset($level)['video_id']; ?>" class="main-igte-a">
                <div class="igte-contain">
                    <div class="igte-contain-top">
                        <img src="<?php echo reset($level)['pic_path']; ?>" alt="" class="igte-contain-i">
                    </div>
                    <div class="igte-contain-box">
                        <p class="igte-t-t"><?php echo mb_substr(reset($level)['name'],0,20); ?></p> 
                        <p class="igte-t-cen"><?php echo mb_substr(reset($level)['synopsis'],0,45); ?> ....</p>
                        <p class="igte-t-bot"><?php echo reset($level)['class_name']; ?>&nbsp;&nbsp;&nbsp;<?php echo reset($level)['level']; ?>星&nbsp;&nbsp;&nbsp;赞<?php echo reset($level)['zan_num']; ?></p>
                    </div>
                </div>
            </a>
        </div>
        <div class="cut-off"></div>
        <?php for($i=1;$i<count($level);$i++): ?>
        <a href="/video/video/play?video_id=<?php echo $level[$i]['video_id']; ?>" class="index-all-it">
            <div class="main-t-tbot">
                <div class="t-tbot-le fl">
                    <p class="mui-st-top"><?php echo mb_substr($level[$i]['name'],0,10); ?></p>
                    <p class="mui-st-cen"><?php echo mb_substr($level[$i]['synopsis'],0,18); ?> ....</p>
                    <p class="mui-st-bot"><?php echo $level[$i]['class_name']; ?>&nbsp;&nbsp;&nbsp;<?php echo $level[$i]['level']; ?>星&nbsp;&nbsp;&nbsp;赞<?php echo $level[$i]['zan_num']; ?></p>
                </div>
                <div class="t-tbot-ri">
                    <img src="<?php echo $level[$i]['pic_path']; ?>" alt="" class="tbot-ri-img fr">
                </div>
            </div>
        </a>
        <div class="cut-off"></div>
        <?php endfor; ?>
    </div>
</div>
<!-- top10 -->
<div class="main-vid">
    <div class="main-vid-title">
        <span class="vid-ti-o"></span>
        <span class="vid-ti-t">TOP10</span>
    </div>
    <?php for($i=0;$i<3;$i++): ?>
    <div class="main-igte">
        <a href="/video/video/play?video_id=<?php echo $top10[$i]['video_id']; ?>" class="main-igte-a">
            <div class="igte-contain">
                <div class="igte-contain-top">
                    <img src="<?php echo $top10[$i]['pic_path']; ?>" alt="" class="igte-contain-i">
                </div>
                <div class="igte-contain-box">
                    <p class="igte-t-t"><?php echo mb_substr($top10[$i]['name'],0,20); ?></p> 
                    <p class="igte-t-cen"><?php echo mb_substr($top10[$i]['synopsis'],0,45); ?> ....</p>
                    <p class="igte-t-bot"><?php echo $top10[$i]['class_name']; ?>&nbsp;&nbsp;&nbsp;赞<?php echo $top10[$i]['zan_num']; ?></p>
                </div>
            </div>
        </a>
    </div>
    <div class="cut-off"></div>
    <?php endfor; ?>
    <div class="main-vid-slide">
        <div class="mui-slider">
            <div class="mui-slider-group">
                <?php for($i=3;$i<count($top10);$i++): ?>
                <div class="mui-slider-item">
                    <a href="/video/video/play?video_id=<?php echo $top10[$i]['video_id']; ?>" class="main-vid-slide-a">
                        <img src="<?php echo $top10[$i]['pic_path']; ?>" />
                        <div class="mui-st-text">
                            <p class="mui-st-top"><?php echo mb_substr($top10[$i]['name'],0,15); ?></p>
                            <p class="mui-st-cen"><?php echo mb_substr($top10[$i]['synopsis'],0,25); ?> ....</p>
                            <p class="mui-st-bot"><?php echo $top10[$i]['class_name']; ?>&nbsp;&nbsp;&nbsp;赞<?php echo $top10[$i]['zan_num']; ?></p>
                        </div>
                    </a>
                </div>
                <?php endfor; ?>
            </div>
        </div>
    </div>
<div class="cut-off"></div>
</div>
<!-- 电影 -->
<div class="main-vid main-v-mar">
    <div class="main-vid-title">
        <span class="vid-ti-o"></span>
        <span class="vid-ti-t">电影</span>
    </div>
    
    <div class="main-igte">
        <a href="/video/video/play?video_id=<?php echo reset($dy)['video_id']; ?>" class="main-igte-a">
            <div class="igte-contain">
        <div class="igte-contain-top">
                <img src="<?php echo reset($dy)['pic_path']; ?>" alt="" class="igte-contain-i">
          </div>
                <div class="igte-contain-box">
                <p class="igte-t-t"><?php echo mb_substr(reset($dy)['name'],0,20); ?></p> 
                <p class="igte-t-cen"><?php echo mb_substr(reset($dy)['synopsis'],0,45); ?> ....</p>
                <p class="igte-t-bot"><?php echo reset($dy)['class_name']; ?>&nbsp;&nbsp;&nbsp;赞<?php echo reset($dy)['zan_num']; ?></p>
                </div>
            </div>
        </a>
    </div>
    <!-- 分割线 -->
    <div class="cut-off"></div>
    <div class="main-vid-slide">
        <div class="mui-slider">
            <div class="mui-slider-group">
                <?php for($i=1;$i<count($dy);$i++): ?>
                <div class="mui-slider-item">
                    <a href="/video/video/play?video_id=<?php echo $dy[$i]['video_id']; ?>" class="main-vid-slide-a">
                        <img src="<?php echo $dy[$i]['pic_path']; ?>" />
                        <div class="mui-st-text">
                            <p class="mui-st-top"><?php echo mb_substr($dy[$i]['name'],0,15); ?></p>
                            <p class="mui-st-cen"><?php echo mb_substr($dy[$i]['synopsis'],0,30); ?> ....</p>
                            <p class="mui-st-bot"><?php echo $dy[$i]['class_name']; ?>&nbsp;&nbsp;&nbsp;赞<?php echo $dy[$i]['zan_num']; ?></p>
                        </div>
                    </a>
                </div>
                <?php endfor; ?>
             </div>
        </div>
    </div>
    <div class="cut-off"></div>
</div>
<!-- 电视剧 -->
<div class="main-vid main-v-mar">
    <div class="main-vid-title">
        <span class="vid-ti-o"></span>
        <span class="vid-ti-t">电视剧</span>
    </div>
    
    <div class="main-igte">
        <a href="/video/video/play?video_id=<?php echo reset($dsj)['video_id']; ?>" class="main-igte-a">
            <div class="igte-contain">
        <div class="igte-contain-top">
                <img src="<?php echo reset($dsj)['pic_path']; ?>" alt="" class="igte-contain-i">
          </div>
                <div class="igte-contain-box">
                <p class="igte-t-t"><?php echo mb_substr(reset($dsj)['name'],0,20); ?></p> 
                <p class="igte-t-cen"><?php echo mb_substr(reset($dsj)['synopsis'],0,45); ?> ....</p>
                <p class="igte-t-bot"><?php echo reset($dsj)['class_name']; ?>&nbsp;&nbsp;&nbsp;赞<?php echo reset($dsj)['zan_num']; ?></p>
                </div>
            </div>
        </a>
    </div>
    <!-- 分割线 -->
    <div class="cut-off"></div>
    <div class="main-vid-slide">
        <div class="mui-slider">
            <div class="mui-slider-group">
                <?php for($i=1;$i<count($dsj);$i++): ?>
                <div class="mui-slider-item">
                    <a href="/video/video/play?video_id=<?php echo $dsj[$i]['video_id']; ?>" class="main-vid-slide-a">
                        <img src="<?php echo $dsj[$i]['pic_path']; ?>" />
                        <div class="mui-st-text">
                            <p class="mui-st-top"><?php echo mb_substr($dsj[$i]['name'],0,15); ?></p>
                            <p class="mui-st-cen"><?php echo mb_substr($dsj[$i]['synopsis'],0,30); ?> ....</p>
                            <p class="mui-st-bot"><?php echo $dsj[$i]['class_name']; ?>&nbsp;&nbsp;&nbsp;赞<?php echo $dsj[$i]['zan_num']; ?></p>
                        </div>
                    </a>
                </div>
                <?php endfor; ?>
             </div>
        </div>
    </div>
    <div class="cut-off"></div>
</div>
<!-- 综艺 -->
<div class="main-vid main-v-mar">
    <div class="main-vid-title">
        <span class="vid-ti-o"></span>
        <span class="vid-ti-t">综艺</span>
    </div>
    
    <div class="main-igte">
        <a href="/video/video/play?video_id=<?php echo reset($zy)['video_id']; ?>" class="main-igte-a">
            <div class="igte-contain">
        <div class="igte-contain-top">
                <img src="<?php echo reset($zy)['pic_path']; ?>" alt="" class="igte-contain-i">
          </div>
                <div class="igte-contain-box">
                <p class="igte-t-t"><?php echo mb_substr(reset($zy)['name'],0,20); ?></p> 
                <p class="igte-t-cen"><?php echo mb_substr(reset($zy)['synopsis'],0,45); ?> ....</p>
                <p class="igte-t-bot"><?php echo reset($zy)['class_name']; ?>&nbsp;&nbsp;&nbsp;赞<?php echo reset($zy)['zan_num']; ?></p>
                </div>
            </div>
        </a>
    </div>
    <!-- 分割线 -->
    <div class="cut-off"></div>
    <div class="main-vid-slide">
        <div class="mui-slider">
            <div class="mui-slider-group">
                <?php for($i=1;$i<count($zy);$i++): ?>
                <div class="mui-slider-item">
                    <a href="/video/video/play?video_id=<?php echo $zy[$i]['video_id']; ?>" class="main-vid-slide-a">
                        <img src="<?php echo $zy[$i]['pic_path']; ?>" />
                        <div class="mui-st-text">
                            <p class="mui-st-top"><?php echo mb_substr($zy[$i]['name'],0,15); ?></p>
                            <p class="mui-st-cen"><?php echo mb_substr($zy[$i]['synopsis'],0,30); ?> ....</p>
                            <p class="mui-st-bot"><?php echo $zy[$i]['class_name']; ?>&nbsp;&nbsp;&nbsp;赞<?php echo $zy[$i]['zan_num']; ?></p>
                        </div>
                    </a>
                </div>
                <?php endfor; ?>
             </div>
        </div>
    </div>
    <div class="cut-off"></div>
</div>
<!-- 新闻 -->
<div class="main-vid main-v-mar">
    <div class="main-vid-title">
        <span class="vid-ti-o"></span>
        <span class="vid-ti-t">新闻</span>
    </div>
    
    <div class="main-igte">
        <a href="/video/video/play?video_id=<?php echo reset($xw)['video_id']; ?>" class="main-igte-a">
            <div class="igte-contain">
        <div class="igte-contain-top">
                <img src="<?php echo reset($xw)['pic_path']; ?>" alt="" class="igte-contain-i">
          </div>
                <div class="igte-contain-box">
                <p class="igte-t-t"><?php echo mb_substr(reset($xw)['name'],0,20); ?></p> 
                <p class="igte-t-cen"><?php echo mb_substr(reset($xw)['synopsis'],0,45); ?> ....</p>
                <p class="igte-t-bot"><?php echo reset($xw)['class_name']; ?>&nbsp;&nbsp;&nbsp;赞<?php echo reset($xw)['zan_num']; ?></p>
                </div>
            </div>
        </a>
    </div>
    <!-- 分割线 -->
    <div class="cut-off"></div>
    <div class="main-vid-slide">
        <div class="mui-slider">
            <div class="mui-slider-group">
                <?php for($i=1;$i<count($xw);$i++): ?>
                <div class="mui-slider-item">
                    <a href="/video/video/play?video_id=<?php echo $xw[$i]['video_id']; ?>" class="main-vid-slide-a">
                        <img src="<?php echo $xw[$i]['pic_path']; ?>" />
                        <div class="mui-st-text">
                            <p class="mui-st-top"><?php echo mb_substr($xw[$i]['name'],0,15); ?></p>
                            <p class="mui-st-cen"><?php echo mb_substr($xw[$i]['synopsis'],0,30); ?> ....</p>
                            <p class="mui-st-bot"><?php echo $xw[$i]['class_name']; ?>&nbsp;&nbsp;&nbsp;赞<?php echo $xw[$i]['zan_num']; ?></p>
                        </div>
                    </a>
                </div>
                <?php endfor; ?>
             </div>
        </div>
    </div>
    <div class="cut-off"></div>
</div>
<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>