<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<style>
.wy-header {
    height: 44px;
    border-bottom: 0px;
    position: fixed;
    left: 0;
    top: 0;
    width: 100%;
    background: #e21323;
    z-index: 100;
}
.wy-header-title {
    margin: 0 50px;
    text-align: center;
    height: 44px;
    line-height: 44px;
    font-size: 16px;
    color: #fff;
    overflow: hidden;
}
.weui-label.wy-lab{
    width: 80px;
}
</style>
<body ontouchstart>
<!--主体-->
    <header class="wy-header">
        <a href="javascript:history.back(-1);" title="返回上一页" style="width: 50px;position: absolute;left: 0;top: 0;z-index: 10; height: 45px;"><div class="wy-header-icon-back"><span></span></div></a>
        <div class="wy-header-title" style="">登录密码修改</div>
    </header>
    <div class="weui-content" style="margin-top: 44px;">
        <form id="repassword">
            <div class="weui-cells weui-cells_form wy-address-edit">
                <div class="weui-cell ">
                    <div class="weui-cell__hd"><label class="weui-label wy-lab">原密码</label></div>
                    <div class="weui-cell__bd"><input class="weui-input" name="old_password" type="password" placeholder="请输入原密码"></div>
                </div>
                <div class="weui-cell ">
                    <div class="weui-cell__hd"><label class="weui-label wy-lab">新密码</label></div>
                    <div class="weui-cell__bd"><input class="weui-input" name="password" type="password" placeholder="请输入新密码"></div>
                </div>
                <div class="weui-cell ">
                    <div class="weui-cell__hd"><label class="weui-label wy-lab">重复新密码</label></div>
                    <div class="weui-cell__bd"><input class="weui-input" name="repassword" type="password" placeholder="重复新密码"></div>
                </div>
            </div>
            <div id="submit_pass" class="weui-btn-area"><a href="javascript:;" class="weui-btn weui-btn_warn">确认修改</a></div>
        </form>
    </div>
</body>
<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>
<script>
  $(function() {
    FastClick.attach(document.body);
  });

  $('#submit_pass').click(function(){
        if (!$('input[name=old_password]').val()) {
            $.toast('请输入原密码', "cancel");
            return;
        }
        if (!$('input[name=password]').val()) {
            $.toast('请填写新密码', "cancel");
            return;
        }
        if ($('input[name=password]').val() != $('input[name=repassword]').val()) {
            $.toast('两次新密码不致', "cancel");
            return;
        }
        if (confirm('修改密码后会重新登录，是否修改？')) {
            $.ajax({
                cache: true,
                type: "POST",
                url:"/exchange/member/repassword",
                data:$('#repassword').serialize(),// 你的formid
                dataType: 'json',
                async: false,
                error: function(data) {
                    $.toast('网络错误', "cancel");
                },
                success: function(data) {      
                    if (data.error == 0) {
                        window.location.href="/exchange/log/in?b="+data.business_id+"&phone_num="+data.phone_num;
                    }else{
                        $.toast(data.msg, "cancel");
                    }
                }
            });  
        }
        
    });
</script>

