<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<style>
.wy-header {
    height: 44px;
    border-bottom: 0px;
    position: fixed;
    left: 0;
    top: 0;
    width: 100%;
    background: #e21323;
    z-index: 100;
}
.wy-header-title {
    margin: 0 50px;
    text-align: center;
    height: 44px;
    line-height: 44px;
    font-size: 16px;
    color: #fff;
    overflow: hidden;
}
.weui-panel__hd:after {
    content: " ";
    position: absolute;
    left: 0;
    bottom: 0;
    right: 0;
    height: 1px;
     border-bottom: none; 
    color: #e5e5e5;
    -webkit-transform-origin: 0 100%;
    transform-origin: 0 100%;
    -webkit-transform: scaleY(.5);
    transform: scaleY(.5);
    left: 15px;
}
</style>
<body ontouchstart>
<header class="wy-header" style="position:fixed; top:0; left:0; right:0; z-index:200;">
 <a href="javascript:history.back(-1);" title="返回上一页" style="width: 50px;position: absolute;left: 0;top: 0;z-index: 10; height: 45px;"><div class="wy-header-icon-back"><span></span></div></a>
  <div class="wy-header-title" style="">申请退货</div>
</header>
<div class='weui-content' style="margin-top: 44px;">
  
  <div class="weui-media-box__bd  pd-10" style="background: #fff;margin-bottom: 5px;">
            <div class="weui-media-box_appmsg ord-pro-list">
              <div class="weui-media-box__hd"><a href="javascript:;"><img class="weui-media-box__thumb" src="<?php echo $order_info['pic']; ?>" alt=""></a></div>
              <div class="weui-media-box__bd" style="height: 82px;">
                <h1 class="weui-media-box__desc"><a href="javascript:;" class="ord-pro-link"><?php echo $order_info['goods_name']; ?></a></h1>
                <p class="weui-media-box__desc">备注：<span><?php echo $order_info['message']; ?></span></p>
              </div>
            </div>       
  </div>
  <div class="weui-panel__hd" style="background: #fff ;border-bottom: none;"><span style="color: #000;">退换原因：</span><span></span></div>
  	<div class="weui-cells weui-cells_radio" style="margin-top: 0;padding: 14px 15px 10px;color: #666;font-size: 13px;position: relative;">
      <label class="weui-cell weui-check__label" id="x11" >
        <div class="weui-cell__bd" style="">
          <p>未收到商品</p>
        </div>
        <div class="weui-cell__ft">
          <input type="radio" class="weui-check" name="radio1"  checked="checked">
          <span class="weui-icon-checked" ></span>
        </div>
      </label>
      <label class="weui-cell weui-check__label" id="x12" >
        <div class="weui-cell__bd" >
          <p>商品质量问题</p>
        </div>
        <div class="weui-cell__ft">
          <input type="radio" name="radio1" class="weui-check"  >
          <span class="weui-icon-checked" ></span>
        </div>
      </label>
      <label class="weui-cell weui-check__label" id="x13">

        <div class="weui-cell__bd" >
          <p>其他</p>
        </div>
        <div class="weui-cell__ft">
          <input type="radio" name="radio1" class="weui-check"  >
          <span class="weui-icon-checked" ></span>
        </div>
      </label>
      <div class="weui-cell" style="padding: 2px 0px 10px 14px;">
        <div class="weui-cell__bd"  style="border: 1px solid #d9d9d9;">
          <textarea class="weui-textarea" placeholder="请输入您的退换原因" rows="3" id='x14'></textarea>
        </div>
      </div>
    </div>
     <div class="weui-panel__hd" style="background: #fff ;margin-top: 5px;"><span style="color: #000;">应退共享币：</span><span style="color: red"><?php echo $order_info['piao']; ?> 共享币</span></div>
     <div class="weui-btn-area">
    <a class="weui-btn weui-btn_warn" href="javascript:;" id="showTooltips">提交</a>
  </div>
</div>



</body>
<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>
<script>
  
    $(function() {
        FastClick.attach(document.body);
        
    });
    $('#x11').attr('reason','1');
    $('#x11').attr('reasonSize','1');
    $('#x12').attr('reasonSize','2');
    $('#x13').attr('reasonSize','3');
     $('#x14').attr('disabled','true')
    $('#x11').click(function () {
    	$('#x12').attr('reason','0');
    	$('#x13').attr('reason','0');
        $(this).attr('reason','1');
        $('#x14').attr('disabled')
    });
  $('#x12').click(function () {
    	$('#x11').attr('reason','0');
    	$('#x13').attr('reason','0');
        $(this).attr('reason','1');
        $('#x14').attr('disabled','true')
        
    });
$('#x13').click(function () {
    	$('#x12').attr('reason','0');
    	$('#x11').attr('reason','0');
        $(this).attr('reason','1');
        $('#x14').removeAttr('disabled');

    });
</script> 
<script>
    $('#showTooltips').click(function (){
        var order_id = <?php echo $_GET['order_id'] ?>;
        if (!order_id) {
            $.toast("参数错误", "cancel");
            return false;
        }
        var reason = $('label[reason=1]').attr('reasonSize');
        var content = $.trim($('#x14').val());
        if (reason == 3 && !content) {
            $.toast("请输入您的退换原因", "cancel");
            return false;
        }
        $.confirm("商家会尽快和您联系，如果商家联系您之后，您长时间没有回复将自动完成该笔订单！","您确定要进行此操作吗?", function() {
            $.ajax({
                cache: true,
                type: "POST",
                url:"/exchange/member/return_goods",
                data:{'order_id':order_id,'reason':reason,'content':content},
                dataType: 'json',
                async: false,
                error: function(data) {
                    $.toast("网络错误", "cancel");
                },
                success: function(data) {
                    if (data.error == 0) {
                        $.toast("已提交申请");
                        setTimeout('window.location.href="/Exchange/Member/myorders?status=6"',1000);
                    }else{
                        $.toast(data.msg, "cancel");
                    }
                    
                }
            });
            
        }, function() {
          //取消操作
        });
    });
    

    </script>
