<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>

<style>
.good-img{
	width: 50px;
	height: 50px;
	display: block;
}
table{
    font-size: 13px;
}
.footable-row-detail-name {
    display: table-cell;
    font-weight: bold;
    padding-right: 0.5em;
    line-height: 30px;
    min-width: 80px;
}
</style>

<body class="gray-bg">
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-sm-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>编辑分组</h5>
                         <span class="label label-primary pull-right label-primary-cust">
                            <a href="javascript:history.back(-1);" class="fa-lg-cust-a" title="返回上一页">
                                <i class="fa fa-arrow-left fa-lg-cust" aria-hidden="true"></i>
                            </a>
                        </span> 
                    </div>
                    <div class="ibox-content">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="input-group col-sm-12">
                                    <form method="get" action="/business/goods/group_detail" class="clearfix pull-left" >
                                        <input type="hidden" name="group_id" value="<?php echo $_GET['group_id']; ?>">
                                        <select name="goods_type_id" class="input-sm form-control input-s-sm inline sex-select " style="width: 15%;margin-right: 10px;">
                                            <option value="0">商品类型</option>
                                            <option disabled="true">--------------------</option>
                                            <?php foreach($goods_type as $v): ?>
                                            <option <?php echo $_GET['goods_type_id'] == $v['goods_type_id'] ? 'selected' : ''; ?> value="<?php echo $v['goods_type_id']; ?>"><?php echo $v['goods_type_name']; ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                        <select name="is_gx" class="input-sm form-control input-s-sm inline sex-select " style="width: 15%;margin-right: 10px;">
                                            <option value="0">共享状态</option>
                                            <option disabled="true">--------------------</option>
                                            <option <?php echo $_GET['is_gx'] == 1 ? 'selected' : ''; ?> value="1">是</option>
                                            <option <?php echo $_GET['is_gx'] == 2 ? 'selected' : ''; ?> value="2">否</option>
                                        </select>
                                        <select name="status" class="input-sm form-control input-s-sm inline sex-select " style="width: 15%;margin-right: 10px;">
                                            <option value="0">上架状态</option>
                                            <option disabled="true">--------------------</option>
                                            <option <?php echo $_GET['status'] == 1 ? 'selected' : ''; ?> value="1">上架</option>
                                            <option <?php echo $_GET['status'] == 2 ? 'selected' : ''; ?> value="2">下架</option>
                                        </select>
                                        <input type="text" name="keywords" value="<?php echo $_GET['keywords'] ? $_GET['keywords'] : ''; ?>" placeholder="商品名称关键字" class="input-sm form-control pull-left col-sm-4" style="width:30%;" >
                                        <span class="input-group-btn pull-left " >
                                            <button type="submit" class="btn btn-sm btn-primary search-btn"> 搜索</button>
                                        </span>
                                    </form>
                                    <button type="button" onclick="javascript:window.location.href = '/business/goods/group_detail?group_id=<?php echo $_GET['group_id']; ?>';" class="btn btn-danger btn-sm  reset-btn pull-left" style="margin-left: 34px;">刷新</button>
                                </div>
                            </div>
                        </div>
                        <div class="member-warn">
                            <div class="alert alert-warning">
                                本分组共有商品： <span class="alert-link"><?php echo $count; ?></span> 种
                                <?php if($_GET['goods_type_id'] > 0 || $_GET['is_gx'] > 0 || $_GET['status'] > 0 || !empty($_GET['keywords'])): ?>
                                ，以下为搜索&nbsp;&nbsp;
                                <?php if($_GET['goods_type_id'] > 0): ?>
                                商品类型是 “<span class="alert-link"><?php echo $goods_type[$_GET['goods_type_id'] - 1]['goods_type_name']; ?></span>”&nbsp;&nbsp;
                                <?php endif; ?>
                                <?php if($_GET['is_gx'] > 0): ?>
                                共享状态是 “<span class="alert-link"><?php echo $_GET['is_gx'] == 1 ? '是' : '否'; ?></span>”&nbsp;&nbsp;
                                <?php endif; ?>
                                <?php if($_GET['status'] > 0): ?>
                                上架状态是 “<span class="alert-link"><?php echo $_GET['status'] == 1 ? '上架' : '下架'; ?></span>”&nbsp;&nbsp;
                                <?php endif; ?>
                                <?php if(!empty($_GET['keywords'])): ?>
                                商品名称包含 “<span class="alert-link"><?php echo $_GET['keywords']; ?></span>”&nbsp;&nbsp;
                                <?php endif; ?>
                                的商品，共 <span class="alert-link"><?php echo $where_count; ?></span> 种
                                <?php endif; ?>
                            </div>
                        </div>
                        <table class="footable table table-stripped toggle-arrow-tiny" data-page-size="10000">
                            <thead>
                                <tr>
                                    <th>序号</th>
                                    <th>商品名</th>
                                    <th>商品图</th>
                                    <th>商品类型</th>
                                    <th>兑换价格（共享币）</th>
                                    <th data-hide="all">库存</th>
                                    <th >上架状态</th>
                                    <th>是否共享</th>
                                    <th data-hide="all">销售返利</th>
                                    <th data-hide="all">商品描述</th>
                                    <th>操作</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach($goods as $k => $v): ?>
                                <tr> 
                                    <td><?php echo str_pad(($k + 1 + $page['firstRow']),strlen(count($goods)),"0",STR_PAD_LEFT); ?></td>
                                    <td data-container="body" data-toggle="popover" data-placement="bottom" data-content="<?php echo $v['goods_name']; ?>"><?php echo $v['business_id'] != $business_id ? '<img data-container="body" data-toggle="popover" data-placement="bottom" data-content="我代理其他商家的商品" src="/Public/hplus/img/red_dai.png">' : '&nbsp;&nbsp;&nbsp;&nbsp;'; ?>&nbsp;<?php echo mb_substr($v['goods_name'],0,15); if(strlen($v['goods_name']) > 15) echo ' ....'; ?></td>
                                    <td><img src="<?php echo explode(';',$v['pics'])[0]; ?>" alt="" class="good-img"></td>
                                    <td><?php echo $goods_type[$v['goods_type_id'] - 1]['goods_type_name']; ?></td>
                                    <td><?php echo $v['piao']; ?> 个</td>
                                    <td><?php echo $v['nums']; ?></td>
                                    <td class="show_status"><?php echo $v['status'] == 1 ? '<span class="text-success">上架</span>' : '<span class="text-muted">下架</span>'; ?></td>
                                    <td class="show_gx"><?php echo $v['is_gx'] == 1 ? '是' : '否'; ?></td>
                                    <td><?php echo $v['rebate'] * 100; ?> %</td>
                                    <td><?php echo $v['description'];?></td>
                                    <td>
                                         <a href="javascript:;">
                                            <span class="label label-danger del_goods" goods_id="<?php echo $v['goods_id']; ?>">删除</span>
                                        </a>
                                    </td>
                                </tr>
                                <?php endforeach; ?>
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td colspan="12">
                                        <div class="b-page">
                                            <?php echo $page['page']; ?>
                                        </div>
                                    </td>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>

<script>
    $(document).ready(function(){$(".footable").footable({
        pagination: false
    });});

    $('.del_goods').click(function(){
        var _this = $(this);
        var goods_id = _this.attr('goods_id');
        var group_id = <?php echo $_GET['group_id']; ?>;
        swal({
            title: "您确定要从本组中删除该商品吗？",
            text: "",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "是的，我要删除！",
            cancelButtonText: "让我再考虑一下…",
            closeOnConfirm: false,
            closeOnCancel: true
        },
        function(isConfirm) {
            if (isConfirm) {
                $.ajax({
                    cache: true,
                    type: "POST",
                    url:"/Business/Goods/group_goods_delete",
                    data:{'good_id':goods_id,'group_id':group_id},
                    dataType: 'json',
                    async: false,
                    error: function(data) {
                       swal('网络错误，请重试！', "", "warning");
                    },
                    success: function(data) {
                        if (data.error == 0) {
                            _this.parents('tr').remove();
                            swal("商品已删除！", "", "success");
                        }else{
                            swal(data.msg, "", "error");
                        }
                    }
                });
                
            }
        })
    })
</script>