<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>

<style>
    .content-list{
        display: inline-block;
    }
    .cont-list-s{
        font-weight: 700;
    }
    .extend-i-img{
        margin:0 30px 0 0;
        display: inline-block;
    }
    .float-e-margins-extend-extend{
        height: 234px;
    }
    .ibox-content-r{
        height: 191px;
        padding-top: 73px;
    }
    .containt-pad{
        padding: 0 10px;
    }
    .extend-i-img2{
    position: absolute;
    left: 50%;
    margin-left: -250px;
    top: 50%;
    margin-top: -250px;
    }
   .remark{
    position: absolute;
    line-height: 30px;
    margin-top: 12px;
    top: 60px;
    left: 13px;
   }
</style>

<body class="gray-bg">
<div class="bg-click" style="width: 100%;height: 100%;background: rgba(0,0,0,0.7);position: fixed;z-index: 5000;display: none;"></div>
<div class="wrapper wrapper-content animated fadeInRight">
        <div class="row" style="min-width: 870px;">
            <div class="col-sm-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>我的商城信息</h5>
                    </div>
                    <div class="ibox-content clearfix">
                        <div class="well " style="line-height: 150px;min-height: 130px;width:100%;float: left;margin-bottom: 0;">
                            <img src="" id="qrcode" title="点击放大" class="extend-i-img col-sm-2" style="height: 90px;width: 90px;float: left;cursor: pointer;margin: 10px 20px 0px 0px;padding: 0px;"/>
                            <div class="input-group  col-sm-4" style="height: 90px;float: left;line-height: 90px;width: 370px;">
                                    <input type="text" class="form-control" id="ext-input" value="" readonly="true" style="top:35px;"> 
                                    <p class="remark"><i class="fa fa-info-circle"></i> 您积分商城的推广方式，置于微信公众号菜单处效果更佳。</p>
                                    <span class="input-group-btn"> 
                                        <button type="button" class="btn btn-primary extend-copy" style="top:10px;" onClick="javascript:copyTest();">复制链接</button> 
                                    </span>
                            </div>
                            <div class="col-sm-3 pull-right">
                                <div class="ibox float-e-margins" style="margin-top: -5px;margin-bottom: 0;">
                                    <div class="ibox-title">
                                        <h4>我的商品总数</h4>
                                    </div>
                                    <div class="ibox-content">
                                        <h2 class="no-margins"><?php echo $goodNum; ?> 个</h2>
                                    </div>
                                </div>
                            </div>
                        <div class="col-sm-3 pull-right">
                            <div class="ibox float-e-margins" style="margin-top: -5px;margin-bottom: 0;">
                                <div class="ibox-title">
                                    <h4>我代理的商品数</h4>
                                </div>
                                <div class="ibox-content">
                                    <h2 class="no-margins"><?php echo $agentNum; ?> 个</h2>
                                </div>
                            </div>
                        </div>  
                        </div>
                                
                         
                    </div>
                </div>
                </div>
            </div>
			  <div class="row" style="min-width: 870px;">
            <div class="col-sm-3">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>共享状态饼状图</h5>
                    </div>
                    <div class="ibox-content">
                        <div class="echarts" id="echarts-share-chart"></div>
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>上架状态饼状图</h5>
                    </div>
                    <div class="ibox-content">
                        <div class="echarts" id="echarts-ground-chart"></div>
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>商品类别柱状图</small></h5>
                    </div>
                    <div class="ibox-content">
                        <div class="echarts" id="echarts-bar-chart"></div>
                    </div>
                </div>
            </div>
        </div>
        </div>
      
    </div>
</body>

<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>

<script src="/Public/hplus/js/plugins/echarts/echarts.common.min.js"></script>
<script type="text/javascript" src="/Public/plugin/qrcode/jquery.qrcode.min.js"></script>

<script>
    //赋值链接
    var domain = document.domain;
    $("#ext-input").val('http://' + domain + '/exchange?b=<?php echo $business_id; ?>');
    //赋值二维码
    $('#qrcode').attr('src',"http://api.qrserver.com/v1/create-qr-code/?data=http://" + domain + "/exchange?b=<?php echo $business_id; ?>&size=90x90");
    //点击复制
    function copyTest(){
        $("#ext-input").select();
        document.execCommand("copy");
        swal("复制成功",'快去粘贴到需要的地方进行推广吧','success');
    }
</script>

<script>
$(function(){
    //点击二维码
    $('.ibox-content').delegate("#qrcode","click",function(){
        $('.bg-click').html( '<img id="qrcode2" class="extend-i-img2"/>');
        $('#qrcode2').attr('src',"http://api.qrserver.com/v1/create-qr-code/?data=http://" + domain + "/exchange?b=<?php echo $business_id; ?>&size=500x500")
        $('.bg-click').show();

    });
    $('body').delegate(".bg-click","click",function(){
        $(this).hide();
    });
    //共享统计图
	var l = echarts.init(document.getElementById("echarts-share-chart")),
	u = {
        tooltip: {
            trigger: 'item',
            formatter: "{a} <br/>{b}: {c} ({d}%)"
        },
        legend: {
            orient: 'vertical',
            x: 'left',
            data:["共享", "非共享"]
        },
        series: [
            {
                name:'共享/非共享',
                type:'pie',
                radius: ['0%', '70%'],
                avoidLabelOverlap: false,
                label: {
                    normal: {
                        show: false,
                        position: 'center'
                    }
                },
                labelLine: {
                    normal: {
                        show: false
                    }
                },
                data:[{
                    value: <?php echo $gxNum[1]; ?>,
                    name: "共享商品数"
                }, {
                    value: <?php echo $gxNum[2]; ?>,
                    name: "非共享商品数"
                }]
            }
        ],
        color: ['rgb(255,127,80)','rgb(135,206,250)','rgb(50,205,50)']

    };
    //上架统计图
    l.setOption(u), $(window).resize(l.resize);
    var ground = echarts.init(document.getElementById("echarts-ground-chart")),
    groundM = {
        title: {
            text: "",
            subtext: "",
            x: "center"
        },
        tooltip: {
            trigger: "item",
            formatter: "{a} <br/>{b} : {c} ({d}%)"
        },
        legend: {
            orient: "vertical",
            x: "left",
            data: ["上架", "非上架"]
        },
        calculable: !0,
        series: [{
            name: "上架/非上架",
            type: "pie",
            label: {
                normal: {
                    show: false,
                    position: 'center'
                },
                emphasis: {
                    show: false,
                    textStyle: {
                        fontSize: '30',
                        fontWeight: 'bold'
                    }
                }
            },
            labelLine: {
                normal: {
                    show: false
                }
            },
            radius: ['0%', '70%'],
            data: [{
                value: <?php echo $statusNum[1]; ?>,
                name: "上架商品数"
            }, {
                value: <?php echo $statusNum[2]; ?>,
                name: "非上架商品数"
            }]
        }],
        color: ['rgb(255,127,80)','rgb(135,206,250)','rgb(50,205,50)']

    };
	ground.setOption(groundM), $(window).resize(ground.resize);
    //类别统计图
	var t = echarts.init(document.getElementById("echarts-bar-chart")),
    n = {
        title: {
            text: ""
        },
        tooltip: {
            trigger: "axis"
        },
        legend: {
            data: ["商品类别"],
            x: "right"
        },
        grid: {
            x: 30,
            x2: 40,
            y2: 24
        },
        calculable: !0,
        xAxis: [{
            type: "category",
            data: [<?php echo $goodsType['name']; ?>]
        }],
        yAxis: [{
            type: "value"
        }],
        series: [{
            name: "商品数",
            type: "bar",
            data: [<?php echo $goodsType['value']; ?>],
            markPoint: {
                data: [{
                    type: "max",
                    name: "最大值"
                }, {
                    type: "min",
                    name: "最小值"
                }]
            },
            markLine: {
                data: [{
                    type: "average",
                    name: "平均值"
                }]
            }
        }],
    color: ['rgb(255,127,80)','rgb(135,206,250)','rgb(50,205,50)']

    };
    t.setOption(n), window.onresize = t.resize;
})	
</script>
