<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<?php require_once MODULE_PATH.'/View/Common/menu.phtml'; ?>

<section class="Hui-article-box">
    <nav class="breadcrumb"><i class="Hui-iconfont">&#xe67f;</i> <a href="/Hospitaladmin">首页</a>
        <span class="c-gray en">&gt;</span>
        <a href="/Hospitaladmin/advice/list">问诊管理</a>
        <span class="c-gray en">&gt;</span>
        问诊列表<a class="btn btn-success radius r" style="line-height:1.6em;margin-top:3px" href="javascript:location.replace(location.href);" title="刷新" ><i class="Hui-iconfont">&#xe68f;</i></a>
    </nav>
    <div class="Hui-article">
        <article class="cl pd-20">
            <div class="text-c">
                <form method="post" action="/Hospitaladmin/advice/list">
                    <!-- <input type="text" onfocus="WdatePicker({maxDate:'#F{$dp.$D(\'datemax\')||\'%y-%M-%d\'}'})" id="datemin" class="input-text Wdate" style="width:120px;">
                    -
                    <input type="text" onfocus="WdatePicker({minDate:'#F{$dp.$D(\'datemin\')}',maxDate:'%y-%M-%d'})" id="datemax" class="input-text Wdate" style="width:120px;"> -->
                    <select class="select-box inline" name="department_id">
                        <option value="">选择科室</option>
                        <?php foreach($department as $v): ?>
                        <option value="<?php echo $v['department_id']; ?>"><?php echo $v['department_name'] ;?></option>
                        <?php endforeach; ?>
                    </select>
                    <input type="text" class="input-text" style="width:250px" placeholder="问诊关键字" id="" name="advice_comment">
                    <button type="submit" class="btn btn-success" id="" name=""><i class="Hui-iconfont">&#xe665;</i> 搜索</button>
                </form>
            </div>
            <div class="cl pd-5 bg-1 bk-gray mt-20">
                <!-- <span class="l"> --> 
                    <!-- <a href="javascript:;" onclick="datadel()" class="btn btn-danger radius"><i class="Hui-iconfont">&#xe6e2;</i> 批量删除</a> -->
                    <!-- <a href="/Videoadmin/video/add" class="btn btn-primary radius"><i class="Hui-iconfont">&#xe600;</i> 添加</a> -->
                <!-- </span> -->
                <span class="r">共有问诊：<strong><?php echo $count; ?></strong> 个，已经回复：<strong style="color: green;"><?php echo $replyNum;?></strong> 个，未回复：<strong style="color: red;"><?php echo $count-$replyNum; ?></strong> 个</span>
            </div>
            <table class="table table-border table-bordered table-bg">
                <thead>
                    <tr class="text-c">
                        <!-- <th width="25"><input type="checkbox" name="" value=""></th> -->
                        <th width="40">序号</th>
                        <th width="300">问题</th>
                        <th width="90">问诊人</th>
                        <th width="50">年龄</th>
                        <th width="50">性别</th>
                        <th width="60">科室</th>
                        <th width="60">针对医生</th>
                        <th width="80">有无回复</th>
                        <th width="130">提问时间</th>
                        <th width="50">操作</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($res as $k => $v): ?>
                    <tr class="text-c">
                        <td><?php echo $k + 1 + $page['firstRow']; ?></td>
                        <td><?php echo mb_substr($v['advice_comment'],0,32); ?>....</td>
                        <td><?php echo $v['is_hidename'] ? '<font color="#ddd">匿名用户</font>' : $v['nick_name']; ?></td>
                        <td><?php echo $v['age']?></td>
                        <td><?php echo $v['sex'] ? '男' : '女'; ?></td>
                        <td><?php echo $v['department_name']; ?></td>
                        <td><?php echo $v['doctor_name']; ?></td>
                        <td><?php echo $v['is_reply'] ? '<font color="green">已回复</font>' : '<font color="red">未回复</font>'; ?></td>
                        <td><?php echo $v['send_time'];?></td>
                        <td class="td-manage">
                            <!-- <a style="text-decoration:none" onClick="admin_stop(this,'10001')" href="javascript:;" title="停用"><i class="Hui-iconfont">&#xe631;</i></a> -->
                            <a title="回复" href="/Hospitaladmin/Advice/reply?advice_id=<?php echo $v['advice_id']; ?>"  class="ml-5" style="color:#008cba">回复</a>
                            <!-- <a title="删除" href="javascript:;" onclick="admin_del(this,'1')" class="ml-5" style="text-decoration:none"><i class="Hui-iconfont">&#xe6e2;</i></a> -->
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
            <div class="b-page">
                <?php echo $page['page']; ?>
            </div>
        </article>
    </div>
</section>
<!--请在下方写此页面业务相关的脚本--> 
<script type="text/javascript" src="/Public/Common/Admin/lib/My97DatePicker/4.8/WdatePicker.js"></script> 
<script type="text/javascript" src="/Public/Common/Admin/lib/datatables/1.10.0/jquery.dataTables.min.js"></script> 
<script type="text/javascript" src="/Public/Common/Admin/lib/laypage/1.2/laypage.js"></script> 
<script type="text/javascript">
/*
    参数解释：
    title   标题
    url     请求的url
    id      需要操作的数据id
    w       弹出层宽度（缺省调默认值）
    h       弹出层高度（缺省调默认值）
*/
/*管理员-增加*/
function admin_add(title,url,w,h){
    layer_show(title,url,w,h);
}
/*管理员-删除*/
function admin_del(obj,id){
    alert('删除功能在开发中');
    return false;
    
    layer.confirm('确认要删除吗？',function(index){
        //此处请求后台程序，下方是成功后的前台处理……

        $(obj).parents("tr").remove();
        layer.msg('已删除!',{icon:1,time:1000});
    });
}

/*管理员-停用*/
function admin_stop(obj,id){
    layer.confirm('确认要停用吗？',function(index){
        //此处请求后台程序，下方是成功后的前台处理……
        
        $(obj).parents("tr").find(".td-manage").prepend('<a onClick="admin_start(this,id)" href="javascript:;" title="启用" style="text-decoration:none"><i class="Hui-iconfont">&#xe615;</i></a>');
        $(obj).parents("tr").find(".td-status").html('<span class="label label-default radius">已禁用</span>');
        $(obj).remove();
        layer.msg('已停用!',{icon: 5,time:1000});
    });
}

/*管理员-启用*/
function admin_start(obj,id){
    layer.confirm('确认要启用吗？',function(index){
        //此处请求后台程序，下方是成功后的前台处理……
        
        $(obj).parents("tr").find(".td-manage").prepend('<a onClick="admin_stop(this,id)" href="javascript:;" title="停用" style="text-decoration:none"><i class="Hui-iconfont">&#xe631;</i></a>');
        $(obj).parents("tr").find(".td-status").html('<span class="label label-success radius">已启用</span>');
        $(obj).remove();
        layer.msg('已启用!', {icon: 6,time:1000});
    });
}
</script>
<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>