<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<?php require_once MODULE_PATH.'/View/Common/menu.phtml'; ?>
<section class="Hui-article-box" style="overflow: auto;">
<nav class="breadcrumb"><i class="Hui-iconfont">&#xe67f;</i> <a href="/Hospitaladmin">首页</a>
    <span class="c-gray en">&gt;</span>
    <a href="/Hospitaladmin/advice/list">问诊管理</a>
    <span class="c-gray en">&gt;</span>
    <a href="/Hospitaladmin/advice/list">问诊列表</a> <span class="c-gray en">&gt;</span>
    当前问题 <a class="btn btn-success radius r" style="line-height:1.6em;margin-top:3px" href="javascript:location.replace(location.href);" title="刷新" ><i class="Hui-iconfont">&#xe68f;</i></a>
</nav>
<div class="cl pd-5 bg-1 bk-gray mt-20">
    <span class="l" style="margin-left: 15px;">
    患者名称：<?php echo $theAdvice['is_hidename'] ? '匿名患者' : $theAdvice['nick_name']; ?>，年龄：<?php echo $theAdvice['age']; ?>岁，性别：<?php echo $theAdvice['sex'] ? '男' : '女';?>，咨询科室：<?php echo $theAdvice['department_name']; ?>，咨询医生：<?php echo $theAdvice['doctor_name']; ?>，发起时间：<?php echo $theAdvice['send_time']; ?>
    </span>
</div>
<form action="/Hospitaladmin/advice/reply" method="post" style="left: -80px;position: relative;" class="form form-horizontal">
    <div class="row cl">
        <div class="formControls col-xs-8 col-sm-9 cl pd-5 bg-1 bk-gray mt-20" style="margin-left: 115px;width: 825px;float: left;width: 50%;background-color: #EFEBEB;border-radius: 10px">
            <span><b><?php echo $theAdvice['is_hidename'] ? '匿名患者' : $theAdvice['nick_name']; ?></b>：<?php echo $theAdvice['advice_comment']; ?></span>
            <br>
            <span style="float: right;font-size: 10px;color: #868484"><?php echo $theAdvice['send_time']; ?></span>
            <br><br>
            <?php foreach(explode('#', $theAdvice['images']) as $v): ?>
            <a target="_blank" href="<?php echo $v; ?>">
                <img width="100" src="<?php echo $v; ?>">
            </a>
            <?php endforeach; ?>
        </div>
        <?php foreach($theAdviceReply as $v): ?>
        <div class="formControls col-xs-8 col-sm-9 cl pd-5 bg-1 bk-gray mt-20" style="margin-left: <?php  echo $v['doctor_id'] > 0 ? '340px' : '115px'; ?>;width: 825px;float: left;width: 50%;background-color: <?php echo $v['doctor_id'] > 0 ? '#76E476' : '#EFEBEB'; ?>;border-radius: 10px">
            <span><b><?php echo $v['doctor_id'] > 0 ? $theAdvice['doctor_name'] : ($theAdvice['is_hidename'] ? '匿名患者' : $theAdvice['nick_name']); ?></b>：<?php echo $v['reply_comment']; ?></span>
            <br>
            <span style="float: right;font-size:10px;color:#868484"><?php echo $v['send_time']; ?></span>
        </div>
        <?php endforeach; ?>
    </div>
    <div class="row cl">
        <div class="formControls col-xs-8 col-sm-9" style="margin-left:100px;width:855px;">
            <input type="hidden" name="doctor_id" value="<?php echo $theAdvice['doctor_id']; ?>">
            <input type="hidden" name="advice_id" value="<?php echo $theAdvice['advice_id']; ?>">
            <textarea class="textarea" name="reply_comment" placeholder="回复内容..."></textarea>
        </div>
    </div>
    <div style="margin-bottom:100px;margin-left:-270px;margin-top:20px;">
        <div class="col-xs-8 col-sm-9 col-xs-offset-4 col-sm-offset-3">
            <input class="btn btn-primary radius" type="submit" value="提交">
        </div>
    </div>
</form>
</section>
<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>