<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>

<style>
	.sure-right{
		float: right;
		margin-right: 9%;
	}
	#match_phone_num-error{
		display: none;
	}
</style>
<body class="gray-bg">
<div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-sm-12">
                <div class="ibox float-e-margins">
                 <div class="ibox-title">
                            <h5>发放共享币（录营业额）</h5>  
                    </div>
                    <div class="ibox-content">
                        <div class="alert alert-warning alert-dismissable">
                            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                            警告：我们系统将会依据您在本页面录入的每一笔会员在您实体店内的消费记录，来产生对应的报表统计数据。
                        </div>
                    	<div class="alert alert-danger">
                            <?php $security = $security * 10; ?>
                            提示：您现在共有共享币 <span class="alert-link"><?php echo $piao+$security; ?></span> 个<?php echo $security > 0 ? "（含保证金 {$security} 个）" : ''; ?>，发放给会员您将被扣除相应的共享币。
                        </div>
                        <form class="form-horizontal m-t" id="commentForm">
                          	 <div class="form-group">
                                <label class="col-sm-3 control-label">手机号：</label>
                                <div class="col-sm-8">
                                    <input class="form-control" id="match_phone_num" name="phone_num" placeholder="输入 3 位将自动匹配"  type="text">
                                    <div class="col-sm-12 test_data_div" >
                                        <ul  id="test_data_ul" >
                                        </ul>
                                    </div>
                                </div>
                            </div>
							<div class="form-group">
                                <label class="col-sm-3 control-label">消费金额（元）：</label>
                                <div class="col-sm-8">
                                    <input id="monetary" placeholder="会员在您实体店内消费的金额" name="pay_num" minlength="1" type="number" class="form-control" aria-required="true">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">发放共享币数：</label>
                                <div class="col-sm-8">
                                    <input id="cone_send" placeholder="请输入数字" name="add_piao" min="0" minlength="1" type="number" class="form-control"  aria-required="true" onkeyup="this.value=this.value.replace(/\D/g,'')" onafterpaste="this.value=this.value.replace(/\D/g,'')">
                                </div>
                            </div>
                            <div class="form-group date-hide">
                                <label class="col-sm-3 control-label">日期：</label>
                                <div class="col-sm-8">
                                    <input id="hello" name="add_time" value="<?php echo date('Y-m-d'); ?>" class="laydate-icon form-control layer-date">
                                </div>
                            </div>
                            <div class="form-group form-group-bottom">
                                <div class="sure-right">
                                    <p class="btn btn-danger" onclick="javascript:enterSend();">确定发放</p>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>
<script type="text/javascript">
//动态搜索手机号
var listText="";
$('#match_phone_num').bind('keyup',function(){
    if (!$('#match_phone_num').val()){
        $("#test_data_ul").html("");
    }
	if ($('#match_phone_num').val().length >= 3){
		//ajax获取用户电话添加
		var url = "/Business/Member/piao_send";
		var match_phone_num = $('#match_phone_num').val();
		$.ajax({
			url : url,
			data:{match_phone_num:match_phone_num},
			type:'get',
			dataType:'json',
			success:function(data){
                listText="";
				for (let i = 0; i < data.res.length; i++) {
					listText+='<li>'+data.res[i].phone_num+'</li>';
				}
				$("#test_data_ul").html(listText);
				if ($('#match_phone_num').val().length>=11) {
					$(".test_data_div").hide();
				}else{
					$(".test_data_div").show().css({
				 	top:$("#match_phone_num").offset().top-$("#match_phone_num").height,
				 	position:'absolute',
		     		zIndex:100
				    })
				}
		 	}
		})
	}
})
$(document).bind('click',function(){
	$(".test_data_div").hide();
})
$("#test_data_ul").delegate('li',"click",function(){
	var val = $(this).text();
	$('#match_phone_num').val(val);
})
//确定发放共享币
function enterSend(){
	swal({
        title: "确定给该用户发放共享币吗？您将被扣除相应的共享币？",
        text: "",
        type: "warning",
        showCancelButton: true,
        confirmButtonColor: "#DD6B55",
        confirmButtonText: "是的，我要发放！",
        cancelButtonText: "让我再考虑一下…",
        closeOnConfirm: false,
        closeOnCancel: true
        },
        function(isConfirm) {
            if (isConfirm) {
                $.post('/Business/Member/piao_send',$('form').serialize(),function(d){
        			if(d.error){
        				 swal(d.msg, "", "error");
        				return false;
        			}else{
        		      	swal(d.msg, "", "success");
                        setTimeout("window.location.reload();",1000);
        			}
		        },'json');          
            }
        }
    )
}
</script>
<script>
	laydate({elem:"#hello",event:"focus"});
</script>