<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<body class="re-bo-all">
<div class="regist-all">
	<div class="re-it">
		<div class="re-t">
			<a href="/log/action/in?refererUrl=<?php echo $refererUrl; ?>">X</a>
			<span>统一账号注册</span>
		</div>
		<div class="re-i">
			<img src="/Public/Video/index/image/logo.png" alt="">
		</div>
	</div>
	<div class="re-body">	
		<input type="text" class="re-in-tel" id="phone_num" placeholder="手机号码(+86)">
		<div class="re-ipb">
			<input type="text" id="sms_code" class="re-in-pas" placeholder="验证码">
			<button id="send_sms" onclick="javascript:sendSMS();return false;" class="but-pas">发送验证码</button>
		</div>
		<div class="re-check">
			<input type="checkbox" value="" checked="true" disabled="true" class="re-check-in">
			<span>我已阅读并同意用户注册协议</span>
		</div>
	</div>
	<div class="re-ck-but">
		<input type="button" id="next" onclick="javascript:checkSMS();return false;" class="re-in-but" style="color: #fff" value="NEXT>">
	</div>
	<div class="margin-body"></div>
	<div class="nav-foot">
		<div class="line-left f_l"></div>
		<div class="moddle-logo">
		    <img src="/Public/Video/index/image/bot.png" alt="">
		    <p class="big f_l">在这里</p >
		    <p class="small f_l">zzlhi.com</p >
		</div>
		<div class="line-right f_r"></div>
	</div>
</div>
<script type="text/javascript">
	function sendSMS(){
		//准备
		var phone_num = $('#phone_num').val();
		var url = "/log/action/getSmsCode";
		//发送
		$.post(url,{phone_num:phone_num},function(d){
			d = eval('('+ d +')');
			if(d.error){
				alert(d.msg);
				return false;
			}else{
				alert(d.msg);
				$('#send_sms').attr('disabled','true');
				return false;
			}
		},'text');
		//禁用
		$('#send_sms').attr('disabled','true');
		//倒计时
		var time = 60;
		setInterval(function(){
			if(time > 0){
				$('#send_sms').text(time + '秒');
				time --;
			}else if(time == 0){
				$('#send_sms').removeAttr('disabled');
				$('#send_sms').text('重新发送');
				time = -1;
			}else{
				return false;
			}
		},1000);
	}
	function checkSMS(){
		//准备
		var sms_code = $('#sms_code').val();
		var phone_num = $('#phone_num').val();
		var url = "/log/action/checkSmsCode?do=reg";
		//发送
		$.post(url,{sms_code:sms_code,phone_num:phone_num},function(d){
			d = eval('('+ d +')');
			if(d.error){
				alert(d.msg);
				return false;
			}else{
				window.location.href = "/log/action/perfect?refererUrl=<?php echo $refererUrl; ?>&phone_num=" + d.phone_num;
				return false;
			}
		},'text');
	}
</script>
<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>