<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<body class="re-bo-all">
<div class="regist-all">
	<div class="re-it">
		<div class="re-t">
			<a href="/log/action/in?refererUrl=<?php echo $refererUrl; ?>">
                <div class="return"></div>
            </a>
			<span class="login-l">统一重设密码</span>
		</div>
	</div>
	<div class="re-body">
		<form>
			<input type="hidden" name="phone_num" value="<?php echo $_GET['phone_num']; ?>">
			<input type="text" class="re-in-tel" disabled="true" value="<?php echo $_GET['phone_num']; ?>">
    		<div class="re-ipb">
    			<input type="password" class="re-in-pas" name="password" placeholder="新密码（必填）">
            	<input type="password" class="re-in-pas" name="repassword" placeholder="确认新密码（必填）">
    		</div>
		</form>	
    </div>
	<div class="re-ck-but">
		<button class="re-in-but" onclick="javascript:reSetPassword();return false;">提交</button>
	</div>
	<div class="nav-foot">
		<div class="line-left f_l"></div>
	 	<div class="moddle-logo">
		    <img src="/Public/Video/index/image/bot.png" alt="">
		    <p class="big f_l">在这里</p >
		    <p class="small f_l">zzlhi.com</p >
		</div>
		<div class="line-right f_r"></div>
	</div>
</div>


<script>
	function reSetPassword(){
		//准备
		var data = $('form').serialize();
		var url = "/log/action/reSetPassword";
		//发送
		$.post(url,{data:data},function(d){
			d = eval('('+ d +')');
			if(d.error){
				alert(d.msg);
				return false;
			}else{
				alert(d.msg);
				window.location.href = "/log/action/in?refererUrl=<?php echo $refererUrl; ?>";
				return false;
			}
		},'text');
	}
</script>
<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>