<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<body>
<div class="container">
    <div class="chatheader clearfix">
        <a href="#" class="fa fa-angle-left"></a><span>最近联系人</span> <a href="#" class="server "><img
            src="/Public/Chat/index/images/server.png" alt=""></a>
    </div>
    <ul class="r-centacts-list">
    <?php foreach ($recent as $key => $value): ?>
        
        <li class="list-content">
            <a href="/Chat/Alone/chat_content?member_id=<?php echo $value['member_id'] ?>">
                <div class="r-cent-l">
                    <div class="l-img">
                        <img src="<?php echo $value['headimg']; ?>" alt="">
                    </div>

                    <div class="mid-centent">
                        <div class="mid-t-title clearfix">
                            <h2><?php echo $value['nick_name']; ?></h2>
                            <div class="right-time">
                                <?php echo $value['last_send_time']; ?>
                            </div>
                        </div>

                        <p class="p-chat-cont">
                            <?php echo $value['last_content']; ?>
                        </p>
                    </div>

                </div>
                <div class="del-right">
                    <i class="">删除</i>
                </div>
            </a>
        </li>
        
    <?php endforeach ?>
    </ul>

</div>

</body>
<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>

<script>
    //侧滑显示删除按钮
    var expansion = null; //是否存在展开的list
    var container = document.querySelectorAll('.r-centacts-list li a');
    for (var i = 0; i < container.length; i++) {
        var x, y, X, Y, swipeX, swipeY;
        container[i].addEventListener('touchstart', function (event) {
            x = event.changedTouches[0].pageX;
            y = event.changedTouches[0].pageY;
            swipeX = true;
            swipeY = true;
            if (expansion) {   //判断是否展开，如果展开则收起
                expansion.className = "";
            }
        });
        container[i].addEventListener('touchmove', function (event) {

            X = event.changedTouches[0].pageX;
            Y = event.changedTouches[0].pageY;
            // 左右滑动
            if (swipeX && Math.abs(X - x) - Math.abs(Y - y) > 0) {
                // 阻止事件冒泡
                event.stopPropagation();
                if (X - x > 10) {   //右滑
                    event.preventDefault();
                    this.className = "";    //右滑收起
                }
                if (x - X > 10) {   //左滑
                    event.preventDefault();
                    this.className = "swipeleft";   //左滑展开
                    expansion = this;
                }
                swipeY = false;
            }
            // 上下滑动
            if (swipeY && Math.abs(X - x) - Math.abs(Y - y) < 0) {
                swipeX = false;
            }
        });
    }
    //控制字数
    var pChatCont=document.querySelectorAll(".p-chat-cont")
    for (var i=0;i<pChatCont.length;i++){
        var txt=$(pChatCont[i]).text().trim();
        var len=txt.length;
        if(len>16){
            var txt=txt.substring(0,16);
            $(pChatCont[i]).text(txt+"...");
        }else {
            $(pChatCont[i]).text(txt);
        }
    }
</script>