<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<body class="gray-bg">
    <div class="wrapper wrapper-content">
       <div class="row">
         
            <div class="col-sm-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>活动公告</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link " title='点击可收起公告'>
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            
                        </div>
                    </div>
                    <div class="ibox-content ">
                        <div class="carousel slide" id="carousel2">
                            <ol class="carousel-indicators">
                                <li data-slide-to="0" data-target="#carousel2" class="active"></li>
                                <li data-slide-to="1" data-target="#carousel2"></li>
                                <li data-slide-to="2" data-target="#carousel2" class=""></li>
                            </ol>
                            <div class="carousel-inner">
                                <div class="item active">
                                    <img alt="image" class="img-responsive banner-busindex" src="/Public/hplus/img/p_big1.jpg">
                                   
                                </div>
                                <div class="item ">
                                    <img alt="image" class="img-responsive banner-busindex" src="/Public/hplus/img/p_big3.jpg">
                                   
                                </div>
                                <div class="item">
                                    <img alt="image" class="img-responsive banner-busindex" src="/Public/hplus/img/p_big2.jpg">
                                   
                                </div>
                            </div>
                            <a data-slide="prev" href="carousel.html#carousel2" class="left carousel-control">
                                <span class="icon-prev"></span>
                            </a>
                            <a data-slide="next" href="carousel.html#carousel2" class="right carousel-control">
                                <span class="icon-next"></span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>

        </div>
          <div class="row">
            <div class="col-sm-4">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h3>会员总数</h3>
                    </div>
                    <div class="ibox-content">
                        <h2 class="no-margins"><?php echo $result['countNum']; ?> 人</h2>
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h3>今日营收</h3>
                    </div>
                    <div class="ibox-content">
                        <h2 class="no-margins"><?php echo $result['countToday']; ?> 元</h2>
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <a href="/Business/Finance/recharge?back=true">
                            <span class="label label-danger pull-right">充值</span>
                        </a>
                        <a href="/Business/Finance/withdraw?back=true">
                            <span class="label label-primary pull-right">提现</span>
                        </a>
                        <h3>共享币余额</h3>
                    </div>
                    <div class="ibox-content">
                        <?php $result['info']['security'] = $result['info']['security'] * 10; ?>
                        <h2 class="no-margins"><?php echo $result['info']['piao']+$result['info']['security']; ?> 个<span style="font-size: 16px"><?php echo $result['info']['security']>0?'（含保证金 '.$result['info']['security'].' 个）':''; ?><span></h2>
                    </div>
                </div>
            </div>
          
        </div>
        <div class="row">
            <div class="col-sm-4">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <a href="/Business/Center/info?back=true"><span class="label label-info pull-right">查看</span></a>
                        <h3>商户资料</h3>
                    </div>
                    <div class="ibox-content heightsize">
                        <p>商户号码: <span style="color:red;"><?php echo $result['info']['business_id']; ?></span></p>
                        <p>法人姓名: <span><?php echo $result['info']['legal_name']; ?></span></p>
                        <p>法人手机: <span><?php echo $result['info']['phone_num']; ?></span></p>
                        <p>激活状态: <span><?php echo $result['info']['status']; ?></span></p>
                        <p>行业类别: <span><?php echo $result['info']['profession']; ?></span></p>
                        <p>上次登录: <span><?php echo $result['info']['last_login']; ?></span></p>
                        <p>注册时间: <span><?php echo $result['info']['add_time']; ?></span></p>
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <a href="/Business/Finance/capital_info?back=true"><span class="label label-info pull-right">查看</span></a>
                        <h3>业务信息</h3>
                    </div>
                    <div class="ibox-content heightsize">
                        <p>推荐获得奖励: <span><?php echo $result['sumRewardPiao']?$result['sumRewardPiao']:0; ?> 个共享币（共 <?php echo $result['unLeaderNum']; ?> 人）</span></p>
                        <p>共为会员发放: <span><?php echo $result['give_piao']?$result['give_piao']:0; ?> 个共享币</span></p>
                        <p>代理别店获利: <span><?php echo $result['rebate_piao']?$result['rebate_piao']:0; ?> 个共享币</span></p>
                        <p>被别店代理得: <span><?php echo $result['agent_piao']?$result['agent_piao']:0; ?> 个共享币</span></p>
                        <p>自营商品收入: <span><?php echo $result['sale_piao']?$result['sale_piao']:0; ?> 个共享币</span></p>
                        <p>累计充值金额: <span><?php echo $result['recharge_piao']?$result['recharge_piao']:0; ?> 个共享币</span></p>
                        <p>累计提现金额: <span><?php echo $result['withdrawals_piao']?$result['withdrawals_piao']:0; ?> 个共享币</span></p>
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <a href="/Business/Center/placard?back=true"><span class="label label-info pull-right">查看</span></a>
                        <h3>最新公告</h3>
                    </div>
                    <div class="ibox-content heightsize">
                        <?php foreach($result['placard'] as $v): ?>
                        <a href="/Business/Center/placard_detail?placard_id=<?php echo $v['placard_id']; ?>">
                            <p><?php echo $v['placard_title']; ?><span class="pull-right">[<?php echo $v['add_time']; ?>] </span></p>
                        </a> 
                        <?php endforeach; ?>
                    </div>
                </div>
            </div>
           
        </div>
   

    </div>

</body>
<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>

