<div class="nav-foot">
    <div class="line-left f_l"></div>
    <div class="moddle-logo">
        <img src="/Public/Index/index/images/bot.png" alt="">
        <p class="big f_l">在这里</p>
        <p class="small f_l">zzlhi.com</p>
        <br>
		<p style="width: 3.5rem;font-size: 0.35rem;margin-left: -0.2rem;margin-top:-0.3rem;">京ICP备17015319号</p>
    </div>
    <div class="line-right f_r"></div>
</div>
</body>
</html>