<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

    <title>在这里共享商企平台</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <link href="/Public/hplus/css/bootstrap.min.css" rel="stylesheet">
    <link href="/Public/hplus/css/font-awesome.min93e3.css?v=4.4.0" rel="stylesheet">
    <link href="/Public/hplus/css/animate.min.css" rel="stylesheet">
    <link href="/Public/hplus/css/style.min.css" rel="stylesheet">
    <link href="/Public/hplus/css/login.min.css" rel="stylesheet">
    <link href="/Public/hplus/css/plugins/sweetalert/sweetalert.css" rel="stylesheet">
    <style>
        .signinpanel {
            width: 780px;
            margin: 15% auto 0;
        }
        .title-in{
            width: 100%;
            text-align: center;
            color: #fff;          
        }
        .signin {
            position: fixed;
            overflow: hidden;
            display: inline-block;
            background: url(/Public/hplus/img/login-bg.jpg) no-repeat center fixed !important;
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
            color: rgb(255,255,255)!important;
        }
        .mycell{
            display: inline-block;
            background: rgba(0,0,0,.3);
        }
/*chen*/
        @media screen and (max-width: 850px) {
            .addClassChen {
                display: none !important;
            }
            .signinpanel{
                margin: 30px auto !important;
            }
            .mycell{
                display: none !important;
            }
            body{
                height: 100% !important;
                width: 100% !important;
               
            }
        }
        @media screen and (min-width: 851px) {
            #mainText {
                display: none !important;
            }
        }
        #mainText{
            height: 100%;
            width: 100% !important;
            padding: 2% 0%;
            font-size: 12px;
            margin-left: auto !important;
            margin-right:auto !important; 
            min-width: 320px !important;
             max-width: 600px;

        }
        .boxMain{
            width: 100%;
            margin: 0 auto;
        }
    </style>
    <script type="text/javascript" src="/Public/hplus/js/jquery.min.js"></script>
    <script src="/Public/hplus/js/plugins/sweetalert/sweetalert.min.js"></script>
    <!--[if lt IE 9]>
    <meta http-equiv="refresh" content="0;ie.html" />
    <![endif]-->
    <script>
        if(window.top!==window.self){window.top.location=window.location};
    </script>

</head>

<body class="signin">
    <div class="mycell"  style="position: absolute;left: 0;top: 0;z-index: 5;">
    </div>
    <div class="signinpanel  addClassChen" >
        <div class="row" style="margin-top: -130px; position: relative; z-index: 10" >
            <div class="title-in">
            <p style='font-size: 38px; color: rgb(255,255,255)!important;'> 再小的个体，也可以因专业而伟大! </p>
            </div>
            <div class='col-sm-12'  style="">
            <div   style="padding: 0;margin: 20px auto 0; width: 50%" >
                <img src="/Public/hplus/img/login_logo.png" style="width: 150px;height: 150px;border-radius: 50%;display: block;margin:0 auto">
                <p class="m-t-md" style=" font-size: 30px; color: rgb(251,252,244);text-align: center;margin-top: 20px;">在这里共享商企平台</p>
                <form onsubmit="javascript:return false;" style="border: none;background: transparent;box-shadow: 0 0 0 transparent;padding-top: 0px;" >
                <div>
                    <input type="text" class="form-control uname" name="username" id="username" placeholder="手机号或者商户号" />
                    <input type="password" class="form-control pword m-b" name="password" id="password" placeholder="密码" style="margin-top: 0" />
                </div>
                    
                    <a href="/Business/Log/findpassword"  style="color: #fff;font-weight: 500">忘记密码了？</a>
                    <button class="btn btn-success btn-block" onclick="javascript:loginAction();" style="margin-bottom: 15px;background: rgb(73,208,171);border: 1px solid rgb(73,208,171) ;font-weight: 500">立即登录</button>
                     <strong>还没有账户？ <a href="/Business/Log/check" style="color: #fff;font-weight: 500">立即注册 &raquo;</a></strong>
                </form>
            </div>
            </div>
            
        </div>
        
    </div>
<!-- chen -->
    <div class="signinpanel" id="mainText">
        <div class="title-in">
        <p style='font-size: 15px; color: rgb(255,255,255)!important;'> 再小的个体，也可以因专业而伟大! </p>
        </div>
        
        <div   style="padding: 0;margin: 25px auto;" class="boxMain">
            <img src="/Public/hplus/img/login_logo.png" style="width: 110px;height: 110px;border-radius: 50%;display: block;margin:0 auto">
            <p class="m-t-md" style=" font-size: 20px; color: rgb(251,252,244);text-align: center;margin-top: 20px;">在这里共享商企平台</p>
            <form onsubmit="javascript:return false;" style="border: none;background: transparent;box-shadow: 0 0 0 transparent;padding-top: 0px;" >
            <div>
                <input type="text" class="form-control uname" name="username" id="username1" placeholder="手机号或者商户号" />
                <input type="password" class="form-control pword m-b" name="password" id="password1" placeholder="密码" style="margin-top: 0" />
            </div>
                
                <a href="/Business/Log/findpassword"  style="color: #fff;font-weight: 500">忘记密码了？</a>
                <button class="btn btn-success btn-block" onclick="javascript:loginAction();" style="margin-bottom: 15px;background: rgb(73,208,171);border: 1px solid rgb(73,208,171) ;font-weight: 500">立即登录</button>
                 <strong>还没有账户？ <a href="/Business/Log/check" style="color: #fff;font-weight: 500">立即注册 &raquo;</a></strong>
            </form>
        </div>
    </div>
<!-- chen -->
    <div class="signup-footer " style="position: fixed;z-index: 10;bottom: 0;width: 100%" >
            <div style="text-align: center;" >
                &copy; 在这里共享商企平台 版权所有
            </div>
        </div>
</body>
<script>
    if (window.innerWidth>=850){
       $('.signin').css('width',window.screen.width);
       $('.mycell').css('width', window.screen.width);
       $('.signin').css('height',window.screen.height);
       $('.mycell').css('height', window.screen.height);
    }
   
    function loginAction(){
        //准备
        var url = "/business/log/in";
        var username = $('#username').val();
        var password = $('#password').val();
        if (!username) {
            username = $('#username1').val();
        }
        if (!password) {
            password = $('#password1').val();
        }
        //发送
        $.post(url,{"username":username,"password":password},function(d){
            if(d.error){            
                swal(d.msg, "", "warning");
                return false;
            }else{
                window.location.href = '/business';
                return false;
            }
        },'json');
    }
</script>
</html>
