<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>

<body class="gray-bg">
    <div class="wrapper wrapper-content animated fadeInRight">
       
        <div class="row">
            <div class="col-sm-12">
                <div class="ibox float-e-margins">
                   <div class="ibox-title">
                            <h5>会员编辑</h5>
                            <span class="label label-primary pull-right label-primary-cust">
                            <a href="javascript:self.location=document.referrer;" class="fa-lg-cust-a" title="返回上一页">
                                <i class="fa fa-arrow-left fa-lg-cust" aria-hidden="true"></i>
                            </a>
                        </span>
                    </div>
                    <div class="ibox-content">
                        <form class="form-horizontal m-t" id="">
                            <div class="form-group">
                                <label class="col-sm-3 control-label">姓名：</label>
                                <div class="col-sm-8">
                                    <input id="cname" name="name" value="<?php echo $result['name']; ?>" type="text" class="form-control" required="" aria-required="true">
                                </div>
                            </div>
                          	 <div class="form-group">
                                <label class="col-sm-3 control-label">电话：</label>
                                <div class="col-sm-8">
                                    <input id="tel-num" readonly="readonly" name="phone_num" value="<?php echo $result['phone_num']; ?>" type="number" class="form-control" required="" aria-required="true">
                                </div>
                            </div>
							<div class="form-group">
                                <label class="col-sm-3 control-label">性别：</label>
                                <div class="col-sm-8">
                                    <div class="radio i-checks">
                                        <label><input type="radio" <?php echo $result['sex'] == 1 ? 'checked=""' : ''; ?> value="1" name="sex"> <i></i> 男</label>
                                    </div>
                                    <div class="radio i-checks">
                                        <label><input type="radio" <?php echo $result['sex'] == 0 ? 'checked=""' : ''; ?> value="0" name="sex"> <i></i> 女</label>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">生日：</label>
                                <div class="col-sm-8">
                                    <input value="<?php echo $result['birth_time']; ?>" name="birth_time" type="text" class="form-control layer-date" onclick="laydate({istime: true, format: 'YYYY-MM-DD'})" required="" aria-required="true">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">入会时间：</label>
                                <div class="col-sm-8">
                                    <input value="<?php echo $result['join_time']; ?>" name="join_time" type="text" class="form-control layer-date" onclick="laydate({istime: true, format: 'YYYY-MM-DD hh:mm:ss'})" required="" aria-required="true">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">级别：</label>
                                <div class="col-sm-8">
                                    <div class="radio i-checks">
                                        <label><input type="radio" <?php echo $result['level'] == 'A' ? 'checked=""' : ''; ?> value="A" name="level"> <i></i> A</label>
                                    </div>
                                    <div class="radio i-checks">
                                        <label><input type="radio" <?php echo $result['level'] == 'B' ? 'checked=""' : ''; ?> value="B" name="level"> <i></i> B</label>
                                    </div>
                                    <div class="radio i-checks">
                                        <label><input type="radio" <?php echo $result['level'] == 'C' ? 'checked=""' : ''; ?> value="C" name="level"> <i></i> C</label>
                                    </div>
                                    <div class="radio i-checks">
                                        <label><input type="radio" <?php echo $result['level'] == 'D' ? 'checked=""' : ''; ?> value="D" name="level"> <i></i> D</label>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">添加时间：</label>
                                <div class="col-sm-8">
                                    <input disabled="" value="<?php echo $result['add_time']; ?>" type="text" class="form-control" required="" aria-required="true">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">备注：</label>
                                <div class="col-sm-8">
                                    <textarea class="form-control" rows="3" style="resize:none;" placeholder="最多输入255个字符" name="notice"><?php echo $result['notice']; ?></textarea>
                                </div>
                            </div>
                            <div class="form-group form-group-bottom">
                                <div class="col-sm-2 col-sm-offset-3">
                                    <p class="btn btn-warning" onclick="javascript:submitEdit();">保存更改</p>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            
            </div>
           
        </div>
    </div>
</body>
<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>

<script>
    //按钮样式
    $(document).ready(function(){$(".i-checks").iCheck({checkboxClass:"icheckbox_square-green",radioClass:"iradio_square-green",})});
    //编辑会员
    function submitEdit(){
        var url = '/Business/Member/edit';
        $.post(url,$('form').serialize(),function(d){
            if(d.error){
                  swal(d.msg, "", "error");
                return false;
            }else{
                swal(d.msg, "", "success");
                return false;
            }
        },'json');
    }
</script>
