<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<body>
<div class="per-container">
    <div class="person-bg">
        <a href="<?php echo $_SERVER['HTTP_REFERER']; ?>" class="fa fa-angle-left"></a>
        <div class="headimg">
            <img src="<?php echo $member['base64_con']; ?>" alt="">
        </div>
        <div class="username">
           <span><?php echo $member['nick_name']; ?></span>
        </div>
    </div>
    <div class="person-content">
        <ul>
            <li class="clearfix">
                <span class="f_l">
                <img src="/Public/Index/index/images/sex.png" alt="">
                </span> <span class="f_l">性别</span> <span class='f_r'><?php echo $member['sex'] ? '男' : '女'; ?></span>
            </li>
            <li class="clearfix">
                <span class="f_l">
                    <img src="/Public/Index/index/images/age.png" alt="">
                </span>
                <span class="f_l">生日：</span>
                <span class='f_r'><?php echo $member['birthday']; ?></span>
            </li>
            <li class="clearfix">
                <span class="f_l">
                    <img src="/Public/Index/index/images/phone.png" alt="">
                </span>
                <span class="f_l">手机号：</span>
                <span class='f_r'><?php echo substr($member['phone_num'],0,3).'****'.substr($member['phone_num'],7,4); ?></span>
            </li>
        </ul>
    </div>
    <div class='person-btn'>
        <?php if($member['member_id'] != $thisMemberId): ?>
        <a href="#" style="background-color:#3bdd16">跟他聊天</a>
        <?php else: ?>
        <a href="/index.php/index/user/index">我的资料</a>
        <a href="javascript:logOut();" style="margin-top: 0.5rem;background-color: #FFFFFF;border: 1px solid #D2D2D2;color: #8C8C8C;">退出</a>
        <?php endif; ?>
    </div>
</div>
</body>
<script>
    function logOut(){
        if(confirm('您确定要退出登录吗？')){
            window.location.href = "/index.php/index/user/logout";
        }
    }
</script>