<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<body class="re-bo-all">
<div class="recent-regist-all">
	<div class="recent-re-it">
		<div class="re-t recent-re-t ">
			<a href="/video/user">
                <div class="recent-return"></div>
            </a>
			<span class="login-l">我的收藏</span>
		</div>
	</div>
    <!-- 收藏里用 -->
	<div class="recent-del my-cang">
		<ul>
			<?php if(count($res) >= 1): ?>
			<?php foreach($res as $v): ?>
			<li>
				<div class="rec-del-li">
					<div onclick="javascript:window.location.href='/video/video/play?video_id=<?php echo $v['video_id']; ?>';" class="rec-ii">
						<img src="<?php echo $v['pic_path']; ?>" alt="">
					</div>
					<button style="background-color: #ff9500;color: #fff;font-size: 0.3rem;" onclick="javascript:clearFavorite(<?php echo $v['video_id']; ?>);" class="rec-bb">删除</button>
				</div>
			</li>
			<?php endforeach; ?>
			<?php endif; ?>
		</ul>
	</div>
	<div class="margin-body"></div>
	<div class="nav-foot">
		<div class="line-left f_l"></div>
		<div class="moddle-logo">
		    <img src="/Public/Video/index/image/bot.png" alt="">
		    <p class="big f_l">在这里</p >
		    <p class="small f_l">zzlhi.com</p >
		</div>
		<div class="line-right f_r"></div>
	</div>		
</div>

<script type="text/javascript">
	function clearFavorite(video_id){
		if(confirm('确定取消收藏？')){
			//准备
			var url = "/Video/user/myFavorite";
			//发送
			$.post(url,{video_id:video_id},function(d){
				d = eval('('+ d +')');
				if(d.error){
					alert(d.msg);
					return false;
				}else{
					alert(d.msg);
					window.location.reload();
					return false;
				}
			},'text');
		}
	}
</script>