
<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<body class="gray-bg">
    <div class="wrapper wrapper-content animated fadeInRight">

        <div class="row">
         
            <div class="col-sm-12">
                <div class="ibox float-e-margins business-info">
                    <div class="ibox-title">
                        <h5>商户资料</h5>
                        <span class="label label-primary pull-right label-primary-cust">
                            <?php if($_GET['back'] == 'true'): ?>
                            <a href="javascript:history.back(-1);" class="fa-lg-cust-a" title="返回上一页">
                                <i class="fa fa-arrow-left fa-lg-cust"  aria-hidden="true"></i>
                            </a>
                            <?php endif; ?>
                        </span>
                    </div>
                    <div class="ibox-content">
                        <form class="form-horizontal m-t" id="signupForm">
                         <div class="form-group">
                                <label class="col-sm-3 control-label">商户号：</label>
                                <div class="col-sm-8">
                                    <input id="firstname" name="firstname" class="form-control" type="text" disabled="disabled" value="<?php echo $info['business_id'] ?>">
                                </div>
                            </div>
                             <div class="form-group">
                                <label class="col-sm-3 control-label">法人姓名：</label>
                                <div class="col-sm-8">
                                    <input id="username" name="username" class="form-control" type="text" disabled="disabled"  value="<?php echo $info['legal_name'] ?>">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">法人身份证号：</label>
                                <div class="col-sm-8">
                                    <input id="cardId" name="cardId" class="form-control" type="text" disabled="disabled"  value="<?php echo $info['card_num'] ?>">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">手机号：</label>
                                <div class="col-sm-8">
                                    <input id="phone" name="phone" class="form-control" type="text" disabled="disabled"  value="<?php echo $info['phone_num'] ?>">
                                </div>
                            </div>
                             
                            <div class="form-group">
                                <label class="col-sm-3 control-label">公司名称：</label>
                                <div class="col-sm-8">
                                    <input id="" name="company_name" class="form-control" type="text" disabled="disabled"  value="<?php echo $info['company_name'] ?>">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">行业类型：</label>
                                <div class="col-sm-8">
                                    <select  disabled="disabled" class="input-sm form-control input-s-sm inline" name="profession_id" style="height: 33px;">
                                        <option value="0">行业类别</option>
                                        <?php foreach ($professions as $key => $value): ?>
                                        <?php $pro_dis = ($value['profession_id']==$info['profession_id'])?'selected="selected"':''; ?>
                                        <option value="<?php echo $value['profession_id'] ?>" <?php echo $pro_dis; ?> ><?php echo $value['profession_name'] ?></option>
                                        <?php endforeach ?>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">积分商城名称：</label>
                                <div class="col-sm-8">
                                    <input id="" name="exchange_name" class="form-control" disabled="disabled" type="text"  value="<?php echo $info['exchange_name'] ?>">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">公司所在地：</label>
                                <div class="col-sm-8">
                                   <select disabled="disabled" class="input-sm form-control input-s-sm inline" name="province_id" style="width: 97px;height: 33px;">
                                        <option value="0">省份</option>
                                        <?php foreach ($provinces as $key => $value): ?>
                                        <?php $prov_dis = ($value['province_id']==$info['province_id'])?'selected="selected"':''; ?>
                                        <option value="<?php echo $value['province_id'] ?>" <?php echo $prov_dis; ?> ><?php echo $value['province_name'] ?></option>
                                        <?php endforeach ?>
                                    </select>

                                    <select disabled="disabled" class="input-sm form-control input-s-sm inline" name="city_id" style="width: 97px;height: 33px;">
                                        <option value="0">城市</option>
                                        <?php foreach ($citys as $key => $value): ?>
                                        <?php $city_dis = ($value['city_id']==$info['city_id'])?'selected="selected"':''; ?>
                                        <option value="<?php echo $value['city_id'] ?>" <?php echo $city_dis; ?> ><?php echo $value['city_name'] ?></option>
                                        <?php endforeach ?>
                                    </select>

                                    <select disabled="disabled" class="input-sm form-control input-s-sm inline" name="area_id" style="width: 97px;height: 33px;">
                                        <option value="0">区(县)</option>
                                        <?php foreach ($areas as $key => $value): ?>
                                        <?php $area_dis = ($value['area_id']==$info['area_id'])?'selected="selected"':''; ?>
                                        <option value="<?php echo $value['area_id'] ?>" <?php echo $area_dis; ?> ><?php echo $value['area_name'] ?></option>
                                        <?php endforeach ?>
                                    </select>
                                                    
                                </div>
                            </div>
                             <div class="form-group">
                                <label class="col-sm-3 control-label">街道地址：</label>
                                <div class="col-sm-8">
                                    <input id="" disabled="disabled" name="business_address" class="form-control" type="text" value="<?php echo $info['business_address'] ?>">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">注册时间：</label>
                                <div class="col-sm-8">
                                    <input id="" name="" class="form-control" type="text" disabled="disabled" value="<?php echo $info['add_time'] ?>">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>
</body>