<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<style>
   
    .table-responsive .cap-center th,.table-responsive table tbody td{
        text-align: center !important;
    }
    .alert-warning b{
        color:red;
    }
    
</style>
<body class="gray-bg">
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-sm-12">
                <div class="ibox">
                    <div class="ibox-title">
                        <h5><?php echo $_GET['is_start'] == 1 ? '推荐下线' : '间接下线商户';?></h5>
                            <span class="label label-primary pull-right label-primary-cust">
                            <a href="<?php echo $back_url; ?>" class="fa-lg-cust-a" title="返回上一页">
                                <i class="fa fa-arrow-left fa-lg-cust"  aria-hidden="true"></i>
                            </a> 
                        </span>
                    </div>
                    <div class="ibox-content">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="input-group col-sm-12">
                                    <form method="get" action="/admin/business/recommend_list?dog=12" class="clearfix pull-left" >
                                        <label class="col-sm-4 control-label" style="padding-right: 0;margin-top: 6px;width: 100px;">按注册日期：</label>
                                        <div class="col-sm-8"  style="padding-left: 0;padding-right: 10px;width: 210px;">
                                            <input placeholder="开始日期" name="regs_start_time" value="<?php echo $_GET['regs_start_time'] ?>" class="form-control layer-date" id="start" style="width:100px;height: 30px;" >
                                            <input placeholder="结束日期" name="regs_end_time" value="<?php echo $_GET['regs_end_time'] ?>" class="form-control layer-date " id="end" style="width:100px;height: 30px;" >
                                        </div>
                                        <label class="col-sm-4 control-label" style="padding-right: 0;margin-top: 6px;width: 125px;">按首次激活日期：</label>
                                        <div class="col-sm-8"  style="padding-left: 0;padding-right: 10px;width: 210px;">
                                            <input placeholder="开始日期" name="activate_start_time" value="<?php echo $_GET['activate_start_time'] ?>" class="form-control layer-date" id="start1" style="width:100px;height: 30px;" >
                                            <input placeholder="结束日期" name="activate_end_time" value="<?php echo $_GET['activate_end_time'] ?>" class="form-control layer-date " id="end1" style="width:100px;height: 30px;" >
                                        </div>
                                        <select name="status" class="input-sm form-control input-s-sm inline sex-select " style="width: 100px;margin-right: 10px;margin-left: 20px;">
                                            <option value="0">激活状态</option>
                                            <option disabled="true">--------------------</option>
                                            <option <?php echo $_GET['status']==1?'selected="selected"':'';?> value="1">已激活</option>
                                            <option <?php echo $_GET['status']==2?'selected="selected"':'';?> value="2">未激活</option>
                                        </select>
                                        <input type="hidden" name="business_id" value="<?php echo $_GET['business_id'] ?>">
                                        <input type="hidden" name="back" value="<?php echo $_GET['back'] ?>">
                                        <input type="hidden" name="recommend" value="<?php echo $_GET['recommend'] ?>">
                                        <input type="hidden" name="is_start" value="<?php echo $_GET['is_start'] ?>">
                                        <span class="input-group-btn pull-left " >
                                            <button type="submit" class="btn btn-sm btn-primary search-btn"> 搜索</button>
                                        </span>
                                    </form>
                                    <button type="button" onclick="javascript:window.location.href='/admin/business/recommend_list?business_id=<?php echo $_GET['business_id']; ?>&back=<?php echo $_GET['back']; ?>&is_start=<?php echo $_GET['is_start']; ?>&recommend=<?php echo $_GET['recommend']; ?>';" class="btn btn-danger btn-sm  reset-btn pull-left" style="">刷新</button>
                                </div>
                            </div>
                        </div>
                        <div class="member-warn">
                            <div class="alert alert-warning">
                                <?php if($_GET['is_start'] == 1): ?>
                                    <span>注册时推荐人ID直接填写商户ID（<b><?php echo $_GET['business_id']; ?></b>）的商户共有：<b><?php echo count($unleaders); ?></b> 人，间接隶属于此商户的下线商户共有：<b><?php echo $jianjieCount; ?></b> 人，线下商户共：<b><?php echo count($unleaders)+$jianjieCount; ?> </b>人</span>
                                <?php else: ?>
                                    <span>间接隶属于商户（<b><?php echo $_GET['recommend']; ?></b>）的下线商户共有：<b><?php echo count($unleaders) + $jianjieCount; ?></b> 人，其中注册时推荐人ID直接填写商户ID <strong><?php echo $_GET['business_id']; ?></strong> 的商户有：<b><?php echo count($unleaders); ?></b> 人，间接隶属于此商户的下线商户有：<b><?php echo $jianjieCount; ?></b> 人</span>
                                <?php endif; ?>
                            </div>
                        </div>
                        <div class="tab-content">
                            <div id="tab-1" class="tab-pane active">
                                <div class="full-height-scroll">
                                    <div class="table-responsive">
                                        <table class="table table-striped table-hover">
                                            <tbody>
                                                <tr class="cap-center">
                                                    <th><?php echo urldecode('&reg') ?>序号</th>
                                                    <th>商户ID</th>
                                                    <th>商户姓名</th>
                                                    <th>间接下线人数</th>
                                                    <th>电话</th>
                                                    <th>公司名称</th>
                                                    <th>激活状态</th>
                                                    <th>首次激活时间</th>
                                                    <th>注册时间</th>
                                                     <th>操作</th>
                                                </tr>
                                                <?php foreach($unleaders as $k => $v): ?>
                                                <tr>
                                                    <td><?php echo $k + 1; ?></td>
                                                    <td><?php echo $v['business_id']; ?></td>
                                                    <td><?php echo $v['legal_name']; ?></td>
                                                    <td><?php echo $jianjieEvery[$v['business_id']] > 0 ? '<font color="blue">'.$jianjieEvery[$v['business_id']].'</font>' : 0; ?></td>
                                                    <td><?php echo $v['phone_num']; ?></td>
                                                    <td><?php echo $v['company_name']; ?></td>
                                                    <td><?php echo $v['status'] == 1 ? '已激活' : '未激活'; ?></td>
                                                    <td><?php echo $v['first_activate_time']; ?></td>
                                                    <td><?php echo $v['add_time']; ?></td>
                                                     <td>
														<a href="/admin/business/recommend_list?business_id=<?php echo $v['business_id']; ?>&recommend=<?php echo $recommend.' > '.$v['business_id'];?>&regs_start_time=<?php echo $_GET['regs_start_time']; ?>&regs_end_time=<?php echo $_GET['regs_end_time']; ?>&activate_start_time=<?php echo $_GET['activate_start_time']; ?>&activate_end_time=<?php echo $_GET['activate_end_time']; ?>&status=<?php echo $_GET['status']; ?>" style="margin-right: 10px;">
				                                            <span class="label label-success">间接下线商户</span>
				                                        </a>
                                                     </td>
                                                </tr>
                                                <?php endforeach; ?>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>
<script type="text/javascript">
$(document).ready(function(){
        $(".footable").footable();
      var start = {
            elem: "#start",
            format: "YYYY/MM/DD",
            min:  "2011-06-16 23:59:59",
            max: laydate.now(),
            istime: false,
            istoday: false,
            choose: function(datas) {
                end.min = datas;
                end.start = datas
            }
        };
        var end = {
            elem: "#end",
            format: "YYYY/MM/DD",
            min: "2011-06-16 23:59:59",
            max: laydate.now(),
            istime: false,
            istoday: false,
            choose: function(datas) {
                start.max = datas
            }
        };
        laydate(start);
        laydate(end);
          var start1 = {
            elem: "#start1",
            format: "YYYY/MM/DD",
            min:  "2011-06-16 23:59:59",
            max: laydate.now(),
            istime: false,
            istoday: false,
            choose: function(datas) {
                end.min = datas;
                end.start = datas
            }
        };
        var end1 = {
            elem: "#end1",
            format: "YYYY/MM/DD",
            min: "2011-06-16 23:59:59",
            max: laydate.now(),
            istime: false,
            istoday: false,
            choose: function(datas) {
                start.max = datas
            }
        };
        laydate(start1);
        laydate(end1);
    });
</script>
