<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<body class="per-all">
    <div class="person" >
        <div class="per-top">
            <div class="pre-t-t">
                <a href="/video">
                    <div class=" person-ret"></div>
                </a>
            </div>
            <div class="per-head">
                <img src="<?php echo $base64_con; ?>" alt="" class="per-head-i"> 
                <p class="per-head-t"><?php echo $memberInfo['nick_name']; ?></p>
            </div>
        </div>
    <div class="per-cen">
    <ul>
        <li>
            <a href="/video/user/myFavorite">
            <img src="/Public/Video/index/image/shoucang.png" alt="" class="per-sen-t">
            <span class="per-sen-t">我的收藏</span>
            </a>
        </li>
        <li>
            <a href="/video/user/viewed">
            <img src="/Public/Video/index/image/liulan.png" alt="" class="per-sen-t">
            <span class="per-sen-t">最近浏览</span>
            </a>
        </li>
        <li>
            <a href="/video/user/orders" >
            <img src="/Public/Video/index/image/dingdan.png" alt="" class="per-sen-t">
            <span class="per-sen-t">我的订单</span>
            </a>
        </li>
        <li>
        </li>
    </ul>
    <div class="per-cut-off"></div>
    </div>
    <div class="nav-foot" style="bottom: -4rem;">
        <div class="line-left f_l"></div>
        <div class="moddle-logo">
            <img src="/Public/Video/index/image/bot.png" alt="">
            <p class="big f_l">在这里</p >
            <p class="small f_l">zzlhi.com</p >
        </div>
        <div class="line-right f_r"></div>
    </div>
</div>