<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<style type="text/css">
    .collet-cen-it .col-cen-li .col-li-but{
        border-radius: 5%;
        width: 2rem;
        background-color: #ffffff;
        border:none;
        right: 0.2rem;
        color: #000;
        top: 0.4rem;
        border-radius:3px;
    }
</style>
<body class="re-bo-all">
    <div class="recent-regist-all">
    	<div class="recent-re-it">
    		<div class="re-t recent-re-t ">
    			<a href="/video/user">
                    <div class="recent-return"></div>
                </a>
    			<span class="login-l">我的订单</span>
    		</div>
    	</div>
    	<div class="cut-off"></div>
	<div class="collet-cen-it">
	<ul>
	<?php foreach($res as $v): ?>
	<li class="col-cen-li " id="del_<?php echo $v['order_id'] ?>" style="background-color: #fff;padding-left: 0.5rem;padding-top: 0.3rem;height: 3.2rem;">
		<div class="main-t-tbot">
			<p>订单号码：<?php echo $v['order_sn']; ?></p>
			<p>购买视频：<a href="/video/video/play?video_id=<?php echo $v['video_id']; ?>"><?php echo mb_substr($v['name'],0,15); ?></a></p>
			<p>消费金额：<?php echo $v['pay_num']; ?>元</p>
			<p>购买时间：<?php echo $v['create_time']; ?></p>
		</div>
        <?php 
            if($v['status'] == 0){
                $sta = '待支付';
                $state = base64_encode($_SERVER['HTTP_HOST'].'#'.$v['order_id']);
                $sta_coclor = 'style="color:#ea4049"';
                $go_pay = '<a href="https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx52c227bda3132ccb&redirect_uri=http%3A%2F%2Fwww.zzlhi.com%2FVideo%2FOrder%2Fpayment&response_type=code&scope=snsapi_base&state='.$state.'#wechat_redirect" class="col-li-but " style="top: 1.4rem;background-color:#ea4049;color:#FFFFFF">去支付</a>';
                $delete = '<a href="javascript:delete_order('.$v['order_id'].');" class="col-li-but " style="top: 2.4rem;border:1px solid #999999;color:#999999;">删&nbsp;&nbsp;除</a>';
            }elseif($v['status'] == 1){
                $sta = '已支付';
                $sta_coclor = 'style="color:#92b63a"';
                $go_pay = '';
                $delete = '';
            }elseif($v['status'] == 2){
                $sta = '已失效';
                $sta_coclor = 'style="color:#1a1a1a"';
                $go_pay = '';
                $delete = '<a href="javascript:delete_order('.$v['order_id'].');" class="col-li-but " style="top: 1.4rem;border:1px solid #999999;color:#999999">删&nbsp;&nbsp;除</a>';
            }
        ?>
	<button class="col-li-but " <?php echo $sta_coclor; ?>><?php echo $sta; ?></button>
    <?php echo $go_pay;echo $delete; ?>
	</li>
  	<div class="cut-off"></div>
	<?php endforeach; ?>
	</ul>
	</div>
	<div class="margin-body"></div>
	<div class="nav-foot">
        <div class="line-left f_l"></div>
        <div class="moddle-logo">
            <img src="/Public/Video/index/image/bot.png" alt="">
            <p class="big f_l">在这里</p >
            <p class="small f_l">zzlhi.com</p >
        </div>
        <div class="line-right f_r"></div>
    </div>
</div>
<script type="text/javascript">

    function delete_order(a){
        if(confirm('是否删除该订单？')){
            $.ajax({
                cache: true,
                type: "POST",
                url:"/Video/User/del_order",
                data:{'order_id':a},
                async: false,
                dataType: 'text',
                error: function(data) {
                  alert('网络错误,删除失败');
                },
                success: function(data) {      
                    data = eval('(' + data + ')');
                    $('#del_'+a).remove();
                }
            });
        }
    }

</script>