<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<body class="gray-bg">
    <div class="wrapper wrapper-content animated fadeInRight">
      
        <div class="row">
           
            <div class="col-sm-12">
                <div class="ibox float-e-margins">
                     <div class="ibox-title">
                            <h5>通知</h5>  
                    </div>
                    <div class="ibox-content">

                        <table class="table table-hover placard-table">
                            <thead>
                                <tr>
                                    <th style="width:15%">时间</th>
                                    <th>标题</th>
                                    <th>状态</th>
                                    <th>操作</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($notices as $key => $value): ?>
                                <tr>
                                    <td <?php echo $value['is_read']==0?'style="font-weight: bold;"':'style="color: #CCC;"'; ?>><?php echo $value['add_time'] ?></td>
                                    <td <?php echo $value['is_read']==0?'style="font-weight: bold;"':'style="color: #CCC;"'; ?>><span><?php echo $value['title'] ?></span>
                                    </td>
                                    <td <?php echo $value['is_read']==0?'style="font-weight: bold;"':'style="color: #CCC;"'; ?>><span><?php echo $value['is_read']==0?'未读':'已读'; ?></span>
                                    </td>
                                    <td>
                                        <a href="/Business/center/notices_detail?notices_id=<?php echo $value['notices_id'] ?>"><span class="label label-primary ">查看</span></a>
                                        <a href="javascript:del_notice(<?php echo $value['notices_id'] ?>)"><span class="label label-danger ">删除</span></a>
                                    </td>
                                </tr>
                                <?php endforeach ?>
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td colspan="12">
                                        <div class="b-page">
                                            <?php echo $page['page']; ?>
                                        </div>
                                    </td>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        
    </div>
   
</body>

<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>
<script type="text/javascript">
    window.onload=function(){
        window.parent.get_notices_num();  
    }
    function del_notice(id){
        swal({
            title: "删除通知后将不可恢复，您确定要删除该通知吗？",
            text: "",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "是的，我要删除！",
            cancelButtonText: "我再考虑一下…",
            closeOnConfirm: false,
            closeOnCancel: true
        },
        function(isConfirm) {
            if (isConfirm) {
                $.ajax({
                    cache: true,
                    type: "POST",
                    url:"/Business/Center/del_notice",
                    data: {notices_id:id},
                    dataType: 'json',
                    async: false,
                    error: function(data) {
                        alert('网络错误');
                    },
                    success: function(data) {
                        if (data.error == 0) {
                            window.location.reload();
                        }else{
                            swal(data.msg, "", "error");
                        }
                    }
                });
                
            }
        })
    }
</script>
