<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<style>
.wy-header {
    height: 44px;
    border-bottom: 0px;
    position: fixed;
    left: 0;
    top: 0;
    width: 100%;
    background: #e21323;
    z-index: 100;
}
.wy-header-title {
    margin: 0 50px;
    text-align: center;
    height: 44px;
    line-height: 44px;
    font-size: 16px;
    color: #fff;
    overflow: hidden;
}
</style>
<body ontouchstart>
<!--主体-->
<header class="wy-header">
    <a href="javascript:history.go(-1);" title="返回上一页" style="width: 50px;position: absolute;left: 0;top: 0;z-index: 10; height: 45px;"><div class="wy-header-icon-back"><span></span></div></a>
  <div class="wy-header-title" style="color: #fff">手机注册</div>
</header>
<div class="weui-content" style="margin-top: 44px">
  <form id="reg_data" action="" method="">
  <div class="weui-cells weui-cells_form wy-address-edit">
    <div class="weui-cell weui-cell_vcode">
      <div class="weui-cell__hd"><label class="weui-label wy-lab">手机号</label></div>
      <div class="weui-cell__bd"><input name="phone_num" class="weui-input" type="tel" placeholder="请输入手机号"></div>
      <div  class="weui-cell__ft"><p class="weui-vcode-btn"  id="get_code">获取验证码</p></div>
    </div>
    <div class="weui-cell ">
      <div class="weui-cell__hd"><label class="weui-label wy-lab">验证码</label></div>
      <div class="weui-cell__bd"><input name="phone_code" class="weui-input" type="number" placeholder="请输入验证码"></div>
    </div>
    <div class="weui-cell">
      <div class="weui-cell__hd"><label class="weui-label wy-lab">设置密码</label></div>
      <div class="weui-cell__bd"><input name="password" class="weui-input" type="password" pattern="[0-9]*" placeholder="请输入新密码"></div>
    </div>
    <div class="weui-cell">
      <div class="weui-cell__hd"><label class="weui-label wy-lab">确认密码</label></div>
      <div class="weui-cell__bd"><input name="repassword" class="weui-input" type="password" pattern="[0-9]*" placeholder="请再次输入新密码"></div>
    </div>
  </div>
  <!-- <label for="weuiAgree" class="weui-agree">
    <input id="weuiAgree" name="agree" type="checkbox" class="weui-agree__checkbox" checked="checked">
    <span class="weui-agree__text">阅读并同意<a href="javascript:void(0);">《注册协议》</a></span>
  </label> -->
  <div id="submit_btn" class="weui-btn-area"><a href="javascript:;" class="weui-btn weui-btn_warn">注册并登录</a></div>
  <div class="weui-cells__tips t-c font-12">登录账号为您输入的手机号码</div>
  <!-- <div class="weui-cells__tips t-c pd-10"><a href="xieyi.html" class="weui-cell_link font-12">查看注册协议</a></div> -->
  </form>
</div>



</body>
<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>

<script>
  $(function() {
    FastClick.attach(document.body);
  });
      var wait=60;
        function time(o) {
          if (wait == 0) {
           //o.removeAttribute("disabled");   
           o.innerHTML="重新发送";
           o.style.backgroundColor='transparent !important';
           wait = 60;
          } else { 
           o.style.backgroundColor='transparent !important';
           //o.setAttribute("disabled", true);
           o.innerHTML="重新发送(" + wait + "s)";
           wait--;
           setTimeout(function() {
            time(o)
           },
           1000)
          }
         }
    //获取手机验证码
    var flag = false; //防止二次提交
    $('#get_code').click(function(){
        var _this = this;
        if($('input[name=phone_num]').val()){
            var phone_num = $('input[name=phone_num]').val();
        }else{
            var phone_num='';
            $.toast('请填写手机号', "cancel");return false;
        }

        if (flag) {
            return false;
        }
        flag = true;
        $.ajax({
            cache: true,
            type: "POST",
            url:"/exchange/log/send_code",
            data:{'phone_num':phone_num},
            dataType: 'json',
            async: false,
            error: function(data) {
                $.toast('网络错误', "cancel");
                flag = false;
            },
            success: function(data) {      
                if (data.error == 0) {
                    time(_this);
                }else{
                    $.toast(data.msg, "cancel");
                    flag = false;
                }
            }
        });
    });
    $('#submit_btn').click(function(){
        if (!$('input[name=phone_num]').val()) {
            $.toast('请填写手机号', "cancel");
            return;
        }
        if (!$('input[name=phone_code]').val()) {
            $.toast('请填写手机验证码', "cancel");
            return;
        }
        if (!$('input[name=password]').val()) {
            $.toast('请填写密码', "cancel");
            return;
        }
        if ($('input[name=password]').val() != $('input[name=repassword]').val()) {
            $.toast('两次密码不致', "cancel");
            return;
        }
        /*if (!$("input[type='checkbox']").is(':checked')){
            $.toast('请未同意注册协议');
            return;
        }*/
        $.ajax({
            cache: true,
            type: "POST",
            url:"/exchange/log/reg",
            data:$('#reg_data').serialize(),// 你的formid
            dataType: 'json',
            async: false,
            error: function(data) {
                $.toast('网络错误', "cancel");
            },
            success: function(data) {      
                if (data.error == 0) {
                    window.location.href="/exchange/?b=<?php echo $_SESSION['exchange']['business_id']; ?>";
                }else{
                    $.toast(data.msg, "cancel");
                    flag = false;
                }
            }
        });
    });
</script>