<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<?php require_once MODULE_PATH.'/View/Common/menu.phtml'; ?>

<section class="Hui-article-box">
    <nav class="breadcrumb"><i class="Hui-iconfont">&#xe67f;</i> 首页
        <span class="c-gray en">&gt;</span>
        视频管理
        <span class="c-gray en">&gt;</span>
        视频列表 <a class="btn btn-success radius r" style="line-height:1.6em;margin-top:3px" href="javascript:location.replace(location.href);" title="刷新" ><i class="Hui-iconfont">&#xe68f;</i></a>
    </nav>
    <div class="Hui-article">
        <article class="cl pd-20">
            <div class="text-c">
                <form method="post" action="/Videoadmin/video/list">
                    <!-- <input type="text" onfocus="WdatePicker({maxDate:'#F{$dp.$D(\'datemax\')||\'%y-%M-%d\'}'})" id="datemin" class="input-text Wdate" style="width:120px;">
                    -
                    <input type="text" onfocus="WdatePicker({minDate:'#F{$dp.$D(\'datemin\')}',maxDate:'%y-%M-%d'})" id="datemax" class="input-text Wdate" style="width:120px;"> -->
                    <select class="select-box inline" name="type_id">
                        <option value="">选择类型</option>
                        <?php foreach($type as $v): ?>
                        <option value="<?php echo $v['type_id']; ?>"><?php echo $v['type_name'] ;?></option>
                        <?php endforeach; ?>
                    </select>
                    <select class="select-box inline" name="class_id">
                        <option value="">选择类别</option>
                        <?php foreach($class as $v): ?>
                        <option value="<?php echo $v['class_id']; ?>"><?php echo $v['class_name'] ;?></option>
                        <?php endforeach; ?>
                    </select>
                    <input type="text" class="input-text" style="width:250px" placeholder="影片名称" id="" name="name">
                    <button type="submit" class="btn btn-success" id="" name=""><i class="Hui-iconfont">&#xe665;</i> 搜索</button>
                </form>
            </div>
            <div class="cl pd-5 bg-1 bk-gray mt-20">
                <span class="l"> 
                    <!-- <a href="javascript:;" onclick="datadel()" class="btn btn-danger radius"><i class="Hui-iconfont">&#xe6e2;</i> 批量删除</a> -->
                    <a href="/Videoadmin/video/add" class="btn btn-primary radius"><i class="Hui-iconfont">&#xe600;</i> 添加</a>
                </span>
                <span class="r">共有视频：<strong><?php echo $count; ?></strong> 个</span>
            </div>
            <table class="table table-border table-bordered table-bg">
                <thead>
                    <tr>
                        <th scope="col" colspan="9">视频列表</th>
                    </tr>
                    <tr class="text-c">
                        <!-- <th width="25"><input type="checkbox" name="" value=""></th> -->
                        <th width="40">序号</th>
                        <th width="150">视频名</th>
                        <th width="90">图片</th>
                        <th width="60">类型</th>
                        <th width="60">类别</th>
                        <th width="80">推荐</th>
                        <th width="200">简介</th>
                        <th width="130">添加时间</th>
                        <th width="100">操作</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($res as $k => $v): ?>
                    <tr class="text-c">
                        <!-- <td><input type="checkbox" value="<?php echo $v['video_id']; ?>" name=""></td> -->
                        <td><?php echo $k + 1 + $page['firstRow']; ?></td>
                        <td><?php echo $v['name']; ?></td>
                        <td><img width="90" height="50" src="<?php echo $v['pic_path']; ?>"></td>
                        <td><?php echo empty($v['type_name']) ? '<font color="red">未选择</font>' : $v['type_name']; ?></td>
                        <td><?php echo empty($v['class_name']) ? '<font color="red">未选择</font>' : $v['class_name']; ?></td>
                        <td><?php for($i=0;$i<=5;$i++){if($v['level'] > $i){echo '★';}}; ?></td>
                        <td><?php echo mb_substr($v['synopsis'],0,30); ?>....</td>
                        <td><?php echo $v['add_time']; ?></td>
                        <td class="td-manage">
                            <!-- <a style="text-decoration:none" onClick="admin_stop(this,'10001')" href="javascript:;" title="停用"><i class="Hui-iconfont">&#xe631;</i></a> -->
                            <a title="编辑" href="/Videoadmin/video/edit?video_id=<?php echo $v['video_id']; ?>"  class="ml-5" style="text-decoration:none"><i class="Hui-iconfont">&#xe6df;</i></a>
                            <!-- <a title="删除" href="javascript:;" onclick="admin_del(this,'1')" class="ml-5" style="text-decoration:none"><i class="Hui-iconfont">&#xe6e2;</i></a> -->
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
            <div class="b-page">
                <?php echo $page['page']; ?>
            </div>
        </article>
    </div>
</section>
<!--请在下方写此页面业务相关的脚本--> 
<script type="text/javascript" src="/Public/Video/admin/lib/My97DatePicker/4.8/WdatePicker.js"></script> 
<script type="text/javascript" src="/Public/Video/admin/lib/datatables/1.10.0/jquery.dataTables.min.js"></script> 
<script type="text/javascript" src="/Public/Video/admin/lib/laypage/1.2/laypage.js"></script> 
<script type="text/javascript">
/*
    参数解释：
    title   标题
    url     请求的url
    id      需要操作的数据id
    w       弹出层宽度（缺省调默认值）
    h       弹出层高度（缺省调默认值）
*/
/*管理员-增加*/
function admin_add(title,url,w,h){
    layer_show(title,url,w,h);
}
/*管理员-删除*/
function admin_del(obj,id){
    alert('删除功能在开发中');
    return false;
    
    layer.confirm('确认要删除吗？',function(index){
        //此处请求后台程序，下方是成功后的前台处理……

        $(obj).parents("tr").remove();
        layer.msg('已删除!',{icon:1,time:1000});
    });
}

/*管理员-停用*/
function admin_stop(obj,id){
    layer.confirm('确认要停用吗？',function(index){
        //此处请求后台程序，下方是成功后的前台处理……
        
        $(obj).parents("tr").find(".td-manage").prepend('<a onClick="admin_start(this,id)" href="javascript:;" title="启用" style="text-decoration:none"><i class="Hui-iconfont">&#xe615;</i></a>');
        $(obj).parents("tr").find(".td-status").html('<span class="label label-default radius">已禁用</span>');
        $(obj).remove();
        layer.msg('已停用!',{icon: 5,time:1000});
    });
}

/*管理员-启用*/
function admin_start(obj,id){
    layer.confirm('确认要启用吗？',function(index){
        //此处请求后台程序，下方是成功后的前台处理……
        
        $(obj).parents("tr").find(".td-manage").prepend('<a onClick="admin_stop(this,id)" href="javascript:;" title="停用" style="text-decoration:none"><i class="Hui-iconfont">&#xe631;</i></a>');
        $(obj).parents("tr").find(".td-status").html('<span class="label label-success radius">已启用</span>');
        $(obj).remove();
        layer.msg('已启用!', {icon: 6,time:1000});
    });
}
</script>
<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>