<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<?php require_once MODULE_PATH.'/View/Common/menu.phtml'; ?>

<section class="Hui-article-box">
  <nav class="breadcrumb"><i class="Hui-iconfont"></i> <a href="/Hospitaladmin" class="maincolor">首页</a> 
    <span class="c-999 en">&gt;</span>
    <span class="c-666">后台首页</span> 
    <a class="btn btn-success radius r" style="line-height:1.6em;margin-top:3px" href="javascript:location.replace(location.href);" title="刷新" ><i class="Hui-iconfont">&#xe68f;</i></a></nav>
  <div class="Hui-article">
    <article class="cl pd-20">
      <p class="f-20 text-success">欢迎使用【在这里】医生站后台</p>
      <!-- <p>登录次数：18 </p> -->
      <!-- <p>上次登录IP：222.35.131.79.1  上次登录时间：2014-6-14 11:19:55</p> -->
      <table class="table table-border table-bordered table-bg">
        <thead>
          <tr>
            <th colspan="7" scope="col">信息统计</th>
      </tr>
          <tr class="text-c">
            <th>--</th>
            <th>--</th>
            <th>--</th>
            <th>--</th>
            <th>--</th>
            <th>--</th>
      </tr>
    </thead>
        <tbody>
          <tr class="text-c">
            <td>--</td>
            <td>--</td>
            <td>--</td>
            <td>--</td>
            <td>--</td>
            <td>--</td>
      </tr>
          <!-- <tr class="text-c">
            <td>今日</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
      </tr>
          <tr class="text-c">
            <td>昨日</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
      </tr>
          <tr class="text-c">
            <td>本周</td>
            <td>2</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
      </tr>
          <tr class="text-c">
            <td>本月</td>
            <td>2</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
      </tr> -->
    </tbody>
  </table>
      <table class="table table-border table-bordered table-bg mt-20">
        <thead>
          <tr>
            <th colspan="2" scope="col">服务器信息</th>
      </tr>
    </thead>
        <tbody>
          <tr>
            <th width="30%">服务器计算机名</th>
            <td><span id="lbServerName">-</span></td>
      </tr>
          <tr>
            <td>服务器IP地址</td>
            <td>-</td>
      </tr>
          <tr>
            <td>服务器域名</td>
            <td>-</td>
      </tr>
          <tr>
            <td>服务器端口 </td>
            <td>80</td>
      </tr>
          <tr>
            <td>服务器IIS版本 </td>
            <td>-</td>
      </tr>
          <tr>
            <td>本文件所在文件夹 </td>
            <td>-</td>
      </tr>
          <tr>
            <td>服务器操作系统 </td>
            <td>Microsoft Windows NT</td>
      </tr>
          <tr>
            <td>系统所在文件夹 </td>
            <td>-</td>
      </tr>
          <tr>
            <td>服务器脚本超时时间 </td>
            <td>-秒</td>
      </tr>
          <tr>
            <td>服务器的语言种类 </td>
            <td>Chinese (People's Republic of China)</td>
      </tr>
          <tr>
            <td>.NET Framework 版本 </td>
            <td>-</td>
      </tr>
          <tr>
            <td>服务器当前时间 </td>
            <td><?php echo time(); ?></td>
      </tr>
          <tr>
            <td>服务器IE版本 </td>
            <td>-</td>
      </tr>
          <tr>
            <td>服务器上次启动到现在已运行 </td>
            <td>-分钟</td>
      </tr>
          <tr>
            <td>逻辑驱动器 </td>
            <td>-</td>
      </tr>
          <tr>
            <td>CPU 总数 </td>
            <td>-</td>
      </tr>
          <tr>
            <td>CPU 类型 </td>
            <td>-</td>
      </tr>
          <tr>
            <td>虚拟内存 </td>
            <td>-</td>
      </tr>
          <tr>
            <td>当前程序占用内存 </td>
            <td>-</td>
      </tr>
          <tr>
            <td>Asp.net所占内存 </td>
            <td>-</td>
      </tr>
          <tr>
            <td>当前Session数量 </td>
            <td>-</td>
      </tr>
          <tr>
            <td>当前SessionID </td>
            <td>-</td>
      </tr>
          <tr>
            <td>当前系统用户名 </td>
            <td>-</td>
      </tr>
    </tbody>
  </table>
</article>
    <footer class="footer">
      <p>在这里</p>
</footer>
</div>
</section>
<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>
