<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no" />
    <meta name="format-detection" content="telephone=no">
    <title><?php echo $webConfig['title']; ?></title>
    <script src="/Public/Video/index/js/mui.min.js"></script>
    <script src="/Public/Video/index/js/zepto.js"></script>
    <script src="/Public/Video/index/js/main.js"></script> 
    <link href="/Public/Video/index/css/mui.css" rel="stylesheet"/>
    <link href="/Public/Video/index/css/main.css" rel="stylesheet" type="text/css"/>
    <script type="text/javascript" charset="utf-8">
        mui.init();
    </script>
  </head>
  <body>