<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>

<style>
.good-img{
    width: 50px;
    height: 50px;
    display: block;
}
table{
    font-size: 13px;
}
.footable-row-detail-name {
    display: table-cell;
    font-weight: bold;
    padding-right: 0.5em;
    line-height: 30px;
    min-width: 80px;
}
.modal-backdrop{
    display: none;
}
</style>

<body class="gray-bg">
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-sm-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>商户列表</h5>
                    </div>
                    <div class="ibox-content">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="input-group col-sm-12">
                                    <form method="get" action="/admin/business/business_list" class="clearfix pull-left" >
                                        <input type="text" name="keywords" value="<?php echo $_GET['keywords'] ? $_GET['keywords'] : ''; ?>" placeholder="公司名称" class="input-sm form-control pull-left col-sm-4" style="width:74%;" >
                                        <span class="input-group-btn pull-left " >
                                            <button type="submit" class="btn btn-sm btn-primary search-btn"> 搜索</button>
                                        </span>
                                    </form>
                                    <button type="button" onclick="javascript:window.location.href = '/admin/business/business_list';" class="btn btn-danger btn-sm  reset-btn pull-left" style="">刷新</button>
                                </div>
                            </div>
                        </div>
                        <div class="member-warn">
                            <div class="alert alert-warning">
                                共找到商户： <span class="alert-link"><?php echo count($result); ?></span> 个
                                <?php if(!empty($_GET['keywords'])): ?>
                                ，且以下是公司名包含 “<span class="alert-link"><?php echo $_GET['keywords']; ?></span>”&nbsp;&nbsp;
                                的商户
                                <?php endif; ?>
                            </div>
                        </div>
                        <table class="footable table table-stripped toggle-arrow-tiny" data-page-size="9999999" data-limit-navigation='10'>
                            <thead>
                                <tr>
                                    <th>序号</th>
                                    <th>商户ID</th>
                                    <th>公司名</th>
                                    <th>法人姓名</th>
                                    <th>手机号</th>
                                    <th>积分商城名称</th>
                                    <th>当前共享币</th>
                                    <th>激活状态</th>
                                    <th>注册时间</th>
                                    <th style="min-width:249px;">操作</th>
                                </tr>
                            </thead>
                            <tbody>
                                    
                                <?php foreach ($result as $key => $value): ?>
                                <tr>
                                    <td><?php echo $key+1; ?></td>
                                    <td><?php echo $value['business_id'] ?></td>
                                    <td><?php echo $value['company_name'] ?></td>
                                    <td><?php echo $value['legal_name'] ?></td>
                                    <td><?php echo $value['phone_num'] ?></td>
                                    <td><?php echo $value['exchange_name'] ?></td>
                                    <td><?php echo $value['piao'] ?></td>
                                    <td><?php echo $value['status'] == 1 ? '已激活' : '未激活'; ?></td>
                                    <td><?php echo $value['add_time'] ?></td>
                                    <td>
                                        <a href="/admin/business/business_list_detail?business_id=<?php echo $value['business_id'] ?>&back=true" style="margin-right: 10px;">
                                            <span class="label label-warning">商户资料</span>
                                        </a>
                                        <a href="/admin/business/recommend_list?business_id=<?php echo $value['business_id'] ?>&back=true&is_start=1&recommend=<?php echo $value['business_id'] ?>" style="margin-right: 10px;">
                                            <span class="label label-success">推荐下线</span>
                                        </a>
                                        <a href="javascript:dai_business(<?php echo $value['business_id'] ?>);" is_dai="<?php echo $value['is_dai']; ?>" bus_id="<?php echo $value['business_id'] ?>" style="margin-right: 10px;">
                                            <?php if ($value['is_dai'] == 1 && $value['business_id'] != '10001'): ?>
                                            <span class="label label-danger">取消代理商</span>
                                            <?php elseif($value['business_id'] != '10001'): ?>
                                            <span class="label label-primary">设为代理商</span> 
                                            <?php endif ?>
                                            
                                        </a>
                                    </td>
                                </tr>
                                <?php endforeach ?>
                         
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td colspan="12">
                                        <div class="b-page">
                                            <?php echo $page['page']; ?>
                                        </div>
                                    </td>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>

<script>
    $(document).ready(function(){$(".footable").footable();});
    var flag = false;
    function dai_business(business_id){

        var _this = $('a[bus_id='+business_id+']');
        var is_dai = _this.attr('is_dai');
        if (is_dai == 1) {
            var msg = '取消代理商';
            var span_html = '设为代理商';
            var span_class = 'label label-primary';
        }else{
            var msg = '设为代理商';
            var span_html = '取消代理商';
            var span_class = 'label label-danger';
        }

        swal({
            title: "确定将 “"+business_id+"” "+msg+"吗？",
            text: "",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "我确定",
            cancelButtonText: "我再考虑考虑...",
            closeOnConfirm: false,
            closeOnCancel: true
            },
            function(isConfirm) {
                if (isConfirm) {
                    
                    $.post('/admin/business/dai_business',{"business_id":business_id,"is_dai":is_dai},function(d){
                        if(d.error){
                            flag = false;
                            swal(d.msg, "", "error");
                            return false;
                        }else{
                           if (flag) {
                                return false;
                            }
                            flag = true;
                            _this.children("span").html(span_html);
                            if (is_dai==1) {
                                _this.attr('is_dai',0);
                            }else{
                                _this.attr('is_dai',1);
                            }
                            _this.children("span").attr('class','');
                            _this.children("span").attr('class',span_class);
                            flag = false;
                            swal(d.msg, "", "success");
                            return false;
                        }
                    },'json');          
                }
            }
        )
    }
</script>