<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<style>
.jiaobiao {
    position: absolute;
    right: 115px;
    top: 7px;
}
.jiaobiao-right{
   position: absolute;
    right: 0px;
    top: 13px;
    padding: 2px 4px;
    font-size: 6px;
}
</style>
<body class="fixed-sidebar full-height-layout gray-bg" style="overflow:hidden">
    <div id="wrapper">
        <!--左侧导航开始-->
        <nav class="navbar-default navbar-static-side" role="navigation">
            <div class="nav-close"><i class="fa fa-times-circle"></i>
            </div>
            <div class="sidebar-collapse">
                <ul class="nav" id="side-menu">
                    <li class=" nav-header">
                        <div class="dropdown profile-element">
                            <span><img id="admin_logo" alt="image" title="在这里共享商企平台" class="img-circle" width="64" height="64" src="/Public/hplus/img/black_logo.png" /></span>
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                                <span class="clear" style='padding-right: 10px;position: relative;'>
                                    <span class="text-muted text-xs block" style='max-width:170px;height: 30px;overflow: hidden;' title="<?php echo $info['name']; ?>"><?php echo $info['name']; ?></span>
                                    <b class="caret" style="position: absolute;top: 14px;right: 0;"></b>
                                </span>
                            </a>
                            <ul class="dropdown-menu animated fadeInRight m-t-xs">
                                <li><a href="/admin/Log/out">安全退出</a>
                                </li>

                            </ul>
                        </div>
                        <div class="logo-element">在这里共享商企平台
                        </div>
                    </li>
                    <li>
                        <a class="J_menuItem" href="/admin/Index/index_base">
                            <i class="fa fa-home"></i>
                            <span class="nav-label">首页</span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                        <i class="fa fa-yen"></i>
                        <span class="nav-label">财务管理</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li><a class="J_menuItem" href="/admin/finance/finance_check">提现审核</a></li>
                            <li><a class="J_menuItem" href="/admin/finance/finance_check_log">提现审核记录</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-edit"></i> <span class="nav-label">系统管理</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li><a class="J_menuItem" href="/admin/system/system_mange">系统配置</a></li>
                        </ul>
                    </li>
                    <li class="">
                        <a href="#"><i class="fa fa-tag"></i><span class="nav-label">订单管理</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level collapse" aria-expanded="false" style="height: 0px;">
                            <li><a class="J_menuItem" href="/admin/order/return_orders" data-index="17">退货订单仲裁</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-desktop"></i> <span class="nav-label">商户管理</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a class="J_menuItem" href="/admin/business/business_list">商户列表</a>
                            </li>
                            <li>
                                <a class="J_menuItem" href="/admin/business/business_info_check">商户资料审核</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
        <!--左侧导航结束-->
        <!--右侧部分开始-->
        <div id="page-wrapper" class="gray-bg dashbard-1">
            <div class="row content-tabs">
             <div class="navbar-header"><a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
                      
                    </div>
                <button class="roll-nav roll-left J_tabLeft"><i class="fa fa-backward"></i>
                </button>
                <nav class="page-tabs J_menuTabs">
                    <div class="page-tabs-content">
                        <!-- <a href="javascript:;" class="active J_menuTab" data-id='/admin'>首页</a> -->
                    </div>
                </nav>
                <button class="roll-nav roll-right J_tabRight" style="margin-right: -173px;"><i class="fa fa-forward" style=""></i>
                </button>
                <div class="btn-group roll-nav roll-right" style="margin-right: -173px;">
                    <button class="dropdown J_tabClose" data-toggle="dropdown">关闭操作<span class="caret"></span>

                    </button>
                    <ul role="menu" class="dropdown-menu dropdown-menu-right">
                        <li class="J_tabShowActive"><a>定位当前选项卡</a>
                        </li>
                        <li class="divider"></li>
                        <!-- <li class="J_tabCloseAll"><a>关闭全部选项卡</a> -->
                        <!-- </li> -->
                        <li class="J_tabCloseOther"><a>关闭其他选项卡</a>
                        </li>
                    </ul>
                   
                </div>
                 <ul class="nav navbar-top-links navbar-right" style="margin-right: -30px;">
                    <li class="dropdown ">
                        <a class="right-sidebar-toggle" aria-expanded="false">
                            <i class="fa fa-tasks"></i> 主题
                        </a>
                    </li>
                </ul>
            </div>
            <div class="row J_mainContent" id="content-main">
                <iframe class="J_iframe" name="iframe0" width="100%" height="100%" src="/admin/Index/index_base" frameborder="0"  seamless></iframe>
            </div>
            <div class="footer">
                <div class="">&copy; 在这里共享商企平台 版权所有</a>
                </div>
            </div>
        </div>
        <!--右侧部分结束-->
        <!--右侧边栏开始-->
        <div id="right-sidebar">
            <div class="sidebar-container">
                <div class="tab-content">
                    <div id="tab-1" class="tab-pane active">
                      
                        <div class="skin-setttings">
                            <div class="title">主题设置</div>
                            <div class="setings-item">
                                <span>收起左侧菜单</span>
                                <div class="switch">
                                    <div class="onoffswitch">
                                        <input type="checkbox" name="collapsemenu" class="onoffswitch-checkbox" id="collapsemenu">
                                        <label class="onoffswitch-label" for="collapsemenu">
                                            <span class="onoffswitch-inner"></span>
                                            <span class="onoffswitch-switch"></span>
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <div class="setings-item">
                                <span>固定顶部</span>

                                <div class="switch">
                                    <div class="onoffswitch">
                                        <input type="checkbox" name="fixednavbar" class="onoffswitch-checkbox" id="fixednavbar">
                                        <label class="onoffswitch-label" for="fixednavbar">
                                            <span class="onoffswitch-inner"></span>
                                            <span class="onoffswitch-switch"></span>
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <div class="setings-item">
                                <span>固定宽度</span>
                                <div class="switch">
                                    <div class="onoffswitch">
                                        <input type="checkbox" name="boxedlayout" class="onoffswitch-checkbox" id="boxedlayout">
                                        <label class="onoffswitch-label" for="boxedlayout">
                                            <span class="onoffswitch-inner"></span>
                                            <span class="onoffswitch-switch"></span>
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <div class="title">皮肤选择</div>
                            <div class="setings-item default-skin nb">
                                <span class="skin-name ">
                         <a href="#" class="s-skin-0">
                             绿色主题
                         </a>
                    </span>
                            </div>
                            <div class="setings-item  blue-skin  nb">
                                <span class="skin-name ">
                        <a href="#" class="s-skin-1">
                            蓝色主题
                        </a>
                    </span>
                            </div>
                            <div class="setings-item yellow-skin nb">
                                <span class="skin-name ">
                        <a href="#" class="s-skin-3">
                            黄色主题
                        </a>
                    </span>
                            </div>
                        </div>
                    </div>
                
                </div>

            </div>
        </div>
    </div>
   
</body>
<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>