<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<style>
	.rechargeTable tr th,.rechargeTable tr td{
		text-align: center;
	}
	.good-img{
		width: 50px;
		height: 50px;
		display: block;
	}
	table{
	    font-size: 13px;
	}
	.footable-row-detail-name {
	    display: table-cell;
	    font-weight: bold;
	    padding-right: 0.5em;
	    line-height: 30px;
	}
	.contact-box {
	    background-color: #fff;
	    border: 1px solid #e7eaec;
	    padding: 20px;
	    margin-bottom: 20px;
	    min-width: 275px;
	}
	.img-responsive{
	    min-width: 70px;
	    min-height: 70px;
	}
	.form-select{
		width: 55%;
	}
    .search-btn{
        margin-top: -15px;
    }
	.selectBody{
		margin-bottom: 30px;
	}
</style>
<body class="gray-bg">
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
           
            <div class="col-sm-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>共享币明细</h5>
                    </div>
                    <div class="ibox-content">
						<div class="row">
                            <div class="col-sm-12">
                                <div class="input-group col-sm-12">
                                    <form method="get" action="/Business/Finance/piao_log" class="clearfix pull-left" style="width:60%;" >
                                        <div class="form-group" style="width:53%;">
                                        <label class="col-sm-4 control-label" style="padding-right: 0;margin-top: 6px;">按日期：</label>
                                        <div class="col-sm-8"  style="padding-left: 0;padding-right: 10px;">
                                            <input placeholder="开始日期" name="start_time" value="<?php echo $_GET['start_time'] ?>" class="form-control layer-date" id="start" style="width:50%;height: 30px;" >
                                            <input placeholder="结束日期" name="end_time" value="<?php echo $_GET['end_time'] ?>" class="form-control layer-date " id="end" style="width:50%;height: 30px;" >
                                        </div>
                                        </div>
                                        <select name="type" class="input-sm form-control pull-left col-sm-4 sex-select " style="width: 20%;margin-top: -15px;margin-right: 10px;">
                                            <option value="0">类型</option>
                                            <option disabled="true">--------------------</option>
                                            <option value="1" <?php echo $_GET['type'] == 1 ? 'selected' : ''; ?>>增加</option>
                                            <option value="2" <?php echo $_GET['type'] == 2 ? 'selected' : ''; ?>>扣除</option>
                                        </select>
                                        <select name="description" class="input-sm form-control pull-left col-sm-4 sex-select " style="width: 20%;margin-top: -15px;">
                                            <option value="0">说明</option>
                                            <option disabled="true">--------------------</option>
                                            <option value="发放共享币" <?php echo $_GET['description'] == '发放共享币' ? 'selected' : ''; ?>>发放共享币</option>
                                            <option value="充值成功" <?php echo $_GET['description'] == '充值成功' ? 'selected' : ''; ?>>充值成功</option>
                                            <option value="提现成功" <?php echo $_GET['description'] == '提现成功' ? 'selected' : ''; ?>>提现成功</option>
                                            <option value="推荐奖励" <?php echo $_GET['description'] == '推荐奖励' ? 'selected' : ''; ?>>推荐奖励</option>
                                            <option value="活动支出" <?php echo $_GET['description'] == '活动支出' ? 'selected' : ''; ?>>活动支出</option>
                                            <option value="返利所得" <?php echo $_GET['description'] == '返利所得' ? 'selected' : ''; ?>>返利所得</option>
                                            <option value="出售所得" <?php echo $_GET['description'] == '出售所得' ? 'selected' : ''; ?>>出售所得</option>
                                        </select>
                                        <span class="input-group-btn pull-left " >
                                            <button type="submit" class="btn btn-sm btn-primary search-btn"  style="margin-top: -15px;"> 搜索</button>
                                        </span>
                                    </form>
                                    <button type="button" onclick="javascript:window.location.href = '/Business/Finance/piao_log';" class="btn btn-danger btn-sm  reset-btn pull-left">刷新</button>
                                </div>
                            </div>
                        </div>
                        <div class="member-warn">
                            <div class="alert alert-warning">
                                提示：这里面包含了您：充值成功、提现成功、发放共享币、推荐奖励、活动支出、返利所得，等涉及到共享币变动的所有情况。
                            </div>
                        </div>
                        <table class="table table-striped table-hover rechargeTable">
                            <thead>
                                <tr>
                                    <th>序号</th>
                                    <th>类型</th>
                                    <th>会员手机号</th>
                                    <th>订单号</th>
                                    <th>共享币数</th>
                                    <th>说明</th>
                                    <th>时间</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach($result as $k => $v): ?>
                                <tr>
                                    <td><?php echo $k + 1 + $page['firstRow']; ?></td>
                                    <td><span class=""><?php echo $v['type'] == 1 ? '<span style="color:green">增加</span>' : '<span style="color:red">扣除</span>'; ?></span></td>
                                    <td><span class=""><?php echo $v['phone_num'] ? $v['phone_num'] : '-'; ?></span></td>
                                    <td><span class=""><?php echo $v['order_sn'] ? $v['order_sn'] : '-'; ?></span></td>
                                    <td><?php echo $v['piao'];?></td>
                                    <td><?php echo $v['description'];?></td>
                                    <td><?php echo $v['add_time'];?></td>
                                </tr>
                                <?php endforeach; ?>
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td colspan="12">
                                        <div class="b-page">
                                            <?php echo $page['page']; ?>
                                        </div>
                                    </td>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>

<script>
    $(document).ready(function(){
        $(".footable").footable();
        $('#myModal').modal({
            keyboard: false,
            backdrop:false,
            show:false
        });
        var start = {
            elem: "#start",
            format: "YYYY/MM/DD",
            min:  "2011-06-16 23:59:59",
            max: laydate.now(),
            istime: false,
            istoday: false,
            choose: function(datas) {
                end.min = datas;
                end.start = datas
            }
        };
        var end = {
            elem: "#end",
            format: "YYYY/MM/DD",
            min: "2011-06-16 23:59:59",
            max: laydate.now(),
            istime: false,
            istoday: false,
            choose: function(datas) {
                start.max = datas
            }
        };
        laydate(start);
        laydate(end);
    });
</script>