<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>

<style>
.good-img{
	width: 50px;
	height: 50px;
	display: block;
}
table{
    font-size: 13px;
}
.footable-row-detail-name {
    display: table-cell;
    font-weight: bold;
    padding-right: 0.5em;
    line-height: 30px;
}
</style>

<body class="gray-bg">
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-sm-12">
                <div class="ibox float-e-margins" style="margin-bottom: 0;">
                    <div class="ibox-title">
                        <h5>共享币提现</h5>
                        <span class="label label-primary pull-right label-primary-cust">
                            <?php if($_GET['back'] == 'true'): ?>
                            <a href="javascript:history.back(-1);" class="fa-lg-cust-a" title="返回上一页">
                                <i class="fa fa-arrow-left fa-lg-cust"  aria-hidden="true"></i>
                            </a>
                            <?php endif; ?>
                        </span>
                    </div>
                    <div class="ibox-content" style="padding: 12px 20px 1px;">
                        <div class="member-warn">
                            <div class="alert alert-warning">
                                <?php $security = $security * 10; ?>
                                提示：您现在共有共享币 <span class="alert-link"><?php echo $piao+$security; ?></span> 个<?php echo $security > 0 ? "（含保证金 {$security} 个）" : ''; ?>，提现共享币数不可超过 <?php echo $piao; ?> 个，提现操作我们将会收取 <?php echo $poundage * 100; ?>% 的手续费，我们将会在 24 小时内完成您的提现。
                            </div>
                        </div>
                    </div>
                    <div class="ibox-title" style="border: none;padding: 20px 21px 7px;min-height: 44px;">
                        <h5>请选择提现银行卡账户</h5>
                    </div>
                    <div class="ibox-content" style="padding: 12px 20px 1px;">
                        <table class="footable table table-stripped toggle-arrow-tiny" style="margin-bottom: 0;">
                            <?php if(count($bank) > 0): ?>
                            <thead>
                                <tr>
                                    <th></th>
                                    <th>银行账户</th>
                                    <th>收款人姓名</th>
                                    <th>收款人卡号</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach($bank as $v): ?>
                                <tr>
                                    <td>
                                        <div bank_card_id="<?php echo $v['bank_card_id']; ?>" class="radio i-checks mycheck">
                                            <input type="radio" value="<?php echo $v['bank_card_id']; ?>" name="bank_card_id">
                                        </div>
                                    </td>
                                    <td><?php echo $v['bank_name']; ?></td>
                                    <td><?php echo $v['card_name']; ?></td>
                                    <td><?php echo $v['card_number']; ?></td>
                                </tr>
                                <?php endforeach; ?>
                            </tbody>
                            <?php else: ?>
                            <tr>
                                <td><i class="fa fa-info-circle" style="color: #ff4400"></i> 请先通过左侧菜单绑定至少一张银行卡</td>
                            </tr>
                            <?php endif; ?>
                        </table>
                    </div>
                     <div class="ibox-title" style="border: none;padding: 20px 21px 7px;min-height: 44px;">
                        <h5>请输入提现共享币数</h5>
                    </div>
                    <div class="ibox-content" style="padding: 12px 20px 1px;border: none;">
					    <div class="form-group clearfix">
					        <div class="col-sm-12">
					            <input type="text" name="piao" class="form-control mypiao-count" placeholder="请输入提现共享币数">
					             <span class="help-block m-b-none">
                                    <i class="fa fa-info-circle" style="color: #ff4400"></i> 可提现共享币：<span><?php echo $piao; ?> </span>个。
                                </span> 
					        </div>
					    </div>
                    </div>
                    <div class="ibox-title" style="border: none;padding: 20px 21px 7px;min-height: 44px;">
                        <h5>实际到账金额</h5>
                    </div>
                    <div class="ibox-content" style="padding: 12px 20px 1px;border: none;">
					    <div class="form-group clearfix">
					        <div class="col-sm-12">
					            <input type="text" class="form-control re-count" disabled> 
					            <span class="help-block m-b-none"><i class="fa fa-info-circle" style="color: #ff4400"></i> 共享币兑现金的比率为 10 : 1，我们将收取 <?php echo $poundage * 100; ?>% 的提现手续费。</span>
					        </div>
					    </div>
                    </div>
                </div>
                <div style="width: 100%; height: 100px;background: #fff;line-height: 65px;text-align: center;">
				    <button type="button" class="btn btn-danger end-btn" onclick="javascript:enterUnPay();" style="padding:10px 50px;font-size: 18px;">确认提现</button>
				</div>
            </div>
        </div>
    </div>
</body>

<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>

<script>
   
    $(document).ready(function(){
    	$(".footable").footable();
    	$(".i-checks").iCheck({checkboxClass:"icheckbox_square-green",radioClass:"iradio_square-green",});
    });
     $('.mypiao-count').bind('keyup change',function () {
     var mypiaoCount=$(this).val();
     $('.re-count').val(parseFloat((mypiaoCount/10*(1-<?php echo $poundage; ?>))).toFixed(2));
    })
 
    //确定提现
    function enterUnPay(){
        if( $('.mypiao-count').val()==''){
             swal('请填全所需信息', "", "warning");
             return;
        }
        swal({
            title: "确定要进行本次共享币提现吗？",
            text: "",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "检查无误，确认",
            cancelButtonText: "取消",
            closeOnConfirm: false,
            closeOnCancel: true
        },
        function(isConfirm) {
            if (isConfirm) {
                $.ajax({
                    cache: true,
                    type: "POST",
                    url:"/Business/Finance/withdraw",
                    data:{bank_card_id:$('.mycheck').children('.iradio_square-green.checked').children('input').val(),piao:$('input[name=piao]').val()},
                    dataType: 'json',
                    async: false,
                    error: function(data) {
                       swal('网络错误，请重试！', "", "warning");
                    },
                    success: function(data) {
                        if (data.error == 0) {
                            swal(data.msg, "请按F5键刷新网页查看最新余额", "success");
                            return false;
                        }else{
                            swal(data.msg, "", "error");
                            return false;
                        }
                    }
                });
            }
        })
    }

</script>