<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title><?php echo isset($exchange_name)?$exchange_name.' - ':''; ?>共享币共享商城</title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
<link rel="stylesheet" href="/Public/mobile/lib/weui.min.css">
<link rel="stylesheet" href="/Public/mobile/css/jquery-weui.css">
<link rel="stylesheet" href="/Public/mobile/css/style.css">
</head>