<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<body>
<div class="common-person-content">
    <div class="com-header">
        <div class="com-head-left">
            <a href="/Hospital/My" class="fa fa-angle-left"></a>   <span>我的挂号</span>
        </div>

    </div>
    <div class="myreg-content">
        <ul class="myreg-list">
            <?php foreach ($result as $key => $value): ?>
            <li class="clearfix" onclick="window.location.href='/Hospital/My/register_info?registration_id=<?php echo $value['registration_id'] ?>'">
                <div class="li-left">
                    <img src="<?php echo $value['head_img'] ?>" alt="">
                </div>
               <div class="li-moddle">
                   <p class="li-m-name"><?php echo $value['doctor_name'] ?></p>
                   <?php if (mb_strlen($value['hospital_name'])>9) {
                       $value['hospital_name'] = mb_substr($value['hospital_name'],0,9,'utf-8').'...';
                   }?>
                   <p><?php echo $value['hospital_name'] ?></p>
               </div>
               <div class="li-right">
                <?php 
                    switch ($value['is_status']) {
                        case 1:
                            $status = '已成功';
                            $style = 'style="color:#0062CC"';
                            break;
                        
                        case 2:
                            $status = '已取消';
                            $style = 'style="color:#DD524D"';
                            break;
                    }
                ?>
                   <p class="state" <?php echo $style ?>><?php echo $status ?></p>
                    <p class="li-time"><?php echo $value['create_time'] ?></p>

               </div>
            </li>
            <?php endforeach ?>
        </ul>
    </div>
    <div class="myAdvice-bot">
        已经全部加载完毕
    </div>
</div>

</body>
<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>