<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<body>
<style type="text/css">
    body{
        background-color: #fff;
    }
</style>
<div class="regist-all">
    <div class="re-it">
        <div class="re-t mi-re-t">
            <a href="/Hospital/My">
                <div class="mi-return"></div>
            </a>
            <span class="login-l">修改密码</span>
        </div>
    </div>
    <div class="mi-re-body">
    <form>
        <input type="password" class="re-in-tel" name="password" id="password" placeholder="新密码">
        <div class="re-ipb">
            <input type="password" class="re-in-pas" id="repassword" placeholder="重复新密码">
        </div>
    </form>
    </div>
    <div class="re-ck-but mi-ck-but">
        <input type="button" onclick="javascript:rePassword();" class="re-in-but" value="提交修改">
    </div>
</div>
<script>
    function rePassword(){
        if($('#password').val() != $('#repassword').val()){
            alert('两次密码不相同');
            return false;
        }
        $.post('/Hospital/My/repassword',{data:$('form').serialize()},function(d){
            d = eval('('+ d +')');
            if(d.error){
                alert(d.msg);
                return false;
            }else{
                alert(d.msg);
                window.location.href = "/Hospital/My";
            }
        },'text');
    }
</script>
</body>
<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>