<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<style type="text/css">
    .common-person-content .com-con-foot {
        height: 1rem;
        line-height: 1rem;
        padding: 0.4rem 0.45rem;
        margin-top: 1.5rem; 
        border-top: none;
    } 
</style>
<body>
<div class="common-person-content">
    <div class="com-header">
        <div class="com-head-left">
            <a href="/Hospital/My/patients" class="fa fa-angle-left"></a>   <span>查看就诊人</span>
        </div>

    </div>
    <div class="com-con-see">
        <div class="see-per-content">
            <span class="see-left f_l">姓名</span>  <span class="see-right f_r"><?php echo $result['patients_name'] ?></span>
        </div>
        <!-- <div class="see-per-content">
            <span class="see-left f_l">性别</span>  <span class="see-right f_r">女</span>
        </div> -->
        <div class="see-per-content">
            <span class="see-left f_l">身份证号</span>  <span class="see-right f_r"><?php echo $result['id_card'] ?></span>
        </div>
        <div class="see-per-content">
            <span class="see-left f_l">年龄</span>  <span class="see-right f_r"><?php echo $result['patients_age'] ?></span>
        </div>
        <div class="see-per-content last">
            <span class="see-left f_l">手机号码</span>  <span class="see-right f_r"><?php echo $result['patients_phone'] ?></span>
        </div>
    </div>
    <div class="com-con-foot">
        <a href="/Hospital/My/edit_patients?patients_id=<?php echo $_GET['patients_id'] ?>" class="foot-left f_l" style="text-align:center;">编辑</a>
        <a href="javascript:del_patients(<?php echo $result['patients_id'] ?>);" class="foot-right f_r" style="text-align:center;">删除</a>

    </div>
</div>
</body>
<script type="text/javascript">
    function del_patients(e){
        if(confirm('是否确认删除就诊人？')){
            window.location.href="/Hospital/My/del_patients?patients_id="+e;
        }
    }
</script>
<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>