<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<body>
<style type="text/css">
    body{
        background-color: #fff;
    }
    .mona-ipb input{
        font-size: 0.4rem;
    }
    .regist-all .re-it .re-t a{
        height: 1.45rem;
    }
    input[type=radio] {
        margin-top: 0.48rem;
    }
    .regist-all .re-it .re-t a {
        height: 1.45rem;
        margin-top: -0.13rem;
    }
</style>
<div class="regist-all">
    <div class="re-it">
        <div class="re-t mona-re-t">
            <a href="/Hospital/My">
                <i class="fa fa-angle-left f_l" aria-hidden="true"></i> 
            </a>
            <span class="login-l">修改信息</span>
        </div>
    </div>
    <div class="mona-borer">
        <iframe style="width: 1px;height: 1px;display:block;position:fixed;bottom:1px;opacity:0.1" name="iframeUpload"></iframe>
        <form method="post" target="iframeUpload" enctype="multipart/form-data">
            <div class="sw_logo">
                    <input type="file" id="logofile" value="<?php echo $res['headimg_path']; ?>" name="headimg_path" class="in_file">
                    <img class="imgLogo" src="<?php echo $base64_con; ?>">
                <span class="mona-p imgLogo" style="height: 0.5rem;top: 2.5rem;background-color: rgba(255, 193, 7, 0.34);padding: 0rem;margin: 0rem;line-height: 0.5rem;font-size: 0.2rem;color: #FFF;text-align: center;">修改头像</span>
            </div>  
            <div class="mona-ipb">
                <span class="mona-p">电话:</span>
                <input type="text" class="mona-nicheng" placeholder="" value="<?php echo $res['phone_num']; ?>" disabled="true">
            </div>
            <div class="mona-ipb">
                <span class="mona-p">昵称:</span>
                <input type="text" class="mona-nicheng" placeholder="" value="<?php echo $res['nick_name']; ?>" name="nick_name">
            </div>
            <div class="mona-sex">
                <span class="mona-p">性别:</span>
                &nbsp;&nbsp;
                <input type="radio" value="1" class="sex" <?php echo $res['sex'] == '1' ? 'checked' : ''; ?> name="sex">男
                &nbsp;&nbsp;&nbsp;&nbsp;
                <input type="radio" value="0" class="sex" <?php echo $res['sex'] == '0' ? 'checked' : ''; ?> name="sex">女
            </div>
            <div class="mona-ipb">
                <span class="mona-p">生日:</span>
                <input type="date" value="<?php echo $res['birthday']; ?>" name="birthday" class="birthday">
            </div>
            <div class="re-ck-but mona-ck-but">
                <button class="re-in-but">保存</button>
            </div>
        </form>
    </div>
</div>
<script>
    $("#logofile").on('change', function () {
        fileToBase64($(this), function (imgBase64) {
            $('.imgLogo').attr('src', imgBase64);
        });
    });
    function fileToBase64(file, callback, outputFormat) {
        var file = file[0];
        if (file.files && file.files[0]) {
            var reader = new FileReader();
            reader.onload = function (evt) {
                callback.call(this, evt.target.result);
            }
            reader.readAsDataURL(file.files[0]);
        }
    }
</script>
</body>
<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>