
<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<style>

</style>
  <style type="text/css">
.goods-img{
     height: 10em;
    width: 100%;
    padding: 10px;
}
#add-img{
   width: 0;
   height: 0;
}
.addback-img {
    display: inline-block;
    width: 100px;
    height: 100px;
    border: 1px solid #ccc;
    margin-right: 10px;
}

.imgBox{
    float: left;
    position: relative;
}
.file-edit{
    width: 100px;
    height: 40px;
    background:rgba(0,0,0,0.2);
    position: absolute;
    left:0;
    top:0;
    display: none;
}
.del-i{
    position: absolute;
    right: 10px;
    /*top:5px;*/
    line-height: 40px;
    /*margin-right: -17.5px;*/
    text-align: center;
    color: #fff;
    font-size:25px;
}
.imgBox:hover .file-edit{
    display: block;
} 



    </style>
<body class="gray-bg">
    <div class="wrapper wrapper-content animated fadeInRight">

        <div class="row">
         
            <div class="col-sm-12">
                <div class="ibox float-e-margins business-info">
                    <div class="ibox-title">
                            <h5>修改商城</h5>
                    </div>
                    <div class="ibox-content">
                        <form class="form-horizontal m-t" id="signupForm">
                            <div class="form-group">
                                <label class="col-sm-3 control-label">商城名称</label>
                                <div  class=" col-sm-8" >
                                    <input type="text" name="exchange_name" class="form-control" style="width:300px;" value="<?php echo $exchange_name; ?>">
                                </div>
                            </div> 
                            <div class="form-group">
                                <label class="col-sm-3 control-label">上传店标</label>
                                <div  class=" col-sm-8" >
                                    <div class="goods-img">
                                        <div class="showimg"> 
                                        </div>
                                        <img class="addback-img" src="<?php echo $now_pic; ?>"    onclick="getElementById('add-img').click()" style="cursor:pointer; border: none;" title="点击添加图片" alt="点击添加图片">
                                        <input id="add-img" type="file" name="logo" >
                                    </div> 
                                <span class="help-block m-b-none"><i class="fa fa-info-circle"></i> 点击图片修改店标</span>
                                </div>
                            </div> 
                              <div class="form-group form-group-bottom clearfix">

                                <div class="col-sm-2 col-sm-offset-3" style='float: left;'>
                                    <p id="signupForm_submit" class="btn btn-primary ">确定修改</p>
                                </div>
                                
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </body>
    <?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>
    <script type="text/javascript">
    window.onload=function(){
        window.parent.get_notices_num(); 

    }
    var _thisFile;
    function getObjectURL(file) {
            var url = null;
            if (window.createObjectURL != undefined) {
                url = window.createObjectURL(file)
            } else if (window.URL != undefined) {
                url = window.URL.createObjectURL(file)
            } else if (window.webkitURL != undefined) {
                url = window.webkitURL.createObjectURL(file)
            }
            return url
        };
    $("#add-img").on('change', function () {
        if($('.showimg .imgBox').length>=1){
            swal('您只能上传一张图片', "", "warning");
            return false;
        }
        var _this = this;
        _thisFile = _this.files[0];
        var srcs=getObjectURL(_thisFile);
        if (!$(_this).val()) {
            return false;
        }
        $('.addback-img').attr('src',srcs)
        $(_this).val(''); 
    });
    
        $('#signupForm_submit').click(function(){
            var formData = new FormData();
            formData.append('file',_thisFile);
            formData.append('exchange_name',$("input[name=exchange_name]").val());
            $.ajax({
                cache: true,
                type: "POST",
                url:"/Business/Center/edit_logo",
                data:formData,
                dataType: 'json',
                async: false,
                processData: false,
                contentType: false,
                error: function(data) {
                    swal('网络错误，请重试！', "", "error");
                    return false;
                },
                success: function(data) {      
                    if (data.error == 0) {
                        swal(data.error, "", "success");
                        setTimeout("window.location.reload();",1000);
                        return false;
                    }else if(data.error == 2){
                        swal(data.msg, "", "error");
                        return false;
                    }else{
                        swal(data.msg, "", "warning");
                        return false;
                    }
                }
            });
        });
    
    </script>


