<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>


<body class="gray-bg">
    <div class="wrapper wrapper-content animated fadeInRight">
      
        <div class="row">
           
            <div class="col-sm-12">
                <div class="ibox float-e-margins">
                     <div class="ibox-title">
                        <h5>公告</h5>
                        <span class="label label-primary pull-right label-primary-cust">
                            <?php if($_GET['back'] == 'true'): ?>
                            <a href="javascript:history.back(-1);" class="fa-lg-cust-a" title="返回上一页">
                                <i class="fa fa-arrow-left fa-lg-cust"  aria-hidden="true"></i>
                            </a>
                            <?php endif; ?>
                        </span>
                    </div>
                    <div class="ibox-content">

                        <table class="table table-hover placard-table">
                            <thead>
                                <tr>
                                    <th>序号</th>
                                    <th>标题</th>
                                    <th>时间</th>
                                    <th>操作</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach($result as $k => $v): ?>
                                <tr>
                                    <td><?php echo $k + 1 + $page['firstRow']; ?></td>
                                    <td><span><?php echo $v['placard_title']; ?></span></td>
                                    <td><?php echo $v['add_time']; ?></td>
                                    <td><a href="/Business/Center/placard_detail?placard_id=<?php echo $v['placard_id']; ?>">
                                            <span class="label label-primary ">查看</span>
                                        </a>
                                    </td>
                                </tr>
                                <?php endforeach; ?>
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td colspan="12">
                                        <div class="b-page">
                                            <?php echo $page['page']; ?>
                                        </div>
                                    </td>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        
    </div>

</body>
<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>