
<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
  <link rel="stylesheet" type="text/css" href="/Public/hplus/css/ycbootstrap.css"/>
  <link rel="stylesheet" type="text/css" href="/Public/hplus/css/reset.css"/>
  <style type="text/css">
.goods-img{
     height: 12em;
    width: 100%;
    padding: 10px;
}
#add-img{
   width: 0;
   height: 0;
}
.addback-img {
    display: inline-block;
    width: 100px;
    height: 100px;
    border: 1px solid #ccc;
    margin-right: 10px;
}

.imgBox{
    float: left;
    position: relative;
}
.file-edit{
    width: 100px;
    height: 40px;
    background:rgba(0,0,0,0.2);
    position: absolute;
    left:0;
    top:0;
    display: none;
}
.del-i{
    position: absolute;
    right: 10px;
    /*top:5px;*/
    line-height: 40px;
    /*margin-right: -17.5px;*/
    text-align: center;
    color: #fff;
    font-size:25px;
}
.imgBox:hover .file-edit{
    display: block;
} 
.defult-color{
    border: 2px solid blue
}

    </style>



<body class="gray-bg">
    <div class="wrapper wrapper-content animated fadeInRight">

        <div class="row">
         
            <div class="col-sm-12">
                <div class="ibox float-e-margins business-info">
                    <div class="ibox-title">
                            <h5>编辑商品</h5>
                            <span class="label label-primary pull-right label-primary-cust">
                                <a href="javascript:history.back(-1);" class="fa-lg-cust-a" title="返回上一页">
                                    <i class="fa fa-arrow-left fa-lg-cust"  aria-hidden="true"></i>
                                </a>
                            </span>
                    </div>
                    <div class="ibox-content">
                        <form class="form-horizontal m-t" id="signupForm">
                            <div class="form-group">
                                <label class="col-sm-3 control-label">商品名：</label>
                                <div class="col-sm-8">
                                    <input name="goods_name" class="form-control" value="<?php echo $goods_info['goods_name'] ?>" type="text" placeholder="请输入商品名称"  >
                                    <input type="hidden" name="goods_id" value="<?php echo $goods_info['goods_id']; ?>">
                                </div>
                            </div>
                             <div class="form-group">
                                <label class="col-sm-3 control-label">商品图：</label>
                               <!--  <div  class=" col-sm-8" >
                                    <div class="goods-img">
                                        <div class="showimg">
                                        <?php foreach (explode(';',$goods_info['pics']) as $k => $v): ?>
                                            <div class="imgBox" >
                                                <div class="file-edit">
                                                    <i class="fa fa-trash del-i"></i>
                                                </div>
                                                <img class="addback-img  <?php echo $k==0?'defult-color':''; ?>" src="<?php echo $v; ?>"  style="cursor:pointer;" >
                                                <input type="hidden" value="<?php echo $v; ?>" name="<?php echo $k==0?'imgs[default]':'imgs[]'; ?>"  >
                                            </div>
                                         <?php endforeach ?> 
                                        </div>
                                        <img class="addback-img" src="/Public/hplus/img/addback-img.jpg" onclick="getElementById('add-img').click()" style="cursor:pointer; border: none;" title="点击添加图片" alt="点击添加图片">
                                        <input id="add-img" type="file" name="image" >
                                    </div> 
                                <span class="help-block m-b-none"><i class="fa fa-info-circle"></i> 最多上传3张图片，第一张默认为显示主图(点击图片可更换默认主图)，上传图片比例为4:3时效果最佳！</span>
                                </div> -->
                                  <div class="col-md-8 col-sm-8 col-xs-8" style="padding-right:0;padding-left:15px;">
                                    <div style="min-height:1px;line-height:160px;text-align:center;position:relative;float: left;" ontouchstart="">
                                         <div class="cover-wrap1"  title='双击可旋转图片，滚动滚轮可缩放图片' style="display:none;position:fixed;left:0;top:0;width:100%;height:100%;background: rgba(0, 0, 0, 0.4);z-index: 10000000;text-align:center;">  
                                        
                                                        <div class="" style="width:900px;height:500px;margin:50px auto;background-color:#FFFFFF;overflow: hidden;border-radius:4px;position: relative;">
                                                         <i class="fa fa-close close_btn"  style="position: absolute;right: 20px;top: 20px;color: #fff;font-size: 30px;z-index: 10000000000000"></i> 
                                                            <div id="clipArea1" style="margin:10px;height: 420px;"></div>
                                                            <div class="" style="height:56px;line-height:36px;text-align: center;padding-top:8px;">
                                                                <span id="clipBtn1" style="width:120px;height: 36px;border-radius: 4px;background-color:#ff8a00;color: #FFFFFF;font-size: 14px;text-align: center;line-height: 36px;outline: none;display: inline-block;" >保存封面</span>
                                                            </div>
                                                        </div>
                                                          <input type="hidden" name='imgs[0]' value="">
                                          </div>
                                          <div id="view1" style="width:214px;height:160.5px;" title="请上传 428*321 的封面图片">

                                          </div>
                                          <div style="height:10px;"></div>
                                          <div class="" style="width:140px;height:32px;border-radius: 4px;background-color:#ff8a00;color: #FFFFFF;font-size: 14px;text-align:center;line-height:32px;outline:none;margin-left:37px;position:relative;">
                                                        点击更换封面主图
                                                        <input type="file" id="file1" style="cursor:pointer;opacity:0;filter:alpha(opacity=0);width:100%;height:100%;position:absolute;top:0;left:0;">
                                           </div>
                                    </div>
                                    <div style="min-height:1px;line-height:160px;text-align:center;position:relative;float: left;margin-left: 10px;" ontouchstart="">
                                         <div class="cover-wrap2"  title='双击可旋转图片，滚动滚轮可缩放图片' style="display:none;position:fixed;left:0;top:0;width:100%;height:100%;background: rgba(0, 0, 0, 0.4);z-index: 10000000;text-align:center;">   
                                        
                                                        <div class="" style="width:900px;height:500px;margin:50px auto;background-color:#FFFFFF;overflow: hidden;border-radius:4px;position: relative;">
                                                         <i class="fa fa-close close_btn"  style="position: absolute;right: 20px;top: 20px;color: #fff;font-size: 30px;z-index: 10000000000000"></i> 
                                                            <div id="clipArea2" style="margin:10px;height: 420px;"></div>
                                                            <div class="" style="height:56px;line-height:36px;text-align: center;padding-top:8px;">
                                                                <span id="clipBtn2" style="width:120px;height: 36px;border-radius: 4px;background-color:#ff8a00;color: #FFFFFF;font-size: 14px;text-align: center;line-height: 36px;outline: none;display: inline-block;" >保存封面</span>
                                                            </div>
                                                        </div>
                                                          <input type="hidden" name='imgs[1]' value="">
                                          </div>
                                          <div id="view2" style="width:214px;height:160.5px;" title="请上传 428*321 的商品图">

                                          </div>
                                          <div style="height:10px;"></div>
                                          <div class="" style="width:166px;height:32px;border-radius: 4px;background-color:#ff8a00;color: #FFFFFF;font-size: 14px;text-align:center;line-height:32px;outline:none;margin-left:23px;position:relative;">
                                                        点击更换第二张商品图
                                                        <input type="file" id="file2" style="cursor:pointer;opacity:0;filter:alpha(opacity=0);width:100%;height:100%;position:absolute;top:0;left:0;">
                                           </div>
                                    </div>
                                    <div style="min-height:1px;line-height:160px;text-align:center;position:relative;float: left;margin-left: 10px;" ontouchstart="">
                                         <div class="cover-wrap3"  title='双击可旋转图片，滚动滚轮可缩放图片' style="display:none;position:fixed;left:0;top:0;width:100%;height:100%;background: rgba(0, 0, 0, 0.4);z-index: 10000000;text-align:center;">    
                                         
                                                        <div class="" style="width:900px;height:500px;margin:50px auto;background-color:#FFFFFF;overflow: hidden;border-radius:4px;position: relative;">
                                                         <i class="fa fa-close close_btn"  style="position: absolute;right: 20px;top: 20px;color: #fff;font-size: 30px;z-index: 10000000000000"></i> 
                                                            <div id="clipArea3" style="margin:10px;height: 420px;"></div>
                                                            <div class="" style="height:56px;line-height:36px;text-align: center;padding-top:8px;">
                                                                <span id="clipBtn3" style="width:120px;height: 36px;border-radius: 4px;background-color:#ff8a00;color: #FFFFFF;font-size: 14px;text-align: center;line-height: 36px;outline: none;display: inline-block;" >保存封面</span>
                                                            </div>
                                                        </div>
                                                          <input type="hidden" name='imgs[2]' value="">
                                          </div>
                                          <div id="view3" style="width:214px;height:160.5px;" title="请上传 428*321 的商品图">
                                          </div>
                                          <div style="height:10px;"></div>
                                          <div class="" style="width:166px;height:32px;border-radius: 4px;background-color:#ff8a00;color: #FFFFFF;font-size: 14px;text-align:center;line-height:32px;outline:none;margin-left:23px;position:relative;">
                                                        点击更换第三张商品图
                                                        <input type="file" id="file3" style="cursor:pointer;opacity:0;filter:alpha(opacity=0);width:100%;height:100%;position:absolute;top:0;left:0;">
                                           </div>
                                    </div>
                                 </div>
                            </div>
                             <div class="form-group">
                                <label class="col-sm-3 control-label">商品描述：</label>
                                <div class="col-sm-8">
                                <textarea id="" name="description" class="form-control" rows="5" style="resize:none;" placeholder="请输入商品简介和规格" ><?php echo $goods_info['description'] ?></textarea>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">商品类型：</label>
                                <div class="col-sm-8">
                                   <select class="input-sm form-control input-s-sm inline" name="goods_type_id" style="height: 33px;">
                                        <option value="0">请选择商品类型</option>
                                        <?php foreach ($goods_types as $key => $value): ?>
                                        <option value="<?php echo $value['goods_type_id'] ?>" <?php echo $value['goods_type_id']==$goods_info['goods_type_id']?'selected="selected"':''; ?>><?php echo $value['goods_type_name'] ?></option>
                                        <?php endforeach ?>
                                    </select>
                                </div>
                            </div>
                             <div class="form-group">
                                <label class="col-sm-3 control-label">商品价格：</label>
                                <div class="col-sm-8">
                                    <input id="" name="piao" class="form-control" value="<?php echo $goods_info['piao'] ?>" type="text" maxlength="8" placeholder="请输入商品兑换价格" onkeyup="if(this.value.length==1){this.value=this.value.replace(/[^1-9]/g,'')}else{this.value=this.value.replace(/\D/g,'')}" onafterpaste="if(this.value.length==1){this.value=this.value.replace(/[^1-9]/g,'')}else{this.value=this.value.replace(/\D/g,'')}">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">库存数量：</label>
                                <div class="col-sm-8">
                                    <input id="" name="nums" class="form-control" value="<?php echo $goods_info['nums'] ?>" type="text" maxlength="8" placeholder="请输入商品库存数量" onkeyup="if(this.value.length==1){this.value=this.value.replace(/[^1-9]/g,'')}else{this.value=this.value.replace(/\D/g,'')}" onafterpaste="if(this.value.length==1){this.value=this.value.replace(/[^1-9]/g,'')}else{this.value=this.value.replace(/\D/g,'')}" >
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">返利百分比(%)：</label>
                                <div class="col-sm-8">
                                    <input id="" name="rebate" class="form-control" value="<?php echo $goods_info['rebate'] * 100; ?>" type="text" placeholder="请输入商品返利百分比（1-100之间的正整数）"   maxlength="3"  onkeyup="if(this.value.length==1){this.value=this.value.replace(/[^1-9]/g,'')}else{this.value=this.value.replace(/\D/g,'')}" onafterpaste="if(this.value.length==1){this.value=this.value.replace(/^([1-9]\/g,'')}else{this.value=this.value.replace(/\D/g,'')}">
                                </div>
                            </div>
                           <div class="form-group">
                                <label class="col-sm-3 control-label">上架状态：</label>
                                <div class="col-sm-8">
                                    <select class="input-sm form-control input-s-sm inline" name="status" style="height: 33px;">
                                        <option value="0">请选择上架状态</option>
                                        <option value="1" <?php echo $goods_info['status']==1?'selected="selected"':''; ?>>上架</option>
                                         <option value="2" <?php echo $goods_info['status']==2?'selected="selected"':''; ?>>下架</option>
                                    </select>
                                </div>
                            </div>
                             <div class="form-group">
                                <label class="col-sm-3 control-label">是否共享：</label>
                                <div class="col-sm-8">
                                    <select class="input-sm form-control input-s-sm inline" name="is_gx" style="height: 33px;">
                                        <option value="0">请选择是否共享</option>
                                        <option value="1" <?php echo $goods_info['is_gx']==1?'selected="selected"':''; ?>>是</option>
                                         <option value="2" <?php echo $goods_info['is_gx']==2?'selected="selected"':''; ?>>否</option>
                                       
                                    </select>
                                    
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">是否推荐：</label>
                                <div class="col-sm-8">
                                    <select class="input-sm form-control input-s-sm inline" name="is_jian" style="height: 33px;">
                                        <option value="0">请选择是否推荐</option>
                                        <option value="1" <?php echo $goods_info['is_jian']==1?'selected="selected"':''; ?>>是</option>
                                         <option value="2" <?php echo $goods_info['is_jian']==2?'selected="selected"':''; ?>>否</option>
                                       
                                    </select>
                                    
                                </div>
                            </div>

                            <div class="form-group form-group-bottom clearfix">

                                <div class="col-sm-2 col-sm-offset-3" style='float: left;'>
                                    <p id="signupForm_submit" class="btn btn-primary "> 保存 </p>
                                </div>
                                
                            </div>
                            </div>  
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>
     <script src="/Public/hplus/js/plugins/cover_js/iscroll-zoom.js"></script>
    <script src="/Public/hplus/js/plugins/cover_js/hammer.js" ></script>
    <script src="/Public/hplus/js/plugins/cover_js/lrz.all.bundle.js" ></script>
    <script src="/Public/hplus/js/plugins/cover_js/jquery.photoClip.min.js" ></script>
    <script type="text/javascript">
    //上传封面 
       var imgView1="<?php echo explode(';',$goods_info['pics'])[0]?explode(';',$goods_info['pics'])[0]:''; ?>"; 
       var imgView2="<?php echo explode(';',$goods_info['pics'])[1]?explode(';',$goods_info['pics'])[1]:''; ?>";
       var imgView3="<?php echo explode(';',$goods_info['pics'])[2]?explode(';',$goods_info['pics'])[2]:''; ?>"; 
        $('#view1').css('background-image',"url("+imgView1+")");
        $('#view2').css('background-image',"url("+imgView2+")");
        $('#view3').css('background-image',"url("+imgView3+")");
        $("input[name='imgs[0]']").val(imgView1);
        $("input[name='imgs[1]']").val(imgView2);
        $("input[name='imgs[2]']").val(imgView3);
        $('.close_btn').click(function () {
        $('div[class^=cover-wrap').fadeOut();
        })
        //document.addEventListener('touchmove', function (e) { e.preventDefault(); }, false);
        var clipArea = new bjj.PhotoClip("#clipArea1", {
            size: [428, 321],// 截取框的宽和高组成的数组。默认值为[260,260]
            outputSize: [428, 321], // 输出图像的宽和高组成的数组。默认值为[0,0]，表示输出图像原始大小
            //outputType: "jpg", // 指定输出图片的类型，可选 "jpg" 和 "png" 两种种类型，默认为 "jpg"
            file: "#file1", // 上传图片的<input type="file">控件的选择器或者DOM对象
            view: "#view1", // 显示截取后图像的容器的选择器或者DOM对象
            ok: "#clipBtn1", // 确认截图按钮的选择器或者DOM对象
            loadStart: function() {
                // 开始加载的回调函数。this指向 fileReader 对象，并将正在加载的 file 对象作为参数传入
                $('.cover-wrap1').fadeIn();
            },
            loadComplete: function() {
                 // 加载完成的回调函数。this指向图片对象，并将图片地址作为参数传入
            },
            //loadError: function(event) {}, // 加载失败的回调函数。this指向 fileReader 对象，并将错误事件的 event 对象作为参数传入
            clipFinish: function(dataURL) {
                 // 裁剪完成的回调函数。this指向图片对象，会将裁剪出的图像数据DataURL作为参数传入
                $('.cover-wrap1').fadeOut();
                $('#view1').css('background-size','100% 100%');
                // console.log(dataURL);
                img_ajax(dataURL,1);
                // console.log(dataURL);
            }
        });
        //上传封面
        //document.addEventListener('touchmove', function (e) { e.preventDefault(); }, false);
        var clipArea = new bjj.PhotoClip("#clipArea2", {
            size: [428, 321],// 截取框的宽和高组成的数组。默认值为[260,260]
            outputSize: [428, 321], // 输出图像的宽和高组成的数组。默认值为[0,0]，表示输出图像原始大小
            //outputType: "jpg", // 指定输出图片的类型，可选 "jpg" 和 "png" 两种种类型，默认为 "jpg"
            file: "#file2", // 上传图片的<input type="file">控件的选择器或者DOM对象
            view: "#view2", // 显示截取后图像的容器的选择器或者DOM对象
            ok: "#clipBtn2", // 确认截图按钮的选择器或者DOM对象
            loadStart: function() {
                // 开始加载的回调函数。this指向 fileReader 对象，并将正在加载的 file 对象作为参数传入
                $('.cover-wrap2').fadeIn();
            },
            loadComplete: function() {
                 // 加载完成的回调函数。this指向图片对象，并将图片地址作为参数传入
            },
            //loadError: function(event) {}, // 加载失败的回调函数。this指向 fileReader 对象，并将错误事件的 event 对象作为参数传入
            clipFinish: function(dataURL) {
                 // 裁剪完成的回调函数。this指向图片对象，会将裁剪出的图像数据DataURL作为参数传入
                $('.cover-wrap2').fadeOut();
                $('#view2').css('background-size','100% 100%');
                // console.log(dataURL);
                img_ajax(dataURL,2);
                // console.log(dataURL);
            }
        });
        // clipArea.destroy();
        // //上传封面
        //document.addEventListener('touchmove', function (e) { e.preventDefault(); }, false);
        var clipArea = new bjj.PhotoClip("#clipArea3", {
            size: [428, 321],// 截取框的宽和高组成的数组。默认值为[260,260]
            outputSize: [428, 321], // 输出图像的宽和高组成的数组。默认值为[0,0]，表示输出图像原始大小
            //outputType: "jpg", // 指定输出图片的类型，可选 "jpg" 和 "png" 两种种类型，默认为 "jpg"
            file: "#file3", // 上传图片的<input type="file">控件的选择器或者DOM对象
            view: "#view3", // 显示截取后图像的容器的选择器或者DOM对象
            ok: "#clipBtn3", // 确认截图按钮的选择器或者DOM对象
            loadStart: function() {
                // 开始加载的回调函数。this指向 fileReader 对象，并将正在加载的 file 对象作为参数传入
                $('.cover-wrap3').fadeIn();
            },
            loadComplete: function() {
                 // 加载完成的回调函数。this指向图片对象，并将图片地址作为参数传入
            },
            //loadError: function(event) {}, // 加载失败的回调函数。this指向 fileReader 对象，并将错误事件的 event 对象作为参数传入
            clipFinish: function(dataURL) {
                 // 裁剪完成的回调函数。this指向图片对象，会将裁剪出的图像数据DataURL作为参数传入
                $('.cover-wrap3').fadeOut();
                $('#view3').css('background-size','100% 100%');
                // console.log(dataURL);
                
                img_ajax(dataURL,3);
                // console.log(dataURL);
            }
        });
           function img_ajax(dataURL,num) {
            $.ajax({
                cache: true,
                type: "POST",
                url:"/Business/Goods/add_imgs",
                data:{
                       'data':dataURL
                    },
                dataType: 'json',
                async: false,
                error: function(data) {
                    swal('网络错误，请重试！', "", "error");
                    return false;
                },
                success: function(data) { 
                    if (data.error == 0) {
                        if (num==1) {
                            $("input[name='imgs[0]']").val(data.file_path);
                        }else if (num==2) {
                            $("input[name='imgs[1]']").val(data.file_path);
                        }else if (num==3) {
                            $("input[name='imgs[2]']").val(data.file_path);
                        }
                    }else{
                        swal(data.msg, "", "error");
                        return false;
                    }
                }
            });
        }
    //  $("#add-img").on('change', function () {
    //     if($('.showimg .imgBox').length>=3){
    //         alert('您只能上传三张图片');
    //         return false;
    //     }
    //     var _this = this;
    //     var formData = new FormData();
    //     formData.append('file',_this.files[0]);
    //     var srcs;
    //     if (!$(_this).val()) {
    //         return false;
    //     }
    //     $.ajax({
    //         cache: true,
    //         type: "POST",
    //         url:"/Business/Goods/add_imgs",
    //         data:formData,
    //         dataType: 'json',
    //         async: false,
    //         processData: false,
    //         contentType: false,
    //         error: function(data) {
    //             swal('网络错误，请重试！', "", "error");
    //             return false;
    //         },
    //         success: function(data) { 
    //             if (data.error == 0) {
    //                 srcs = data.file_path;
    //                 $(_this).val('');
    //             }else{
    //                 swal(data.msg, "", "error");
    //                 return false;
    //             }
    //         }
    //     });
        
    //     var addImg='<div class="imgBox" > <div class="file-edit"><i class="fa fa-trash del-i"></i></div><img class="addback-img" src='+srcs+'  style="cursor:pointer;" > <input type="hidden" value="'+srcs+'" name="imgs[]"  ></div>';
    //      $('.showimg').append(addImg);
    //      if(!$('.showimg .imgBox>img').hasClass('defult-color')){
    //         $('.showimg .imgBox>img:first').addClass('defult-color');
    //         $('.showimg .imgBox>input:first').attr('name','imgs[default]');
    //      }
         
    // });
    //  $('.showimg').delegate("img","click",function(){
    //     $('.showimg .imgBox>img').removeClass('defult-color');
    //     $('.showimg .imgBox>input').attr('name','imgs[]');
    //     $(this).addClass('defult-color');
    //     $(this).parent().children('input').attr('name','imgs[default]');

    //  });

    //  $('.showimg').delegate(".del-i","click",function(){ 
    //     $(this).parent().parent().remove();   
    //     if($(this).parent().parent().children('img').hasClass("defult-color")){
    //         $('.showimg .imgBox>img:first').addClass('defult-color');
    //         $('.showimg .imgBox>input:first').attr('name','imgs[default]');
    //     }
    // });

     

        $('#signupForm_submit').click(function(){
            $.ajax({
                cache: true,
                type: "POST",
                url:"/Business/Goods/edit",
                data:$('#signupForm').serialize(),// 你的formid
                dataType: 'json',
                async: false,
                error: function(data) {
                    swal('网络错误，请重试！', "", "error");
                    return false;
                },
                success: function(data) {      
                    if (data.error == 0) {
                        swal({
                            title: "保存商品成功！",
                            text: "",
                            type: "success",
                            showCancelButton: true,
                            confirmButtonColor: "#DD6B55",
                            confirmButtonText: "继续编辑商品",
                            cancelButtonText: "返回商品列表",
                            closeOnConfirm: false,
                            closeOnCancel: false
                        },
                        function(isConfirm) {
                            if (isConfirm) {
                                window.location.reload();
                            }else{
                                window.location.href="/Business/Goods/lists";
                            }
                        })
                    }else{
                        swal(data.msg, "", "error");
                        return false;
                    }
                }
            });
        });
    
    </script>
</body>

