<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>

<style>
    .content-list{
        display: inline-block;
    }
    .cont-list-s{
        font-weight: 700;
    }
    .extend-i-img{
        margin:0 30px 0 0;
        height: 150px;
        width: 150px;
        display: inline-block;
    }
    .float-e-margins-extend-extend{
        height: 234px;
    }
    .ibox-content-r{
        height: 191px;
        padding-top: 73px;
    }
    .containt-pad{
        padding: 0 10px;
    }
</style>

<body class="gray-bg">
<div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-sm-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>商品推广</h5>
                        <span class="label label-primary pull-right label-primary-cust">
                            <a href="javascript:history.back(-1);" class="fa-lg-cust-a" title="返回上一页">
                                <i class="fa fa-arrow-left fa-lg-cust" aria-hidden="true"></i>
                            </a>
                        </span>
                    </div>
                    <div class="ibox-content">
                        <div class="alert alert-warning alert-dismissable">
                            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                            <span class="alert-link">说明：</span>本页面提供了两种对商品进行推广的功能，您可以复制二维码或者推广链接粘贴到 QQ、微信、朋友圈、微博等地方进行宣传推广。
                        </div>
                        <div class="alert alert-success" style="margin-bottom:0px;">
                            <span class="alert-link">商品名称：</span><span style="margin-right:30px;"><?php echo $_GET['goods_name']; ?></span>
                            <span class="alert-link">商品类型：</span><span style="margin-right:30px;"><?php echo $_GET['goods_type_name']; ?></span>
                            <span class="alert-link">兑换价格（共享币）：</span><span style="margin-right:30px;"><?php echo $_GET['piao']; ?></span>
                            <span class="alert-link">库存：</span><span style="margin-right:30px;"><?php echo $_GET['nums']; ?></span>
                            <span class="alert-link">返利百分比：</span><span style="margin-right:30px;"><?php echo $_GET['rebate']*100; ?>%</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
         <div class="row">
            <div class="col-sm-6">
                <div class="ibox float-e-margins float-e-margins-extend">
                    <div class="ibox-title">
                        <h5>推广二维码：</small></h5>
                    </div>
                    <div class="ibox-content">
                        <img id="qrcode" src="" class="extend-i-img"/>
                        <span style="position: relative;"><i class="fa fa-info-circle"></i> 右击二维码，选择保存或另存为，即可宣传。</span>
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="ibox float-e-margins float-e-margins-extend">
                    <div class="ibox-title">
                        <h5>推广链接：</h5>
                    </div>
                    <div class="ibox-content ibox-content-r">
                        <div class="input-group ">
                            <input type="text" class="form-control" id="ext-input" value="" readonly="true"> 
                            <span class="input-group-btn"> 
                                <button type="button" class="btn btn-primary extend-copy" onClick="javascript:copyTest();">复制链接</button> 
                            </span>
                        </div>
                        <br>
                        <div>
                            <i class="fa fa-info-circle"></i>
                            <span>点击 “复制链接” 按钮，即可复制。</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>

<script language="javascript">
    //赋值链接
    var domain = document.domain;
    $("#ext-input").val('http://' + domain + '/exchange?<?php echo $_GET['get_name']?$_GET['get_name']:"g"; ?>=<?php echo $_GET['goods_id']; ?><?php echo $_GET['get_name']?"&b=".$_SESSION["business"]['business_id']:""; ?>');
    //赋值二维码
    $('#qrcode').attr('src',"http://api.qrserver.com/v1/create-qr-code/?data=http://" + domain + "/exchange?<?php echo $_GET['get_name']?$_GET['get_name']:"g"; ?>=<?php echo $_GET['goods_id']; ?><?php echo $_GET['get_name']?"%26b=".$_SESSION["business"]['business_id']:""; ?>&size=150x150");
    //点击复制
    function copyTest(){
        $("#ext-input").select();
        document.execCommand("copy");
        swal("复制成功",'快去粘贴到需要的地方进行推广吧','success');
    }
</script>