<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<body>
<div class="doc-home-page">
    <!-- 内网进入本站显示bar -->
    <?php if(isset($_SESSION['SITE_URL'])): ?>
    <div class="doc-top clearfix">
        <div class="doc-top-t top-bar-l active">
            <a href="">问诊</a>
        </div>
        <div class="doc-top-t top-bar-r">
            <a href="<?php echo $_SESSION['SITE_URL'] ? $_SESSION['SITE_URL'].'?site_type=hospital&logedMemberToken='.$_SESSION['logedMemberToken'] : 'javascript:alert(\'参数错误\');'; ?>">看片</a>
        </div>
    </div>
    <?php endif; ?>
    <!-- Swiper -->
    <div class="doc-top-banner">
        <div class="swiper-container">
            <a href="http://www.zzlhi.com" class="doc-topbanner-return">
                <i class="fa fa-chevron-circle-left"></i>
            </a>
            <div class="swiper-wrapper">
                <div class="swiper-slide">
                    <a href="">
                        <img src="/Public/Hospital/index/images/slide_1.png" alt="">
                    </a>
                </div>
                <div class="swiper-slide">
                    <a href="">
                        <img src="/Public/Hospital/index/images/slide_2.png" alt="">
                    </a>
                </div>
                <!-- <div class="swiper-slide">
                    <a href="">
                        <img src="/Public/Hospital/index/images/14.jpg" alt="">
                    </a>
                </div>
                <div class="swiper-slide">
                    <a href="">
                        <img src="/Public/Hospital/index/images/15.jpg" alt="">
                    </a>
                </div> -->
            </div>
            <!-- 轮播图下方点点 -->
            <div class="swiper-pagination"></div>

        </div>
    </div>
    <div class="margin-box">
    </div>
    <div class="doc-register">
        <div class="cle-fl">
            <img src="/Public/Hospital/index/images/circle1.png" alt="">
            <span>挂号</span>
        </div>
    </div>
    <div class="regis-list">
        <div class="regis-list-le">
            <a href="/Hospital/Doctor/lists">
                <img src="/Public/Hospital/index/images/2.png" alt="">
                <p class="re-fir">全部科室</p>
                <!--<p class="re-sec">阐述病症 </p>-->
                <!--<p class="re-thi">1分钟快速挂号</p>-->
            </a>
        </div>
        <div class="regis-list-ri">
            <ul>
                <li class="regis-list-li">
                    <a href="/Hospital/Doctor/lists?department=2">
                        <img src="/Public/Hospital/index/images/pifu.png" alt="">
                        <p>皮肤科</p>
                    </a>
                </li>
                <li class="regis-list-li">
                    <a href="/Hospital/Doctor/lists?department=3">
                        <img src="/Public/Hospital/index/images/erbihou.png" alt="">
                        <p>耳鼻喉科</p>
                    </a>
                </li>
                <li class="regis-list-li">
                    <a href="/Hospital/Doctor/lists?department=1">
                        <img src="/Public/Hospital/index/images/gu.png" alt="">
                        <p>骨科</p>
                    </a>
                </li>
                <li class="regis-list-li">
                    <a href="/Hospital/Doctor/lists?department=4">
                        <img src="/Public/Hospital/index/images/zhongyi.png" alt="">
                        <p>中医科</p>
                    </a>
                </li>
                <li class="regis-list-li">
                    <a href="/Hospital/Doctor/lists?department=5">
                        <img src="/Public/Hospital/index/images/kouqiang.png" alt="">
                        <p>口腔科</p>
                    </a>
                </li>
                <li class="regis-list-li">
                    <a href="/Hospital/Doctor/lists?department=6">
                        <img src="/Public/Hospital/index/images/meirong.png" alt="">
                        <p>美容整形</p>
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="margin-box-m"></div>
    <div class="doctor-list-top">热门医生</div>
    <!-- 医生列表滑动 -->
    <div class="doc-cen-banner">
        <div class="swiper-container">
            <div class="swiper-wrapper">
                <?php foreach ($hot_doctors as $key => $value): ?>
                <div class="swiper-slide">
                    <a href="/Hospital/Doctor/detail?doctor_id=<?php echo $value['doctor_id'] ?>">
                        <img src="<?php echo $value['head_img'] ?>" alt="">
                        <p class="doc-list-fir"><?php echo $value['doctor_name'] ?></p>
                        <p class="doc-list-sec"><?php echo $value['department_name'] ?></p>
                        <p class="doc-list-thi">人气:
                            <span class="doc-li-this"><?php echo $value['count_zan'] ?></span>
                        </p>
                    </a>
                </div>
                <?php endforeach ?>
               
            </div>
        </div>
    </div>
    <div class="margin-box">
    </div>
    <!-- 询问区域 -->
    <div class="ask_container">
        <div class='interrogation'>
            <div class="interrogation-title ">
                <div class="interrogation-left ">
                    <img src="/Public/Hospital/index/images/icon/circle2.png">
                    <span>问诊</span>
                </div>
            </div>
            <?php foreach ($advices as $key => $value): ?>
            <div class="interrogation-centent">
                <div class="interrogation-container">
                    <div class="centent-top">
                        <div class="keshi f_l">
                            <?php echo $value['department_name'] ?>
                        </div>
                        <div class="time f_r">
                            <?php echo $value['advice_time'] ?>
                        </div>
                    </div>
                    <div class="centent-description">
                        <p class="" onclick="javascript:window.location.href='/Hospital/Advice/advice_info?advice_id=<?php echo $value['advice_id'];?>';"><?php echo mb_strlen($value['advice_comment'])<65?$value['advice_comment']:mb_substr($value['advice_comment'],0,65,'utf-8').'...'; ?></p>
                        <span class="fa fa-angle-right"></span>
                    </div>
                    <?php if ($value['doctor_name']=='等待医生回复'){ ?>
                    <div class="centent-status">
                        等待医生回复
                    </div>
                    <?php }else{ ?>
                    <div class="centent-status offer">
                        <img src="<?php echo $value['head_img'] ?>" class="head-img">
                        <span><?php echo $value['doctor_name'] ?></span>医生已回复
                    </div>    
                    <?php } ?>
                    
                </div>
            </div>
            <?php endforeach ?>
            <!-- <div class="interrogation-centent">
                <div class="interrogation-container">
                    <div class="centent-top">
                        <div class="keshi f_l">
                            耳鼻喉头颈科
                        </div>
                        <div class="time f_r">
                            2017-05-02
                        </div>
                    </div>
                    <div class="centent-description clearfix hasimg">
                        <img src="/Public/Hospital/index/images/hasi.png" class="hasimg-icon">
                        <p id="cen-des-pb">我额诶非法核算的花果山伺服机所的花果山伺服机所所所搜所所搜多女多女搜集偶剧哦VC美女覅你回复才能</p>
                        <span class="fa fa-angle-right"></span>
                    </div>
                    <div class="centent-status offer">
                        <img src="/Public/Hospital/index/images/person.png" class="head-img">
                        <span>陈潜</span>医生已回复
                    </div>
                </div>
            </div> -->
        </div>
    </div>
</div>
<!--定位浮标-->
<div class="introduce-footer clearfix">
    <div class="footer-top">
        <a href="/Hospital/Advice/add_advice" class="footer-left f_l ask indexask"> <img src="/Public/Hospital/index/images/icon/ask%20button.png" alt=""><span>免费问诊</span></a>
        <a href="/Hospital/Doctor/lists" class="footer-righter f_r order"><img src="/Public/Hospital/index/images/icon/book%20button.png"alt=""><span>预约挂号</span></a>
    </div>
    <div class="tab-bar">
        <ul class="clearfix">
            <li class="tab-group  f_l  ">
                <a href="/Hospital/Advice/lists">
                    <span>会诊室</span>
                </a>
            </li>
            <li class="tab-home f_l home-currunt">
                <a href="#">
                    <span>首页</span>
                </a>
            </li>
            <li class="tab-personal f_l">
                <a href="/Hospital/My/index">
                    <span>我</span>
                </a>
            </li>
        </ul>
    </div>
</div>
<script>

//    <!-- Swiper JS -->
    var swiper_top = new Swiper('.doc-top-banner .swiper-container', {
        pagination: '.doc-top-banner .swiper-pagination',
        slidesPerView: 1,
        paginationClickable: true,
        loop: true,
        autoplay: 1500,
        autoplayDisableOnInteraction: false
    });
    var swiper_doc = new Swiper('.doc-cen-banner .swiper-container', {
        slidesPerView: 3.5,
        paginationClickable: true,
        spaceBetween: 0,
        freeMode: true
    });
</script>
</body>
<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
