<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<?php require_once MODULE_PATH.'/View/Common/menu.phtml'; ?>
<section class="Hui-article-box">
<nav class="breadcrumb"><i class="Hui-iconfont">&#xe67f;</i> 首页
    <span class="c-gray en">&gt;</span>
    系统管理
    <span class="c-gray en">&gt;</span>
    修改密码 <span class="c-gray en">&gt;</span>
    <?php echo $res['nick_name']; ?> <a class="btn btn-success radius r" style="line-height:1.6em;margin-top:3px" href="javascript:location.replace(location.href);" title="刷新" ><i class="Hui-iconfont">&#xe68f;</i></a>
</nav>
<form action="/Hospitaladmin/admin/repassword" method="post" enctype="multipart/form-data" style="margin-right: 60px;left: -80px;position: relative;" class="form form-horizontal">
    <div class="row cl">
        <label class="form-label col-xs-4 col-sm-3">医院名称：</label>
        <div class="formControls col-xs-8 col-sm-9">
            <input type="text" class="input-text" autocomplete="off" disabled="true" name="hospital_name" value="<?php echo $_SESSION['hospital_admin']['hospital_name']; ?>">
        </div>
    </div>
    <div class="row cl">
        <label class="form-label col-xs-4 col-sm-3">后台账号：</label>
        <div class="formControls col-xs-8 col-sm-9">
            <input type="text" class="input-text" autocomplete="off" disabled="true" name="admin" value="<?php echo $_SESSION['hospital_admin']['admin']; ?>">
        </div>
    </div>
    <div class="row cl">
        <label class="form-label col-xs-4 col-sm-3">新密码：</label>
        <div class="formControls col-xs-8 col-sm-9">
            <input type="password" class="input-text" autocomplete="off" name="password" placeholder="输入新密码">
        </div>
    </div>
    <div class="row cl">
        <label class="form-label col-xs-4 col-sm-3">重复密码：</label>
        <div class="formControls col-xs-8 col-sm-9">
            <input type="password" class="input-text" autocomplete="off" name="repassword" placeholder="重复输入新密码">
        </div>
    </div>
    <div class="row cl">
        <div class="col-xs-8 col-sm-9 col-xs-offset-4 col-sm-offset-3">
            <input class="btn btn-primary radius" type="submit" value="提交">
            <input class="btn btn-primary radius" type="reset" value="重置">
        </div>
    </div>
</form>
</section>
<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>