<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>

<body style='background-color: #EBEBEB;'>
<div class="container">
    <div class="chatheader clearfix">
        <a href="#" class="fa fa-angle-left"></a><span><?php echo $other_info['nick_name']; ?></span> <a href="#" class="server "><img
            src="/Public/Chat/index/images/server.png" alt=""></a>
    </div>
    <div class="chat-content">
        <div class="chatbigbox">
        <?php foreach ($contents as $key => $value): ?>
            <?php $value['send_member_id']==$member_id?$role = 'self':$role = 'other';$info = $role.'_info'; ?>
        
            <div class="<?php echo $role ?>box clearfix">
                <div class="<?php echo $role ?> ">
                    <a href="/index.php/index/index/memberInfo?member_id=<?php echo $$info['member_id']; ?>"><img src="<?php echo $$info['member_head']; ?>" alt=""></a>
                    <div class="<?php echo $role ?>chatbox">
                        <p class='chatname'><?php echo $$info['nick_name']; ?></p>
                        <div class="chat-details">
                            <p class="member_content"><?php echo $value['content']; ?></p>

                            <div class="bugle"></div>
                        </div>
                        <div class="chattime">
                            <span member-id="<?php echo $$info['member_id']; ?>"><?php echo $value['send_time']; ?></span>
                        </div>
                    </div>
                    
                </div>
            </div>
        <?php endforeach ?>
            
        </div>
    </div>
</div>
<div class="chat-container-bot">
    <div class="chat-conbot-input">
        <div class="chat-cbin-l">
            <img src="/Public/Chat/index/images/list.png" alt="" class="cbin-list">
        </div>
        <form action="" id="chat_content" class="chat-cbin-form" method="post">
            <div class="chat-cbin-in">
                <textarea name="content" id="emojiInput" onkeyup="myFunction()" class="emojiInput" rows="1"
                          cols="18"></textarea>
            </div>
            <div class="chat-cbin-r">
                <img src="/Public/Chat/index/images/smile.png" alt="" class="cbin-smile">
            </div>
            <a style="line-height: 0.9rem;text-align: center;" class="chat-cbin-but ds" <?php echo empty($member_id)?'disabled="disabled"':'' ?> >发送</a>
            <input type="hidden" name="member_id" value="<?php echo $other_info['member_id'] ?>">
        </form>
    </div>
    <div class="chat-conbot-item">
        <ul>
            <a href="" class="conbot-item-a">
                <li class="chat-task">
                    <img src="/Public/Chat/index/images/task.png" alt="" class="cbit-task">
                    <span>任务区</span>
                </li>
            </a>
            <a href="" class="conbot-item-a">
                <li class="chat-publick">
                    <img src="/Public/Chat/index/images/publicchat.png" alt="" class="cbit-pub">
                    <span>公共聊天</span>
                </li>
            </a>
            <a href="" class="conbot-item-a">
                <li class="chat-region">
                    <img src="/Public/Chat/index/images/areachat.png" alt="" class="cbit-reg">
                    <span>区域聊天</span>
                </li>
            </a>
            <a href="/Chat/Alone/index" class="conbot-item-a">
                <li class="chat-contact">
                    <img src="/Public/Chat/index/images/contacts.png" alt="" class="cbit-cont">
                    <span>最近联系人</span>
                </li>
            </a>
        </ul>
    </div>
    <div class="emoji-mod" data-textmod="emoji" id="emojiContainer"></div>
</div>
</body>
<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>
<script>
    // var str = 你接收的输入框的值;
//    for (var i = 0; i < acc.length; i++) {
//        str=str.replace(new RegExp(acc[i].name,'gm'),acc[i].img);
//    };
    // 这个str就是带图片的值了
    $('.chat-cbin-but').on('click', function() {
        $("#emojiInput").val("");
        var screenW =$(window).width();
        var multiple = screenW/320;
        var textHv = 20.5*multiple+'px';
        $("#emojiInput").height(textHv);
    });


    autosize($('#emojiInput'));
    var cbb = $(".chat-cbin-but");
    var myflag = true;
    var emo_val = $('#emojiInput').val().replace(/(^\s*)|(\s*$)/g, "");
    function myFunction(){
        if (myflag&&emo_val.length>0) {
        console.log('1'+emo_val+'1')

            cbb.css({
                backgroundColor: '#ff9500',
                color: '#fff'
            })
        }
    };
    var cbl = $(".cbin-list");
    var cit = $('.chat-conbot-item');
    var cbs = $(".cbin-smile");
    var emo = $(".emoji-mod");
    var cbt = $("#emojiInput");
    var text_info =cbt.val();
    var cbt = $("#emojiInput");
    var screenW =$(window).width();
    var multiple = screenW/320;
    var h = document.getElementsByClassName('chatbigbox')[0].clientHeight-$('.chat-content')[0].clientHeight+multiple*21*6;
    var cbmb = $('.chat-cbin-form')[0].scrollHeight+28*(multiple+2);
    var bable = 28*multiple;
    var bables = 28*multiple*1.6;
    var csbs = $('.chat-cbin-form')[0].scrollHeight+28*(multiple+4);
    $('.chat-content').animate({'scrollTop':h},250)
    $('.chatbigbox').animate({'marginBottom':bables*2.2},250) 
    $(function(){
        
        setInterval(function(){
            var text_info =cbt.val();
            var dee =  Math.ceil(text_info.length/15);
            if (text_info.length>0&&text_info.lastIndexOf(']') > 0 ) {
                cbt.css({height:dee*multiple*21+'px'});
                if (text_info.length>0&&text_info.indexOf(']') < text_info.length-1&&text_info.lastIndexOf(']') > 0 ) {
                    autosize($('#emojiInput'));
                }
            }
            if (text_info!==undefined&&text_info!=="") {
                if (myflag) {
                    cbb.css({
                        backgroundColor: '#ff9500',
                        color: '#fff'
                    })
                }
            }else{
                    cbb.css({
                        backgroundColor: '#bbb',
                        color: '#ddd'
                    })
            }
        }, 500);
        // var h = document.getElementsByClassName('chatbigbox')[0].clientHeight-$('.chat-content')[0].clientHeight+multiple*21*6;
        // var cbmb = $('.chat-cbin-form')[0].scrollHeight+28*(multiple+2);
        // var bable = 28*multiple;
        // var bables = 28*multiple*1.6;
        // var csbs = $('.chat-cbin-form')[0].scrollHeight+28*(multiple+4);
        cbl.on('tap', function() {
            emo.css('display',"none");
            cbt.blur();
            if (cit.css('display')=="block") {
                $('.chat-content').animate({'scrollTop': h},250);
                $('.chatbigbox').animate({'marginBottom':bables},250)
                setTimeout(function(){
                    cit.css('display',"none");
                    
                },100)

            }else{
                $('.chatbigbox').css('marginBottom', cbmb);
                $('.chat-content').animate({'scrollTop':h},250);
                setTimeout(function(){
                    cit.css('display',"block");
                },100)
            };
        });
        cbs.on('tap', function() {
            cit.css('display',"none");
            cbt.blur();
            if (emo.css('display')=="block") {
                emo.css('display',"none");
                $('.chat-content').animate({'scrollTop':h*1.5},250)
                $('.chatbigbox').animate({'marginBottom':bables},250)
            }else{
                emo.css('display',"block");
                $('.chatbigbox').css('marginBottom',csbs );
                $('.chat-content').animate({'scrollTop':h*1.5},250)
            }
        });

        cbt.on('focus',function() {
            emo.css('display',"none");
            cit.css('display',"none");
            $('.chat-content').animate({'scrollTop':h},250);
            $('.chatbigbox').animate({'marginBottom':bables},250)
        });
        cbb.on('tap',function() {
            if ($('#emojiInput').val().replace(/(^\s*)|(\s*$)/g, "")==""|| !myflag) {
                return false;
            };

            var timer =6;
            Countdown();
            function Countdown() {
               if (timer >= 2) {
                   timer -= 1;
                   $('.chat-cbin-but').html(timer) ;
                       setTimeout(function() {
                           Countdown();
                        }, 1000);
                }else{
                    $('.chat-cbin-but').html('发送') 
                }
            }
            cbb.css({
                backgroundColor: '#bbb',
                color: '#ddd'
            });
            $('.chat-cbin-but').prop("disabled",true);
            myflag = false;
            submit_content();
            setTimeout(function(){
                $('.chat-cbin-but').prop("disabled",false);
                myflag = true;
            }, 5000)
        })
       
        $('.chatbigbox').on('tap', function() {
            emo.css('display',"none");
            cbt.blur();
            cit.css('display',"none");
            $('.chat-content').animate({'scrollTop':h},250)
            $('.chatbigbox').animate({'marginBottom':bables},250)  
            });

    })
    
   
    for (var e = 0; e < $('.chatbigbox').children().length; e++) {
        
        var str = $('.chatbigbox').children('div:nth-child('+(e+1)+')').children('div').children('div').children('div').children('p').text();
        for (var i = 0; i < acc.length; i++) {
            str=str.replace(new RegExp(acc[i].name,'gm'),acc[i].img);
        };
        $('.chatbigbox').children('div:nth-child('+(e+1)+')').children('div').children('div').children('div').children('p').html(str);
    };
                    
    var div_length = $('.chatbigbox').children('div').length;
    function submit_content(){
        $.ajax({
            cache: true,
            type: "POST",
            url:"/Chat/Alone/add_content",
            data:$('#chat_content').serialize(),// 你的formid
            async: false,
            error: function(data) {
              alert('网络错误,发送失败');
            },
            success: function(data) {
                // data = JSON.parse(data);   
                // console.log(data);
                if (data.err_code == 0) {
                    console.log(data.data);
                    var member = data.data;
                    var str = member.content;
                    for (var i = 0; i < acc.length; i++) {
                        str=str.replace(new RegExp(acc[i].name,'gm'),acc[i].img);
                    };
                    
                    var string = '<div class="selfbox clearfix"> <div class="self "> <a href="#"><img src="'+member.member_head+'" alt=""></a> <div class="selfchatbox"> <p class="chatname">'+member.nick_name+'</p> <div class="chat-details"> <p> '+str+' </p> <div class="bugle"></div> </div> <div class="chattime"> <span>'+member.send_time+'</span> </div> </div> </div> </div>';
                    $('textarea[name=content]').val('');
                    $('.chatbigbox').append(string);
                    div_length++;
                    // var h = document.getElementsByClassName('chatbigbox')[0].clientHeight-$('.chat-content')[0].clientHeight+multiple*21*6;
                    // var cbmb = $('.chat-cbin-form')[0].scrollHeight+28*(multiple+2);
                    // var bable = 28*multiple;
                    // var bables = 28*multiple*1.6;
                    // var csbs = $('.chat-cbin-form')[0].scrollHeight+28*(multiple+4);
                    $('.chat-content').animate({'scrollTop': h+bables*2.5},250);
                    $('.chatbigbox').animate({'marginBottom':bables*5},250)
                    if (div_length >= 15) {
                        $('.chatbigbox').children('div:first-child').remove();
                    };
                    // $('.chat-cbin-but').prop("disabled",true);
                    // setInterval(function(){
                    // $('.chat-cbin-but').prop("disabled",false);
                    // }, 5000)
                }else{
                    alert(data.msg);
                };
            }
        });
    }

    
   
    var get_c = setInterval("get_coment()",5000);
    var  time = $($('.otherbox')[$('.otherbox').length-1]).children('div').children('div').children('div:last-child').children('span').text();
    var other_id = $($('.otherbox')[$('.otherbox').length-1]).children('div').children('div').children('div:last-child').children('span').attr('member-id');
    if (time=="") {
        time = "<?php echo date('Y-m-d H:i:s');?>";
    };
    if (other_id=="") {
        other_id = 0;
    };
    function get_coment(){
        if ($('.otherbox').length > 0) {
            
        };
        
        $.ajax({
            cache: true,
            type: "POST",
            url:"/Chat/Alone/get_content",
            data:{'time':time,'other_id':other_id},// 你的formid
            async: false,
            error: function(data) {
              //alert('网络错误,发送失败');
            },
            success: function(data) {
                // console.log(data);
                // return false;
                // data = JSON.parse(data);   
                //console.log(data);
                if (data.err_code == 0) {
                    for (var i = 0; i <= data.data.length - 1; i++) {
                        //console.log(i);return false;
                        var member = data.data[i];
                        var str = member.content;
                        for (var i = 0; i < acc.length; i++) {
                            str=str.replace(new RegExp(acc[i].name,'gm'),acc[i].img);
                        };
                        
                        var string = '<div class="otherbox clearfix"> <div class="other "> <a href="#"><img src="'+member.member_head+'" alt=""></a> <div class="otherchatbox"> <p class="chatname">'+member.nick_name+'</p> <div class="chat-details"> <p> '+str+' </p> <div class="bugle"></div> </div> <div class="chattime"> <span>'+member.send_time+'</span> </div> </div> </div> </div>';
                        time = member.send_time;
                        other_id = member.member_id;
                        $('.chatbigbox').append(string);
                        div_length++;

                    };
                };
            }
        });

    //clearInterval(get_c);
    }


</script>
