<!DOCTYPE html>
<html>


<!-- Mirrored from www.zi-han.net/theme/hplus/lockscreen.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 20 Jan 2016 14:19:52 GMT -->
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <title>在这里共享商企平台</title>

    <!--[if lt IE 9]>
    <meta http-equiv="refresh" content="0;ie.html" />
    <![endif]-->
    <link href="/Public/hplus/css/bootstrap.min14ed.css?v=3.3.6" rel="stylesheet">
    <link href="/Public/hplus/css/font-awesome.min93e3.css?v=4.4.0" rel="stylesheet">

    <link href="/Public/hplus/css/animate.min.css" rel="stylesheet">
    <link href="/Public/hplus/css/style.min862f.css?v=4.1.0" rel="stylesheet">
    <link href="/Public/hplus/css/plugins/sweetalert/sweetalert.css" rel="stylesheet">
    <script>if(window.top !== window.self){ window.top.location = window.location;}</script>
    <style>
.lockscreen.middle-box {
    width: 320px;
    padding-top: 110px;
}
.myhide{
     display: none;

   
}
.myshow{
   display: block;
    }
 </style>

</head>

<body class="gray-bg">

    <div class="lock-word animated fadeInDown">
    </div>
    <div class="middle-box text-center lockscreen animated fadeInDown">
        <div>
            <div class="m-b-md">
                <img alt="image" style="background-color: #1ab394;" class="img-circle circle-border" src="/Public/hplus/img/black_logo.png">
            </div>
            <h3>密码找回</h3>
            <div class=" old-form myshow">
                <form class="m-t  " name='getCode' >
                    <div class="form-group" style="position: relative;">
                        <input type="text" name="phone_num" class="form-control" maxlength="11" placeholder="企业注册法人手机号" >
                         <p id="send_code" class="btn btn-primary " maxlength="4" style='position: absolute; right: 0;top: 3px; padding: 3px;'>发送验证码</p>
                    </div>
                    <div class="form-group">
                        <input type="text" name="sms_code" class="form-control" placeholder="输入验证码" >
                    </div>
                    <p  class="btn btn-primary block full-width  find-btn">找回</p>
                </form>
            </div>
           <div class="new-form myhide">
            <form class="m-t  " name='resetPass' >
                <div class="form-group" style="position: relative;">
                    <input type="password" name="n_password" class="form-control" placeholder="输入新密码" >
                </div>
                <div class="form-group">
                    <input type="password" name="c_password" class="form-control" placeholder="确认新密码" >
                </div>
                <p id="reset_submit" class="btn btn-primary block full-width">重置</p>
            </form>

           </div>
          
        </div>
    </div>
    <script src="/Public/hplus/js/jquery.min.js?v=2.1.4"></script>
    <script src="/Public/hplus/js/bootstrap.min.js?v=3.3.6"></script>
    <script src="/Public/hplus/js/plugins/sweetalert/sweetalert.min.js"></script>
</body>



</html>
<script>
    var wait=60;
    function time(o) {
        if (wait == 0) {
            o.removeAttribute("disabled");   
            $(o).html("重新发送");
            o.style.backgroundColor='#1ab394';
            wait = 60;
        } else { 
            o.style.backgroundColor='#ccc';
            o.setAttribute("disabled", true);
            $(o).html(" " + wait + " s ");
            wait--;
            setTimeout(function() {
                time(o)
            },
            1000)
        }
    }

    $('#send_code').click(function(){
        var _this = this;
        $.ajax({
            cache: true,
            type: "POST",
            url:"/Business/Log/send_code",
            data:{phone_num:$('input[name=phone_num]').val(),find_pass:true},
            dataType: 'json',
            async: false,
            error: function(data) {
                swal('网络错误，请重试！', "", "warning");
            },
            success: function(data) {
                if (data.error == 0) {
                    time(_this);
                }else{
                     swal(data.msg, "", "warning")
                }
            }
        });
    });

    $('.find-btn').click(function () {
        $.ajax({
            cache: true,
            type: "POST",
            url:"/Business/Log/findpassword",
            data:{phone_num:$('input[name=phone_num]').val(),sms_code:$('input[name=sms_code]').val()},
            dataType: 'json',
            async: false,
            error: function(data) {
                 swal('网络错误，请重试！', "", "warning");
             
            },
            success: function(data) {
                if (data.error == 0) {
                    $('.old-form').removeClass('myshow').addClass('myhide');
                    $('.new-form').removeClass('myhide').addClass('myshow');
                }else{
                     swal(data.msg, "", "warning")
                   
                }
            }
        });
        
    })

    $('#reset_submit').click(function () {
        if (!$('input[name=n_password]').val()) {
            swal('新密码未填写！', "", "warning");
            return false;
        }
        
        if ($('input[name=n_password]').val().length < 6 || $('input[name=n_password]').val().length > 16) {
             swal('请输入6~16位密码', "", "warning");
            return false;
        }

        if ($('input[name=n_password]').val() != $('input[name=c_password]').val()) {
            swal('两次新密码不一致', "", "warning");
            return false;
        }
        $.ajax({
            cache: true,
            type: "POST",
            url:"/Business/Log/findpassword?phone_num="+$('input[name=phone_num]').val(),
            data:{phone_num:$('input[name=phone_num]').val(),password:$('input[name=c_password]').val()},
            dataType: 'json',
            async: false,
            error: function(data) {
               swal('网络错误，请重试！', "", "warning");
            },
            success: function(data) {
                if (data.error == 0) {
                    swal(data.msg,"","warning");
                    setTimeout("window.location.href='/Business/Log/in';",1000);
                }else{
                    swal(data.msg, "", "warning"); 
                }
            }
        });
        
    })
</script>
