<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<style>
    .i-check-right{
        margin-left: 40px;
    }
    .col-sm-s{
    	width: 40% !important;
    }
    .bank-card-p{
    	display: block;
    	margin-top: 12px;
    }
    .but-sure{
    	padding-left: 0;
    }
    .ibox-content{
        padding-left: 25%;
    }
</style>
<body class="gray-bg">
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-sm-12">
                <div class="ibox">
                    <div class="ibox-title">
                        <h5>增加一张卡</h5>
                        <span class="label label-primary pull-right label-primary-cust">
                            <a href="javascript:history.back(-1);" class="fa-lg-cust-a" title="返回上一页">
                                <i class="fa fa-arrow-left fa-lg-cust"  aria-hidden="true"></i>
                            </a>
                        </span>
                    </div>
                    <div class="ibox-content">
                        <div class="main-content">
	                        <form method="get" class="form-horizontal">
	                            <div class="bank-card form-group">
	                                <div class="bank-card-list">
	                                    <label class="label-style col-sm-2 control-label">选择银行卡类型：</label>
	                                    <select name="bank_id" id="bank_id" class="form-control m-b col-sm-s">
	                                        <?php foreach($banks as $v): ?>
                                            <option value="<?php echo $v['bank_id']; ?>"><?php echo $v['bank_name']; ?></option>
	                                        <?php endforeach; ?>
	                                    </select>
	                                </div>
	                                <div class="bank-card-list">
	                                    <p class="bank-card-p"><label class="label-style col-sm-2 control-label">开户名：</label>
                                            <input class="form-control col-sm-s" id="card_name" name="card_name" type="text">
                                        </p>
	                                    <p class="bank-card-p"><label class="label-style col-sm-2 control-label">卡号：</label>
                                            <input class="form-control col-sm-s" id="card_number" name="card_number" type="text">
                                        </p>
	                                </div>
    	                             <div class="col-sm-4 col-sm-offset-2 but-sure">
    									<p class="btn btn-primary" onclick="javascript:actionAdd();">确定添加</p>
    	                            </div>
	                            </div>
	                        </form>
                    	</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>
<script>
    //执行添加
    function actionAdd(){ 
         // chen
        if (!($('#bank_id').val()&&$.trim($('#card_name').val())&&$.trim($('#card_number').val()))){
            swal({
                title: "请完整填写所需内容",
                text: "",
                type: "warning",
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "确定",
                closeOnConfirm: false,
                closeOnCancel: true
            })
        }else{
        // chen
            swal({
                title: "添加前请确认您的输入无误",
                text: "",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "确定添加",
                cancelButtonText: "取消",
                closeOnConfirm: false,
                closeOnCancel: true
            },
            function(isConfirm) {
                if (isConfirm) {
                    $.ajax({
                        cache: true,
                        type: "POST",
                        url:"/Business/Finance/bank_card_action",
                        data:{method:'add',bank_id:$('#bank_id').val(),card_name:$('#card_name').val(),card_number:$('#card_number').val()},
                        dataType: 'json',
                        async: false,
                        error: function(data) {
                           swal('网络错误，请重试！', "", "warning");
                        },
                        success: function(data) {
                            if (data.error == 0) {
                                swal(data.msg, "", "success");
                                setTimeout("window.location.href = '/Business/Finance/bank_card';",1000);
                            }else{
                                swal(data.msg, "", "error");
                            }
                        }
                    });
                }
            })
        }
    }
</script>