<!-- 找回密码 -->
<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<style>
.wy-header {
    height: 44px;
    border-bottom: 0px;
    position: fixed;
    left: 0;
    top: 0;
    width: 100%;
    background: #e21323;
    z-index: 100;
}
.wy-header-title {
    margin: 0 50px;
    text-align: center;
    height: 44px;
    line-height: 44px;
    font-size: 16px;
    color: #fff;
    overflow: hidden;
}
.weui-label.wy-lab{
    width: 80px;
}
</style>
<body ontouchstart>
<!--主体-->
<header class="wy-header">
 <a href="javascript:;" title="返回上一页" style="width: 50px;position: absolute;left: 0;top: 0;z-index: 10; height: 45px;"><div class="wy-header-icon-back"></div></a>
  <div class="wy-header-title" style="color: #fff">设置支付密码</div>
</header>
<form id="find_pass" >
    <div class="weui-content" style="margin-top: 44px;">
        <div class="weui-cells weui-cells_form wy-address-edit">
            <div class="weui-cell">
                <div class="weui-cell__hd"><label class="weui-label wy-lab">支付密码</label></div>
                <div class="weui-cell__bd"><input class="weui-input" name="pay_pass" type="password" pattern="[0-9]*" placeholder="请输入6位支付密码" maxlength="6"></div>
            </div>
            <div class="weui-cell">
                <div class="weui-cell__hd"><label class="weui-label wy-lab">重复密码</label></div>
                <div class="weui-cell__bd"><input class="weui-input" name="repay_pass" type="password" pattern="[0-9]*" placeholder="重复新密码" maxlength="6"></div>
            </div>
        </div>
        <div id="submit_pass" class="weui-btn-area"><a href="javascript:;" class="weui-btn weui-btn_warn">设置密码</a></div>
    </div>
</form>

</body>
<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>

<script>
    $(function() {
        FastClick.attach(document.body);
    });

    var flag = false; //防止二次提交

    $('#submit_pass').click(function(){
        if(!$('input[name=pay_pass]').val() || $('input[name=pay_pass]').val().length != 6){
            $.toast('请填写6位支付密码', "cancel");return false;
        }

        if($('input[name=pay_pass]').val() != $('input[name=repay_pass]').val()){
            $.toast('两次密码不致', "cancel");return false;
        }

        $.ajax({
            cache: true,
            type: "POST",
            url:"/exchange/log/pay_pass",
            data:$('#find_pass').serialize(),// 你的formid
            dataType: 'json',
            async: false,
            error: function(data) {
                $.toast('网络错误', "cancel");
            },
            success: function(data) {      
                if (data.error == 0) {
                    window.location.href="/exchange";
                }else{
                    $.toast(data.msg, "cancel");
                }
            }
        });
    });
</script>