<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<style type="text/css">
    .load-more{
        width: 100%;
        height: 1rem;
        line-height: 1rem;
        background-color: #BFDFFF;
        color: #999;
        font-size: 0.4rem;
        text-align: center;
    }
</style>
<body>
<div class="details-coentainer">
    <div class="header">
        <a href="/Hospital/Doctor/lists" onclick="javascript:;" class="fa fa-angle-left f_l" aria-hidden="true"></a> <span> 医生详情 </span>

        <a href="#" class="collect f_r <?php echo $info['is_collect']==1?'select':'' ?>"
           aria-hidden="true" id="collect" onclick=collect("#collect","select")></a>
        &nbsp;&nbsp;
        <!-- <a href="#"
           class="share-alt f_r" id="share" aria-hidden="true"></a> -->
    </div>
    <div class="doctor clearfix">
        <div class="doc-left f_l">
            <img src="<?php echo $info['head_img'] ?>" alt="">
        </div>
        <div class="doc-moddle f_l">
            <p class="m-p"><span><?php echo $info['doctor_name'] ?></span><?php echo $info['ranks_name'] ?></p>
            <?php foreach ($toux as $key => $value){ ?>
                <p><?php echo $value ?></p>
            <?php } ?>
            <!-- <p>北京华医皮肤病医院院长</p>
            <p> 中国武警总医院原皮肤科主任</p> -->
        </div>
        <div class="doc-right f_r">
            <div class="doc-good">
                <span id="good" onclick=active("#good","good") <?php echo $info['is_zan']==1?'class="good"':'' ?> ></span>
                <p id="zan-count"><?php echo $info['count_zan'] ?></p>
            </div>

            <!-- <a href="#">医生说</a> -->
        </div>
    </div>
    <div class="doc-grade clearfix">
        <!-- <div class="grade blue f_l">治疗效果<span> 100 </span> 分</div> -->
        <a href="/Hospital/Doctor/chat?doctor_id=<?php echo $_GET['doctor_id'] ?>"> <div class="grade blue f_l">医生说 </div> </a>
        <div class="grade orange f_l">医生评价 <span> <?php echo ceil($info['level']/5*100) ?> </span> 分</div>
        <div class="grade green f_r">接诊次数 <span> <?php echo $info['count_see'] ?> </span> 次</div>
    </div>
    <div class="doc-introduce">
        <div class="introduce-title clearfix">
            <div class="introduce-left f_l">
                <span class="icon-introduce"></span>医生介绍
            </div>

        </div>
        <div class="introduce-profile"  stlye="height:3rem;overflow:auto;">
            <p id="doctor_jieshao">
                <?php echo $short; ?>
            </p>
            <span style="float:right;font-size:0.4125rem;color:#007aff;display:none" onclick="javascript:shouqi();" id="shouqi">收起▲</span>
            <span style="float:right;font-size:0.4125rem;color:#007aff" id="zhankai" onclick="javascript:zhankai();">展开▼</span>
        </div>
    </div>
    <div class="doc-introduce">
        <div class="introduce-title clearfix">
            <div class="introduce-left f_l">
                <span class=" icon-introduce disease"></span>擅长疾病
            </div>
        </div>
        <div class="introduce-profile">
            <p>
                <?php echo $info['adept'] ?>
            </p>
        </div>
    </div>
    <div class="doc-introduce">
        <div class="introduce-title clearfix">
            <div class="introduce-left f_l">
                <span class="icon-introduce cometime"></span>出诊时间
            </div>
        </div>
        <div class="cometime-table  clearfix">
            <div class="cometime-head">
                <div class="cometime-left  f_l"></div>
                <div class="cometime-right f_l">
                    <ul class="cometime-title">
                        <li>一</li>
                        <li>二</li>
                        <li>三</li>
                        <li>四</li>
                        <li>五</li>
                        <li>六</li>
                        <li class="last">日</li>
                    </ul>

                </div>
            </div>
            <div class="cometime-body clearfix">
                <div class="cometime-left  f_l">
                    上午
                </div>
                <div class="cometime-right f_l">
                    <ul>
                        <li <?php echo $visiting['1-1'] ?>></li>
                        <li <?php echo $visiting['2-1'] ?>></li>
                        <li <?php echo $visiting['3-1'] ?>></li>
                        <li <?php echo $visiting['4-1'] ?>></li>
                        <li <?php echo $visiting['5-1'] ?>></li>
                        <li <?php echo $visiting['6-1'] ?>></li>
                        <li <?php echo $visiting['7-1'] ?>></li>
                    </ul>

                </div>
                <div class="cometime-left  f_l">
                    下午
                </div>
                <div class="cometime-right f_l">
                    <ul>
                        <li <?php echo $visiting['1-2'] ?>></li>
                        <li <?php echo $visiting['2-2'] ?>></li>
                        <li <?php echo $visiting['3-2'] ?>></li>
                        <li <?php echo $visiting['4-2'] ?>></li>
                        <li <?php echo $visiting['5-2'] ?>></li>
                        <li <?php echo $visiting['6-2'] ?>></li>
                        <li <?php echo $visiting['7-2'] ?>></li>
                    </ul>

                </div>
            </div>


        </div>

    </div>

    <div class="doc-introduce">

        <div class="introduce-title clearfix">
            <div class="introduce-left f_l">
                <span class="icon-introduce evaluate"></span>用户评价(共 <span><?php echo $opinion_count ?></span> 条)
            </div>

        </div>

        <div class="evaluate-content" id="z_div">
            <?php foreach ($opinions as $key => $value): ?>
            <div class="evaluate-title clearfix">
                <div class="evaluate-name f_l"><?php echo $value['nick_name'] ?></div>
                <div class="evaluate-time f_r"><?php echo $value['create_time'] ?></div>
            </div>
            <div class="evaluate-description">
                <p><?php echo $value['opinion_comment'] ?></p>
            </div>
            <?php endforeach ?>
            <?php if ($opinion_count == 0): ?>
            <div class="load-more" style="margin-bottom:2rem;padding-top:1rem;background-color:#fff;" id="get-more">暂时没有评论</div>
            <div style='visibility:hidden' id="page" num='2'></div>    
            <?php else: ?>
            <div class="load-more" style="margin-bottom:2rem;" id="get-more" onclick="get_more()">点击加载更多...</div>
            <div style='visibility:hidden' id="page" num='2'></div>
            <?php endif ?>

            <!-- <div class="evaluate-title clearfix">
                <div class="evaluate-name f_l">魅灵</div>
                <div class="evaluate-time f_r">2017-04-22</div>
            </div>
            <div class="evaluate-description">
                <p>信任,会遵照执行</p>
            </div>
            <div class="evaluate-title clearfix">
                <div class="evaluate-name f_l">一丁姥姥</div>
                <div class="evaluate-time f_r">2017-03-19</div>
            </div>
            <div class="evaluate-description">
                <p>很好,谢谢</p>
            </div> -->
        </div>

    </div>
</div>
<div class="introduce-footer clearfix">
    <div class="footer-top">
        <a href="/Hospital/Advice/add_advice?doctor_id=<?php echo $_GET['doctor_id']; ?>" class="footer-left f_l ask indexask"> <img src="/Public/Hospital/index/images/icon/ask%20button.png" alt=""><span>向Ta问诊</span></a>
        <?php if (in_array($info['hospital_id'],$ke_hospital_id)){ ?>
        <a href="/Hospital/Register/register/?doctor_id=<?php echo $_GET['doctor_id']; ?>" class="footer-righter f_r order"><img src="/Public/Hospital/index/images/icon/book%20button.png"alt=""><span>预约挂号</span></a>
        <?php }else{ ?>
        <a href="javascript:;" class="footer-righter f_r order" style="background-color:#CCCCCC;"><img src="/Public/Hospital/index/images/icon/book%20button.png"alt=""><span>已预约满</span></a>
        <?php } ?>
    </div>
    
</div>
</body>

<script>
    var doctor_id = <?php echo $_GET['doctor_id'] ?>;
    //点赞
    var click_zan = true;
    function active(selecter, str) {
        var is_login = <?php echo $info['is_login'] ?>;
        if (is_login == 0) {
            if(confirm("点赞需要登录，是否登录？")){    
                window.location.href="http://www.zzlhi.com/log/action/in?refererUrl=http://<?php echo $_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'] ?>";   
            }
            return false;  
        };
//        var collect=document.getElementById("collect");
        if ($(selecter).hasClass(str)) {
            alert("您已经点过赞了");
        } else if (click_zan){
            click_zan = false;
            var new_zan = <?php echo $info['count_zan'] + 1;?>;
            $.ajax({
                type:"post",
                url:"/Hospital/Doctor/laud",
                data:{'doctor_id':doctor_id},
                success:function(data){
                    if(data.status == 1){
                        $('#zan-count').html(new_zan);
                        $(selecter).addClass(str);
                        //alert('点赞成功');
                    }else if(data.status == 2){
                        alert(data.data);
                    }else{
                        alert(data.data);
                    }
                }
            })
        }

    }

    //收藏
    var click_collect = false;
    function collect(selecter, str) {
        if (click_collect) {
            return false;
        };
        click_collect = true;
        var is_login = <?php echo $info['is_login'] ?>;
        if (is_login == 0) {
            if(confirm("点赞需要登录，是否登录？")){    
                window.location.href="http://www.zzlhi.com/log/action/in?refererUrl=http://<?php echo $_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'] ?>";   
            }
            return false;  
        };
        if ($(selecter).hasClass(str)) {
            $.ajax({
                type:"post",
                url:"/Hospital/Doctor/collect",
                data:{'doctor_id':doctor_id,'is_collect':0},
                success:function(data){
                    if(data.status == 1){
                        $(selecter).removeClass(str);
                        click_collect = false;
                    }else if(data.status == 2){
                        alert(data.data);
                        click_collect = false;
                    }else{
                        alert(data.data);
                        click_collect = false;
                    }
                }
            })
        } else {
            $.ajax({
                type:"post",
                url:"/Hospital/Doctor/collect",
                data:{'doctor_id':doctor_id,'is_collect':1},
                success:function(data){
                    if(data.status == 1){
                        $(selecter).addClass(str);
                        click_collect = false;
                    }else if(data.status == 2){
                        alert(data.data);
                        click_collect = false;
                    }else{
                        alert(data.data);
                        click_collect = false;
                    }
                }
            })
        }

    }

    //获取更多
    function get_more(){
        var page = $("#page").attr("num");
        $.ajax({
            type:"post",
            url:"/Hospital/Doctor/get_opinions",
            data:{'page':page,'doctor_id':doctor_id},
            success:function(data){
                if(data.status == 1){
                    $("#page").attr("num",parseInt(page)+parseInt(1));
                    //console.log(data.data);
                    var data = data.data;
                    for (var i = 0; i <= data.length-1; i++) {
                        //console.log(data[i]);
                        in_comment(data[i]);
                    };
                }else if(data.status == 2){
                    $("#get-more").html(data.data);
                }else{
                    alert(data.data);
                }
            }
        })
    }

    //将获取的更多的数据放入页面中
    function in_comment(data){
        var str = '<div class="evaluate-title clearfix"> <div class="evaluate-name f_l">'+data.nick_name+'</div> <div class="evaluate-time f_r">'+data.create_time+'</div> </div> <div class="evaluate-description"> <p>'+data.opinion_comment+'</p> </div>';
        $('#get-more').before(str);
    }

    //收起
    function shouqi(){
        $('#doctor_jieshao').text('<?php echo $short; ?>');
        $('#shouqi').hide();
        $('#zhankai').show();
    }
    //展开
    function zhankai(){
        $('#doctor_jieshao').text('<?php echo $long; ?>');
        $('#shouqi').show();
        $('#zhankai').hide();
    }
</script>
<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>