<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<style type="text/css">
    .bo-con-le {
        height: 2.5rem;
    }

    .fr-bottom {
        height: 6.2rem;
    }
    .fr-bot-but {
        line-height: 1.2rem;
    }
    
</style>
<body>
<div class="free-regist-all">
    <div class="fr-re-it">
        <a href="<?php echo empty($_GET['doctor_id'])?'/Hospital':'/Hospital/Doctor/detail?doctor_id='.$_GET['doctor_id'] ?>" class="fa fa-angle-left"></a>
        <span class="fr-login-l">免费问诊</span>
    </div>
    <div class="fr-in-top">
        <p class="in-top-t">温馨提示:</p>
        <p class="in-top-b">所有问题均由医生利用业余时间进行公益解答,如未能获得及时回复请耐心等待。</p>
    </div>
    <div class="fr-contain">
        <form id="p_advice" class="fr-form" method="post" enctype="multipart/form-data" >
            <div class="fe-form-in">
                <div class="form-in-fir">
                    <span class="free-p">性别:</span>
                    <div class="in-fir-r">
                        <input type="radio" class="sex" name="sex" checked value="1"><label class="s-sex boy">男</label>
                        <input type="radio" class="sex sex-r" id="fr-sex" name="sex" value="2"><label class="s-sex girl">女</label>
                    </div>
                </div>
                <div class="form-in-sec">
                    <span class="mona-p">年龄:</span>
                    <input type="number" name="age" class="age">
                </div>
            </div>
            <div class="fr-contain-b">
                <div class="con-b-t">
                    <select name="department" id="" class="con-b-t-l fl" onchange="get_doctors($(this).val())">
                        <?php foreach ($departments as $key => $value): ?>
                            <?php if ($value['department_id']==$department_id){
                                    $selected = 'selected="selected"';
                                }else{
                                    $selected = '';
                                } ?>
                            <option value="<?php echo $value['department_id'] ?>" <?php echo $selected; ?>><?php echo $value['department_name'] ?></option>
                        <?php endforeach ?>
                    </select>
                    <div class="con-b-t-san"></div>
                     <select name="doctor_id" id="doctors_id" class="con-b-t-r fr">
                         <?php foreach ($doctors as $key => $value): ?>
                            <?php if ($value['doctor_id']==$_GET['doctor_id']){
                                    $selected1 = 'selected="selected"';
                                }else{
                                    $selected1 = '';
                                } ?>
                             <option value="<?php echo $value['doctor_id'] ?>" <?php echo $selected1; ?>><?php echo $value['doctor_name'] ?></option>
                         <?php endforeach ?>
                    </select>
                    <div class="con-b-t-sanb"></div>
                </div>
                <div class="con-b-con">
                    <!-- <div class="b-con-t">
                        <input type="text" name="advice" placeholder="请输入您要咨询的主题">
                    </div> -->
                    <textarea name="comment" id="" cols="48" rows="5" placeholder="请详细描述您的病情、症状、治疗经过以及想要获得的帮助" class="main-main"></textarea>
                </div>
            </div>
            <div class="fr-bottom">
                <div class="fr-bo-top">上传报告</div>
                <div class="fr-bo-con">
                    <div class="bo-con-le">
                        <p>上传就诊病历/检查报告/病状报告</p>
                        <p>
                            <input type="checkbox" checked="checked" disabled="disabled" class="con-le-check">
                            <span>图片仅医生可见</span>
                        </p>
                        <p>
                            <label for="niname"><input type="checkbox" id="niname" name="niname" class="con-le-check">
                            <span>匿名提问</span></label>
                        </p>
                    </div>
                    <div class="bo-con-ri">
                        <input type="file" id="freefileT" name="pic1" class="fr-in_file">
                        <img class="fr-imgLogoT" src="/Public/Hospital/index/images/tianjia.png">
                    </div>
                    <div class="bo-con-ri">
                        <input type="file" id="freefileC" name="pic2" class="fr-in_file">
                        <img class="fr-imgLogoC" src="/Public/Hospital/index/images/tianjia.png">
                    </div>
                    <div class="bo-con-ri">
                        <input type="file" id="freefileB" name="pic3" class="fr-in_file">
                        <img class="fr-imgLogoB" src="/Public/Hospital/index/images/tianjia.png">
                    </div>
                </div>
            </div>
            <div class="doc-fr-sub">
            <div class="fr-bot-but" onclick="javascript:submitAdd();">提交咨询</div>
            </div>
        </form>
    </div>
</div>
<script>
    function get_doctors(b){
        $.ajax({
            type:"post",
            url:"/Hospital/Advice/get_doctors",
            data:{'department_id':b},
            success:function(data){
                if(data.status == 1){
                    var data = data.data;
                    $('#doctors_id').children('option').remove()
                    for (var i = 0; i <= data.length-1; i++) {
                        var str = '<option value="'+data[i].doctor_id+'">'+data[i].doctor_name+'</option>';
                        $('#doctors_id').append(str);
                    };
                }else if(data.status == 0){
                    alert(data.data);
                    window.location.reload();
                }
            }
        })
    }

    var is_submit = true;
    function submitAdd(){
        if ($(".age").val() == ""){
         alert("请输入年龄") ;
         return false;
        }
        else if($(".main-main").val() == ""){
            alert("请输入你要咨询的问题");
            return false;
        }else if(is_submit){
            is_submit = false;
            var formData = new FormData($( "#p_advice" )[0]);
            $.ajax({
                cache: true,
                type: "POST",
                url:"/Hospital/Advice/do_add_advice",
                data:formData,// 你的formid
                async: false,
                cache: false,  
                contentType: false,  
                processData: false, 
                error: function(data) {
                  alert('网络连接错误');
                  is_submit = true;
                },
                success: function(data) {
                    if (data.error_code == 1) {
                        alert(data.data);
                        window.location.href="/Hospital/Advice/advice_info?advice_id="+data.advice_id;                        
                    }else{
                        alert(data.data);
                        is_submit = true;
                    }  
                }
            });
        }
    }
   
</script>
</body>
<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>