<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<body class="gray-bg">
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-sm-12">
                <div class="ibox float-e-margins">
                   <div class="ibox-title">
                        <h5>账户激活</h5>
                    </div>
                    <div class="ibox-content">
                     <div class="member-warn">
                            <div class="alert alert-danger">
                               <i class="fa fa-warning"></i> 激活账户后，您将可以使用本平台的的全部功能！否则基本实际功能您只能查看，无法操作。<b>（现在仅需 ￥<?php echo $activate_price; ?> 元，即可激活三个月）</b>
                            </div>
                        </div>
                        <form class="form-horizontal m-t" id="commentForm">
                         <div class="form-group">
                                <label class="col-sm-3 control-label">商户ID：</label>
                                <div class="col-sm-8">
                                    <input class="form-control" type="text"  style='' value="<?php echo $result['business_id']; ?>" disabled>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">当前状态：</label>
                                <div class="col-sm-8">
                                    <input class="form-control" type="text" style='' value="<?php echo $result['status'] == 1 ? '已激活' : '未激活'; ?>" disabled>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">激活时间：</label>
                                <div class="col-sm-8">
                                    <input class="form-control" type="text" style='' value="<?php echo $result['status'] == 1 ? $result['activate_time'] : '未激活'; ?>" disabled>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">过期时间：</label>
                                <div class="col-sm-8">
                                 <input class="form-control" type="text" style='' value="<?php echo $result['lose_time'] ? $result['lose_time'] : '未激活'; ?>" disabled>
                                </div>
                            </div>
                            <div class="form-group form-group-bottom">
                                <div class="col-sm-2 col-sm-offset-3">
                                    <?php if($result['status'] == 1): ?>
                                    <p class="btn btn-primary" disabled>您已激活</p>
                                    <?php else: ?>
                                    <p class="btn btn-danger" onclick="javascript:doActivate();">立即激活</p>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>
<script>
    //账户激活
    function doActivate(){
        swal({
            title: "确定激活账户吗？",
            text: "您需通过支付宝 支付 <?php echo $activate_price; ?> 元",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "是的！我要激活",
            cancelButtonText: "我再考虑一下",
            closeOnConfirm: false,
            closeOnCancel: true
        },
        function(isConfirm) {
            if (isConfirm) {
                // $.ajax({
                //     cache: true,
                //     type: "POST",
                //     url:"/Business/Center/activate",
                //     data: {},
                //     dataType: 'json',
                //     async: false,
                //     error: function(data) {
                //         alert('网络错误');
                //     },
                //     success: function(data) {
                //         if (data.error == 0) {
                //             swal(data.msg, "请按F5键刷新网页查看效果", "success");
                //             return false;
                //         }else{
                //             swal(data.msg, "", "error");
                //             return false;
                //         }
                //     }
                // });
                window.location.href = '/Business/Center/do_activate';
            }
        })
    }
</script>