<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<body class="gray-bg">
    <div class="wrapper wrapper-content animated fadeInRight">
       
        <div class="row">
            <div class="col-sm-12">
                <div class="ibox float-e-margins">
                   <div class="ibox-title">
                            <h5>密码重置</h5>  
                    </div>
                    <div class="ibox-content">
                        <form class="form-horizontal m-t" id="commentForm">
                         <div class="form-group">
                                <label class="col-sm-3 control-label">旧密码：</label>
                                <div class="col-sm-8">
                                    <input id="o_password" name="o_password" class="form-control" type="password" maxlength="16">
                                </div>
                            </div>
                           <div class="form-group">
                                <label class="col-sm-3 control-label">新密码：</label>
                                <div class="col-sm-8">
                                    <input id="n_password" name="n_password" class="form-control" type="password" maxlength="16">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">确认新密码：</label>
                                <div class="col-sm-8">
                                    <input id="c_password" name="c_password" class="form-control" type="password" maxlength="16">
                                    <span class="help-block m-b-none"><i class="fa fa-info-circle"></i> 请再次输入您的密码</span>
                                </div>
                            </div>
                            <div class="form-group form-group-bottom">
                                <div class="col-sm-2 col-sm-offset-3">
                                    <p id="save_submit" class="btn btn-primary">提交</p>
                                </div>
                                 <div class="col-sm-2">
                                   <button class="btn btn-default" type="reset">取消</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            
            </div>
           
        </div>
    </div>


</body>
<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>

    <script>
        $(document).ready(function(){$(".i-checks").iCheck({checkboxClass:"icheckbox_square-green",radioClass:"iradio_square-green",})});

        $("#save_submit").click(function(){
            if (!$('input[name=o_password]').val()) {
                swal('原密码未填写', "", "error");
                return false;
            }

            if (!$('input[name=n_password]').val()) {
                swal('新密码未填写', "", "error");
                return false;
            }
            
            if ($('input[name=n_password]').val().length < 6 || $('input[name=n_password]').val().length > 16) {
                swal('请输入6~16位密码', "", "error");
                return false;
            }

            if ($('input[name=n_password]').val() != $('input[name=c_password]').val()) {
                swal('两次新密码不一致', "", "error");
                return false;
            }
            swal({
                title: "修改密码后将重新登录，您是否要修改吗？",
                text: "",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "是的，我要修改！",
                cancelButtonText: "让我再考虑一下…",
                closeOnConfirm: false,
                closeOnCancel: true
            },
            function(isConfirm) {
                if (isConfirm) {
                    $.ajax({
                        cache: true,
                        type: "POST",
                        url:"/Business/Center/repassword",
                        data:$('#commentForm').serialize(),// 你的formid
                        dataType: 'json',
                        async: false,
                        error: function(data) {
                           swal('网络错误，请重试！', "", "warning");
                        },
                        success: function(data) {
                            if (data.error == 0) {
                                swal("修改成功！", "", "success");
                                setTimeout("window.location.href='/Business/Log/out';",1000);
                            }else{
                                swal(data.msg, "", "error");
                            }
                        }
                    });
                    
                }
            })
            
                
            
        });
    </script>

