<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<style>
.laydate_body .laydate_table {
    display: none;
    width: 240px!important;
    margin: 0!important;
    border: 1px solid #ccc;
    border-top: none;
    border-bottom: none;
}
#laydate_MM{
	 display: none!important;
}
.laydate_body .laydate_ym {
    border: 1px solid #009F95;
    background-color: #009F95;
    width: 228px !important;
}
.laydate_body .laydate_y input {
    width: 171px !important;
    margin-right: 15px;
}
.laydate_body .laydate_y .laydate_yms {
    width: 229px !important;
    text-align: center;
}
</style>
<body class="gray-bg">
    <div class="wrapper wrapper-content animated fadeInRight">
    	<div class="ibox float-e-margins">
          <div class="ibox-title">
               <h5>销售统计（分组）</h5>
                <span class="label label-primary pull-right label-primary-cust">
                    <?php if($_GET['back'] == 'true'): ?>
                    <a href="javascript:history.back(-1);" class="fa-lg-cust-a" title="返回上一页">
                        <i class="fa fa-arrow-left fa-lg-cust"  aria-hidden="true"></i>
                    </a>
                    <?php endif; ?>
                </span> 
          </div>
          <div class="ibox-content">
	    	<div class="alert alert-info">
		    	<div class="row">
		            <div class="col-sm-8">
			            <input id="year" value="<?php echo $_GET['year'] ? $_GET['year'] : date('Y-m'); ?>" class="laydate-icon form-control layer-date datepicker" style='width: 40%;margin-top: -8px; margin-right: 5px'>
			            <button type="button" class="btn btn-primary" data-container="body" onclick="javascript:enterYear();" data-toggle="popover" data-placement="left" style='padding: 5px 10px;margin-top:-3px;margin-right: 5px'>
			                查看
			            </button>
			            <button type="button" class="btn btn-success" data-container="body" onclick="javascript:enterYear('theYear');" data-toggle="popover" data-placement="left" style='padding: 5px 10px;margin-top: -3px; margin-right: 5px'>
			                当月
			            </button>
		            </div>
		        </div>
	            </div>
        	</div>
	        </div>
   
        <div class="row">
            <div class="col-sm-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>（积分商城）商品销售量（件/组）</h5>
                   
                    </div>
                    <div class="ibox-content">
                        <div class="echarts" id="echarts-line-chart"></div>
                    </div>
                </div>
            </div>
            
        </div>
          <div class="row">
            <div class="col-sm-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>（积分商城）商品销售额（共享币/组）</h5>
                   
                    </div>
                    <div class="ibox-content">

                        <div class="echarts" id="echarts-bar-chart1"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>

<script src="/Public/hplus/js/plugins/echarts/echarts-all.js"></script>

<script>
	$('.datepicker').datepicker({  
		language: "zh-CN",
		todayHighlight: true,
		format: 'yyyy-mm',
		autoclose: true,
		startView: 'months',
		maxViewMode:'months',
		minViewMode:'months'
	});      
</script>

<script>
	function enterYear(year){
		if(year == 'theYear'){
			window.location.href = '/Business/Finance/orders_count_group?year=<?php echo date('Y-m'); ?>'
		}else{
			window.location.href = '/Business/Finance/orders_count_group?year=' + $('#year').val();
		}
	}


</script>

<script>
    $(function() {
         
	    var e = echarts.init(document.getElementById("echarts-line-chart")),
	    a = {
	        title: {
	            text: ""
	        },
	        tooltip: {
	            trigger: "axis"
	        },
	        legend: {
	            data: ["销售量"],
	             x: "right"
	        },
	       grid:{
			  	left:'5%',//组件距离容器左边的距离
			  	right:'4%',
			  	bottom:'7%',
			  },
	        calculable: !0,
	        xAxis: [{
	            type: "category",
	            boundaryGap: !1,
	            data: [<?php echo $str_group; ?>]
	        }],
	        yAxis: [{
	            type: "value",
	            axisLabel: {
	                formatter: "{value} "
	            }
	        }],
	        series: [{
	            name: "销售量",
	            type: "line",
	            barMaxWidth:30,//最大宽度
	            data: [<?php echo $str_agentNum_count; ?>],
	            markPoint: {
	                data: [{
	                    type: "max",
	                    name: "最大值"
	                },
	                {
	                    type: "min",
	                    name: "最小值"
	                }]
	            },
	            markLine: {
	                data: [{
	                    type: "average",
	                    name: "平均值"
	                }]
	            }
	        }]
	    };
	    e.setOption(a),
	    $(window).resize(e.resize);
	    var t1 = echarts.init(document.getElementById("echarts-bar-chart1")),
	    n1 = {
	        title: {
	            text: ""
	        },
	        tooltip: {
	            trigger: "axis"
	        },
	        legend: {
	            data: ["销售额",],
	             x: "right"
	        },
	        grid:{
			  	left:'5%',//组件距离容器左边的距离
			  	right:'4%',
			  	bottom:'7%',
			  },
	        calculable: !0,
	        xAxis: [{
	            type: "category",
	            data: [<?php echo $str_group; ?>]
	        }],
	        yAxis: [{
	            type: "value"
	        }],
	        series: [{
	            name: "销售额",
	            type: "bar",
	            data: [<?php echo $str_agentPiao_count; ?>],
	            markPoint: {
	                data: [{
	                    type: "max",
	                    name: "最大值"
	                },
	                {
	                    type: "min",
	                    name: "最小值"
	                }]
	            },
	            markLine: {
	                data: [{
	                    type: "average",
	                    name: "平均值"
	                }]
	            }
	        }]
	    };
	    t1.setOption(n1),
	    window.onresize = t1.resize;
    
        
});
    
</script>