<?php require_once MODULE_PATH.'/View/Common/header.phtml'; ?>
<style>
.jiaobiao {
    position: absolute;
    right: 110px;
    top: 7px;
}
.jiaobiao-right{
   position: absolute;
    right: 0px;
    top: 13px;
    padding: 2px 4px;
    font-size: 6px;
}
</style>
<body class="fixed-sidebar full-height-layout gray-bg" style="overflow:hidden">
    <div id="wrapper">
        <!--左侧导航开始-->
        <nav class="navbar-default navbar-static-side" role="navigation">
            <div class="nav-close"><i class="fa fa-times-circle"></i>
            </div>
            <div class="sidebar-collapse">
                <ul class="nav" id="side-menu">
                    <li class=" nav-header">
                        <div class="dropdown profile-element">
                            <span><img id="business_logo" alt="image" title="在这里共享商企平台" class="img-circle" width="64" height="64" src="/Public/hplus/img/black_logo.png" /></span>
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                                <span class="clear" style='padding-right: 10px;position: relative;'>
                                    <span class="text-muted text-xs block" style='max-width:170px;height: 30px;overflow: hidden;' title="<?php echo $info['exchange_name']; ?>">
                                        <?php if($info['is_dai'] == 1): ?>
                                        <span title="您是代理商" class="label label-success" >商</span>&nbsp;&nbsp;
                                        <?php endif; ?>
                                        <?php echo $info['exchange_name']; ?>
                                    </span>
                                    <b class="caret" style="position: absolute;top: 14px;right: 0;"></b>
                                </span>
                            </a>
                            <ul class="dropdown-menu animated fadeInRight m-t-xs">
                                <li><a class="J_menuItem" href="/Business/Center/edit_logo">修改商城</a>
                                </li>
                                <li><a href="/Business/Log/out">安全退出</a>
                                </li>

                            </ul>
                        </div>
                        <div class="logo-element">在这里共享商企平台
                        </div>
                    </li>
                    <li>
                        <a class="J_menuItem" href="/Business/Index/index_base">
                            <i class="fa fa-home"></i>
                            <span class="nav-label">首页</span>
                        </a>
                    </li>
                    
                    <li>
                        <a href="#">
                            <i class="fa fa fa-shopping-cart"></i>
                            <span class="nav-label">商品管理</span>
                            <span class="fa arrow"></span>
                        </a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a class="J_menuItem" href="/Business/Goods/exchange"><span class="text-warning">共享商品池</span></a>
                            </li>
                            <li>
                                <a class="J_menuItem" href="/Business/Goods/myexchangeinfo">我的商城信息</a>
                            </li>
                            <li>
                                <a class="J_menuItem" href="/Business/Goods/lists">我的商品</a>
                            </li>
                            <li>
                                <a class="J_menuItem" href="/Business/Goods/myagent">我代理的商品</a>
                            </li>
                            <li>
                                <a class="J_menuItem" href="/Business/Goods/group_list">分组管理</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#">
                        <i class="fa fa-envelope"></i>
                         <span class="nav-label">会员管理 </span>
                         <span class="fa arrow"></span>
                         </a>
                        <ul class="nav nav-second-level">
                            <li><a class="J_menuItem" href="/Business/Member/lists">会员列表</a></li>
                            <li><a class="J_menuItem" href="/Business/Member/not_formal_list">临时会员</a></li>
                            <li><a class="J_menuItem" href="/Business/Member/add">会员添加</a></li>
                            <li><a class="J_menuItem" href="/Business/Member/member_count">会员统计</a></li>
                            <li><a class="J_menuItem" href="/Business/Member/piao_send">发放共享币（录营业额）</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#">
                        <i class="fa fa-yen"></i> 
                        <span class="nav-label">财务管理</span>
                        <span class="fa arrow"></span>
                        </a>
                        <ul class="nav nav-second-level">
                            <li><a class="J_menuItem" href="/Business/Finance/recharge">共享币充值</a></li>
                            <li><a class="J_menuItem" href="/Business/Finance/withdraw">共享币提现</a></li>
                            <li><a class="J_menuItem" href="/Business/Finance/piao_log">共享币明细</a></li>
                            <li><a class="J_menuItem" href="/Business/Finance/bank_card">绑定银行卡</a></li>
                            <li><a class="J_menuItem" href="/Business/Finance/finance_log">充值提现记录</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#">
                        <i class="fa fa-tag"></i> 
                        <span class="nav-label">订单管理</span>
                        <span class="fa arrow"></span>
                        </a>
                        <ul class="nav nav-second-level">
                            <li><a class="J_menuItem" href="/Business/Finance/orders">销售订单</a></li>
                            <li><a class="J_menuItem" href="/Business/Finance/return_orders">退货订单</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-edit"></i> <span class="nav-label">销售统计</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li><a class="J_menuItem" href="/Business/Finance/capital_info">业务信息</a></li>
                            <li><a class="J_menuItem" href="/Business/Finance/orders_count_year">销售统计（每年）</a></li>
                            <li><a class="J_menuItem" href="/Business/Finance/orders_count_month">销售统计（每月）</a></li>
                            <li><a class="J_menuItem" href="/Business/Finance/orders_count_group">销售统计（分组）</a></li>
                            <li><a class="J_menuItem" href="/Business/Finance/order_count_level">销售统计（级别）</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-desktop"></i> <span class="nav-label">商户中心 <span class="label label-warning notices_num"></span></span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a class="J_menuItem" href="/Business/Center/info">商户资料</a>
                            </li>
                            <li>
                                <a class="J_menuItem" href="/Business/Center/repassword">密码重置</a>
                            </li>
                            <li>
                                <a class="J_menuItem" href="/Business/Center/notices">通知</a>
                                <span class="label label-warning jiaobiao notices_num" ></span>
                            </li>
                            <li>
                                <a class="J_menuItem" href="/Business/Center/recommend">推荐奖励</a>
                            </li>
                            <?php if($info['is_dai'] == 1): ?>
                            <li>
                                <a class="J_menuItem" href="/Business/Center/recommend_list?business_id=<?php echo $_SESSION['business']['business_id'] ?>&is_start=1&recommend=<?php echo $_SESSION['business']['business_id'] ?>">我的团队</a>
                                <span title="代理商专属功能" class="label label-success jiaobiao" style="right: 77px;" >商</span>
                            </li>
                            <?php endif; ?>
                        </ul>
                    </li>
                     <li>
                        <a href="#"><i class="glyphicon glyphicon-earphone"></i> <span class="nav-label">帮助</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li><a class="J_menuItem" href="/Business/Center/placard">公告</a>
                            </li>
                            <li><a class="J_menuItem" href="/Business/Center/about_us">关于我们</a>
                            </li>
                        </ul>
                    </li>

                </ul>
            </div>
        </nav>
        <!--左侧导航结束-->
        <!--右侧部分开始-->
        <div id="page-wrapper" class="gray-bg dashbard-1">
            <div class="row content-tabs">
             <div class="navbar-header"><a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
                      
                    </div>
                <button class="roll-nav roll-left J_tabLeft"><i class="fa fa-backward"></i>
                </button>
                <nav class="page-tabs J_menuTabs">
                    <div class="page-tabs-content">
                        <!-- <a href="javascript:;" class="active J_menuTab" data-id='/Business'>首页</a> -->
                    </div>
                </nav>
                <button class="roll-nav roll-right J_tabRight"><i class="fa fa-forward"></i>
                </button>
                <div class="btn-group roll-nav roll-right">
                    <button class="dropdown J_tabClose" data-toggle="dropdown">关闭操作<span class="caret"></span>

                    </button>
                    <ul role="menu" class="dropdown-menu dropdown-menu-right">
                        <li class="J_tabShowActive"><a>定位当前选项卡</a>
                        </li>
                        <li class="divider"></li>
                        <!-- <li class="J_tabCloseAll"><a>关闭全部选项卡</a> -->
                        <!-- </li> -->
                        <li class="J_tabCloseOther"><a>关闭其他选项卡</a>
                        </li>
                    </ul>
                   
                </div>
                 <ul class="nav navbar-top-links navbar-right" style="margin-right: -30px;">
                        <li class="dropdown">
                            <a class="J_menuItem"  href="/business/center/activate">
                                <?php if($info['status'] == 1): ?>
                                <i class="fa fa-get-pocket" style="color:#FF9800"></i> <span style="color:#FF9800">已激活</span>    
                                <?php else: ?>
                                <i class="fa fa-get-pocket" style="color:#3F51B5"></i> <span style="color:#3F51B5">未激活</span>    
                                <?php endif; ?>
                            </a>
                        </li>
                        <li class="dropdown">
                            <a class="dropdown-toggle count-info J_menuItem"  href="/business/center/notices">
                                <i class="fa fa-bell"></i> 通知 
                            </a>
                            <span class="label label-warning jiaobiao-right notices_num"></span>
                        </li>
                        <li class="dropdown ">
                            <a class="right-sidebar-toggle" aria-expanded="false">
                                <i class="fa fa-tasks"></i> 主题
                            </a>
                        </li>
                    </ul>
            </div>
            <div class="row J_mainContent" id="content-main">
                <iframe class="J_iframe" name="iframe0" width="100%" height="100%" src="/Business/Index/index_base" frameborder="0"  seamless></iframe>
            </div>
            <div class="footer">
                <div class="">&copy; 在这里共享商企平台 版权所有</a>
                </div>
            </div>
        </div>
        <!--右侧部分结束-->
        <!--右侧边栏开始-->
        <div id="right-sidebar">
            <div class="sidebar-container">
                <div class="tab-content">
                    <div id="tab-1" class="tab-pane active">
                      
                        <div class="skin-setttings">
                            <div class="title">主题设置</div>
                            <div class="setings-item">
                                <span>收起左侧菜单</span>
                                <div class="switch">
                                    <div class="onoffswitch">
                                        <input type="checkbox" name="collapsemenu" class="onoffswitch-checkbox" id="collapsemenu">
                                        <label class="onoffswitch-label" for="collapsemenu">
                                            <span class="onoffswitch-inner"></span>
                                            <span class="onoffswitch-switch"></span>
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <div class="setings-item">
                                <span>固定顶部</span>

                                <div class="switch">
                                    <div class="onoffswitch">
                                        <input type="checkbox" name="fixednavbar" class="onoffswitch-checkbox" id="fixednavbar">
                                        <label class="onoffswitch-label" for="fixednavbar">
                                            <span class="onoffswitch-inner"></span>
                                            <span class="onoffswitch-switch"></span>
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <div class="setings-item">
                                <span>固定宽度</span>
                                <div class="switch">
                                    <div class="onoffswitch">
                                        <input type="checkbox" name="boxedlayout" class="onoffswitch-checkbox" id="boxedlayout">
                                        <label class="onoffswitch-label" for="boxedlayout">
                                            <span class="onoffswitch-inner"></span>
                                            <span class="onoffswitch-switch"></span>
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <div class="title">皮肤选择</div>
                            <div class="setings-item default-skin nb">
                                <span class="skin-name ">
                         <a href="#" class="s-skin-0">
                             绿色主题
                         </a>
                    </span>
                            </div>
                            <div class="setings-item  blue-skin  nb">
                                <span class="skin-name ">
                        <a href="#" class="s-skin-1">
                            蓝色主题
                        </a>
                    </span>
                            </div>
                            <div class="setings-item yellow-skin nb">
                                <span class="skin-name ">
                        <a href="#" class="s-skin-3">
                            黄色主题
                        </a>
                    </span>
                            </div>
                        </div>
                    </div>
                
                </div>

            </div>
        </div>
    </div>
   
</body>
<?php require_once MODULE_PATH.'/View/Common/footer.phtml'; ?>
<script type="text/javascript">
    var a = 0;
    function get_notices_num(){
        $.ajax({
            cache: true,
            type: "POST",
            url: "/Business/Center/notices_num",
            dataType: 'json',
            async: false,
            error: function(data) {
              
            },
            success: function(data) {
                if (data.notices_num != 0) {
                    $('.notices_num').html(data.notices_num);
                }else{
                    $('.notices_num').html('');
                }
                if (data.error == 0) {
                    $('#business_logo').attr('src',data.business_logo);
                }
            }
        });

    }
    get_notices_num();
    setInterval(get_notices_num,60000);
</script>